### PR TITLE
[FTheoryTools] Fixed some bugs that were missed before

### PR DESCRIPTION
**Pull request by emikelsons**
Some small bug fixes that were missed in some recents pull requests relating to model indexes and zero section classes of FTheory models:

- model_index doesn't result in errors anymore(there might have been a defunct method that was used before)
- Model constructors now no longer attempt to set a zero_section_class for models constructed over an arbitrary base
- For Tate and Weierstrass models the zero section class is now always set to be 'z'

### CODE REVIEW

**Comment by emikelsons** [comment]
@apturner @HereAround

**Comment by HereAround** [comment]
Looks good to me. Unless you are still working on this @emikelsons , it can be merged.

Regarding the failed book-tests (cf. https://github.com/oscar-system/Oscar.jl/actions/runs/11269198738/job/31337353429), which prevent the merge at this point: I could not see exactly why they failed. The error message "The operation was cancelled" was not very enlightening to me. So I just restarted those tests.

One possibly very naive idea: The book tests failed after about 2.5 hours. Could it maybe be a time-out error?

**Comment by emikelsons** [comment]
The error that was raised previously was not a time-out error, but that one doesn't seem to appear any longer

**Comment by HereAround** [comment]
> The error that was raised previously was not a time-out error, but that one doesn't seem to appear any longer

It seems the error has disappeared. As such, I will merge this now.

**Review by HereAround — APPROVED** [review]
Thank you for working on this @emikelsons

**Pull request merged**
