### PR TITLE
Renaming for localizations

### PR DESCRIPTION
**Pull request by HechtiDerLachs**
Some work for #3054 .

 - un-export a lot of concrete types in the localizations
 - rename `ambient_ring` to simply `ring` 
 - un-export some functions

### CODE REVIEW

**Comment by thofma** [comment]
If we have a localized module, how do we get the underlying module back? What is the name of the function?

P.S.: I am just worried about some mismatch, because we have `ring`, but we cannot have a function named `module`.

**Comment by fingolfin** [comment]
Could you say a bit about the motivation for renaming to `ambient_ring` to `ring` (I am not opposed, just wondering)

**Comment by HechtiDerLachs** [comment]
@thofma : There has never been a function to get the underlying module back, really. Do you think we need it? One problem is that the module does not know that it came from a localization in the first place. 

@fingolfin : I just recalled various talks with @fieker suggesting to rename `base_ring` just into `ring`. The name `base_ring` might be too established to do this on such short notice. But at least for `ambient_ring` I thought, I could give it a try.

**Comment by thofma** [comment]
I think `ring` is a rather unfortunate name. It would be similar to calling the $R$ in $R[x]$ *the* ring of $R[x]$.

**Comment by HechtiDerLachs** [comment]
But we're not talking about renaming `base_ring` by `ring` here. I renamed `ambient_ring` for multiplicative sets by `ring`. I think that's unambiguous, isn't it?

**Comment by thofma** [comment]
Sorry, my bad. I was confused.

**Comment by lgoettgens** [comment]
Could you add deprecations for your renaming?

**Comment by HechtiDerLachs** [comment]
There is only one command that has only changed its name. For the rest I simply don't want to export it anymore. Is this legitimate? Back in the days when I wrote the code, I simply didn't have a feeling for it.

**Comment by lgoettgens** [comment]
If there are other dispatches for `ambient_ring`, you should use `@deprecate` with a concrete signature instead. It's best if you have a look at deprecations.jl (and maybe put the deprecation there)

**Comment by HechtiDerLachs** [comment]
@bschroter : It seems that you are using `ambient_ring`  for your realization spaces, too. Could/should this also be changed to `ring`?

**Comment by HechtiDerLachs** [comment]
From my side this can be merged. My question to @bschroter was more a heads up and can be resolved elsewhere.

**Review by simonbrandhorst — APPROVED** [review]

**Comment by dcorey2814** [comment]
> @bschroter : It seems that you are using `ambient_ring` for your realization spaces, too. Could/should this also be changed to `ring`?

`ambient_ring` is referring to the polynomial ring where the defining ideal and multiplicative semigroup live. `ring` could be ambiguous since one may think this produces the coordinate ring of the matroid realization space.

**Pull request merged**
