### PR TITLE
Add back serialization for universal polynomials

### PR DESCRIPTION
**Pull request by SoongNoonien**
@fingolfin is this what you meant in #2158?

### CODE REVIEW

**Comment by SoongNoonien** [comment]
I think this wont fix https://github.com/oscar-system/Oscar.jl/issues/2158. As the problem seems to be in another package.

**Comment by SoongNoonien** [comment]
@HereAround I think the new title is not correct. I meant "readd" in terms of "to add again".

**Comment by HereAround** [comment]
> @HereAround I think the new title is not correct. I meant "readd" in terms of "to add again".

Ohh. Ok. Sorry then.

**Comment by fingolfin** [comment]
This is what I had in mind, yes, thank you. And of course the CI will fail here, as we did not yet fix the underlying issue. But once it is fixed, we can merge this again. By having the PR open now, we won't forget about it :-)

**Comment by thofma** [comment]
I pushed the fix in AA and made a new release. Everything should be green now.

**Review by fingolfin — APPROVED** [review]

**Pull request merged**
