### PR TITLE
docs: change some '->' to proper LaTeX arrows

### PR DESCRIPTION
**Pull request by fingolfin**

### CODE REVIEW

**Comment by wdecker** [comment]
@fingolfin As we had this dicussion before, and as this "Problem" appears at various places in the docu, let us discuss things over on Monday and find a "final solution".

**Review by wdecker — APPROVED** [review]

**Review by HechtiDerLachs — APPROVED** [review]
These changes improve the readability of the documentation in the REPL. The constructions like `R` ``\to`` `Q` are not too beautiful, but they are a reasonable compromise.

**Comment by HechtiDerLachs** [comment]
One test fails here while the others don't. Might this be due to a faulty generation of random elements in the gmodules? 

(CC: @fieker , @thofma )

**Comment by benlorenz** [comment]
I have restarted the failing test-run, the error is already reported here: https://github.com/oscar-system/Oscar.jl/issues/1912

**Pull request merged**
