### PR TITLE
Orthogonal groups via orthogonal decomposition

### PR DESCRIPTION
**Pull request by simonbrandhorst**

### CODE REVIEW

**Comment by simonbrandhorst** [comment]
I have trouble debugging the following. To reproduce it run 

 ``` 
  N1 = root_lattice(:A, 2)
  N2 = rescale(N1, 4)
  N,_,_ = Hecke.orthogonal_sum(N1,N2)
  orthogonal_group(N)
```

On this branch. It is also in the test folder.
@thofma @ThomasBreuer @StevellM @fingolfin 

```
Computing the kernel of Group homomorphism from 
Matrix group of degree 4 over Rational Field
to
Group of isometries of TorQuadMod 0 by 0 empty matrix generated by 4 elements
Error During Test at REPL[40]:1
  Test threw exception
  Expression: order(orthogonal_group(N))
  Error thrown by GAP: Error, recursion depth trap (5000) in
    MakeGroupyType( family, IsMagmaWithInverses and IsAttributeStoringRep and HasGeneratorsOfMagmaWithInverses and HasIsEmpty, gens, fail, false ) at /home/simon/.julia/artifacts/80196249c050204d1b65e3b9f8b41878914c2cb0/share/gap/lib/magma.gi:715 called from 
  MakeMagmaWithInversesByFiniteGenerators( FamilyObj( gens ), gens ) at /home/simon/.julia/artifacts/80196249c050204d1b65e3b9f8b41878914c2cb0/share/gap/lib/magma.gi:731 called from
  MagmaWithInversesByGenerators( gens ) at /home/simon/.julia/artifacts/80196249c050204d1b65e3b9f8b41878914c2cb0/share/gap/lib/magma.gi:619 called from
  SubgroupNC( Source( hom ), MappingGeneratorsImages( hom )[1] ) at /home/simon/.julia/artifacts/80196249c050204d1b65e3b9f8b41878914c2cb0/share/gap/lib/ghom.gi:650 called from
  PreImagesRange( map ) at /home/simon/.julia/artifacts/80196249c050204d1b65e3b9f8b41878914c2cb0/share/gap/lib/mapping.gi:574 called from
  IsTotal( InverseGeneralMapping( hom ) ) at /home/simon/.julia/artifacts/80196249c050204d1b65e3b9f8b41878914c2cb0/share/gap/lib/ghom.gi:723 called from
  ...  at *defin*:0
  
  Stacktrace:
    [1] error(s::String)
      @ Base ./error.jl:33
    [2] ThrowObserver(depth::Int32)
      @ GAP ~/.julia/packages/GAP/2o1Ra/src/GAP.jl:68
    [3] _call_gap_func(func::GAP_jll.GapObj, a1::GAP_jll.GapObj)
      @ GAP ~/.julia/packages/GAP/2o1Ra/src/ccalls.jl:258
    [4] call_gap_func_nokw
      @ ~/.julia/packages/GAP/2o1Ra/src/ccalls.jl:224 [inlined]
    [5] (::GAP_jll.GapObj)(a1::GAP_jll.GapObj)
      @ GAP ~/.julia/packages/GAP/2o1Ra/src/ccalls.jl:235
    [6] kernel(f::GAPGroupHomomorphism{MatrixGroup{fmpq, fmpq_mat}, AutomorphismGroup{Hecke.TorQuadMod}})
      @ Oscar ~/.julia/dev/Oscar/src/Groups/homomorphisms.jl:272
    [7] _isometry_group_via_decomposition(L::ZLat)
      @ Oscar ~/.julia/dev/Oscar/src/Groups/matrices/form_group.jl:784
    [8] var"##compute_isometry_group#294"(L::ZLat)
      @ Oscar ~/.julia/dev/Oscar/src/Groups/matrices/form_group.jl:699
    [9] #3140
      @ ~/.julia/packages/AbstractAlgebra/GyvKf/src/Attributes.jl:344 [inlined]
   [10] get!(default::Oscar.var"#3140#3141"{ZLat}, h::Dict{Symbol, Any}, key::Symbol)
      @ Base ./dict.jl:464
   [11] get_attribute!
      @ ~/.julia/packages/AbstractAlgebra/GyvKf/src/Attributes.jl:225 [inlined]
   [12] isometry_group
      @ ~/.julia/dev/Oscar/src/Groups/matrices/form_group.jl:694 [inlined]
   [13] orthogonal_group(L::ZLat)
      @ Oscar ~/.julia/dev/Oscar/src/Groups/matrices/form_group.jl:814
   [14] top-level scope
      @ ~/julia-1.7.2/share/julia/stdlib/v1.7/Test/src/Test.jl:445
   [15] eval
      @ ./boot.jl:373 [inlined]
   [16] eval_user_input(ast::Any, backend::REPL.REPLBackend)
      @ REPL ~/julia-1.7.2/share/julia/stdlib/v1.7/REPL/src/REPL.jl:150
   [17] repl_backend_loop(backend::REPL.REPLBackend)
      @ REPL ~/julia-1.7.2/share/julia/stdlib/v1.7/REPL/src/REPL.jl:246
   [18] start_repl_backend(backend::REPL.REPLBackend, consumer::Any)
      @ REPL ~/julia-1.7.2/share/julia/stdlib/v1.7/REPL/src/REPL.jl:231
   [19] run_repl(repl::REPL.AbstractREPL, consumer::Any; backend_on_current_task::Bool)
      @ REPL ~/julia-1.7.2/share/julia/stdlib/v1.7/REPL/src/REPL.jl:364
   [20] run_repl(repl::REPL.AbstractREPL, consumer::Any)
      @ REPL ~/julia-1.7.2/share/julia/stdlib/v1.7/REPL/src/REPL.jl:351
   [21] (::Base.var"#930#932"{Bool, Bool, Bool})(REPL::Module)
      @ Base ./client.jl:394
   [22] #invokelatest#2
      @ ./essentials.jl:716 [inlined]
   [23] invokelatest
      @ ./essentials.jl:714 [inlined]
   [24] run_main_repl(interactive::Bool, quiet::Bool, banner::Bool, history_file::Bool, color_set::Bool)
      @ Base ./client.jl:379
   [25] exec_options(opts::Base.JLOptions)
      @ Base ./client.jl:309
   [26] _start()
      @ Base ./client.jl:495
ERROR: There was an error during testing
```

**Comment by StevellM** [comment]
The problem comes from computing kernels on GAP at lines 784 and 786. It seems that GAP can't compute the kernel, maybe something to do for the codomain of the maps and their generators
```
julia> codomain(psi1)
Group of isometries of H1 generated by 4 elements

julia> ans.X
GAP: <group of size 1 with 4 generators>

julia> GG.GeneratorsOfGroup(ans)
GAP: [ [  ] -> [  ], [  ] -> [  ], [  ] -> [  ], [  ] -> [  ] ]
```
edit: as far as I see, the codomain of `psi1` is the isometry group of the trivial `TorQuadMod`.

**Comment by StevellM** [comment]
What about, in the `kernel` method, testing first whether the domain/codomain are trivial to handle the obvious cases, and then run the GAP code only in case both are non-trivial ? In this way you will avoid such problems I guess, by returning the entire domain as kernel.

**Comment by simonbrandhorst** [comment]
A workaround might be possible. But I would prefer to fix/understand the underlying problem.

**Comment by StevellM** [comment]
Ok, there is maybe something to look from there: I made it worked by creating its `InverseGeneralMapping` from GAP. I don't know what this function exactly does, but it solved the issue somehow

```
julia> kernel(psi1)
^CERROR: Error thrown by GAP: Error, Error thrown by GAP: Error, InterruptException: in
  act( pnt, g ) at /home/user/.julia/artifacts/80196249c050204d1b65e3b9f8b41878914c2cb0/share/gap/lib/oprt.gi:2096 called from 
Julia.Oscar.permutation( data[1], Julia.Oscar.group_element( data[2], elm ) ) at stream:7 called from
ImageElm( nice, i ) at /home/user/.julia/artifacts/80196249c050204d1b65e3b9f8b41878914c2cb0/share/gap/lib/grpnice.gi:953 called from
func( C[i] ) at /home/user/.julia/artifacts/80196249c050204d1b65e3b9f8b41878914c2cb0/share/gap/lib/coll.gi:663 called from
List( gens, function ( i )
return ImageElm( nice, i );
end ) at /home/user/.julia/artifacts/80196249c050204d1b65e3b9f8b41878914c2cb0/share/gap/lib/grpnice.gi:953 called from
GroupGeneralMappingByImagesNC( G, H, gens, imgs ) at /home/user/.julia/artifacts/80196249c050204d1b65e3b9f8b41878914c2cb0/share/gap/lib/ghom.gi:437 called from
...  at *defin*:0

not in any function at *defin*:0

Stacktrace:
 [1] error(s::String)
   @ Base ./error.jl:33
 [2] ThrowObserver(depth::Int32)
   @ GAP ~/.julia/packages/GAP/2o1Ra/src/GAP.jl:68
 [3] _call_gap_func(func::GAP_jll.GapObj, a1::GAP_jll.GapObj)
   @ GAP ~/.julia/packages/GAP/2o1Ra/src/ccalls.jl:258
 [4] call_gap_func_nokw
   @ ~/.julia/packages/GAP/2o1Ra/src/ccalls.jl:224 [inlined]
 [5] (::GAP_jll.GapObj)(a1::GAP_jll.GapObj)
   @ GAP ~/.julia/packages/GAP/2o1Ra/src/ccalls.jl:235
 [6] kernel(f::GAPGroupHomomorphism{MatrixGroup{fmpq, fmpq_mat}, AutomorphismGroup{Hecke.TorQuadMod}})
   @ Oscar ~/.julia/dev/Oscar/src/Groups/homomorphisms.jl:272
 [7] top-level scope
   @ REPL[53]:1

julia> GG = GAP.Globals
"table of global GAP objects"

julia> GG.InverseGeneralMapping(psi1.map)
GAP: [ IdentityMapping( <pc group of size 1 with 0 generators> ), IdentityMapping( <pc group of size 1 with 0 generators> ), IdentityMapping( <pc group of size 1 with 0 generators> ), IdentityMapping( <pc group of size 1 with 0 generators> ) ] -> [ [ [ -1, 0, 0, 0 ], [ 0, -1, 0, 0 ], [ 0, 0, 1, 0 ], [ 0, 0, 0, 1 ] ], [ [ 1, 1, 0, 0 ], [ 0, -1, 0, 0 ], [ 0, 0, 1, 0 ], [ 0, 0, 0, 1 ] ], [ [ 0, 1, 0, 0 ], [ -1, -1, 0, 0 ], [ 0, 0, 1, 0 ], [ 0, 0, 0, 1 ] ], [ [ 1, 0, 0, 0 ], [ -1, -1, 0, 0 ], [ 0, 0, 1, 0 ], [ 0, 0, 0, 1 ] ] ]

julia> kernel(psi1)
(Matrix group of degree 4 over Rational Field, Group homomorphism from 
Matrix group of degree 4 over Rational Field
to
G1)

julia> ans[1] == G1
true
```
EDIT: it worked once, I can't reproduce it...

**Comment by simonbrandhorst** [comment]
I suppose this is failing because it does not yet load the `shortest_vectors` fix I pushed in Hecke.

**Comment by thofma** [comment]
I released a new version a few minutes ago, which should include the fix. You can bump the version of Hecke in `Oscar/Project.toml` to `0.15.2`.

**Comment by ThomasBreuer** [comment]
First of all, sorry for my late reaction.

I would like to understand the "recursion depth trap" error signaled from GAP which is mentioned in the beginning, but I have not been able to reproduce it with the test example (also with the code just from the first commit). This problem is surely something which must be fixed in the matrix group code.

Concerning the proposed changes, I do not understand some details.
- The idea behind `compute_order` is that for finite matrix groups over the Rationals or over number fields,  `isomorphic_group_over_finite_field` is regarded as better than delegating to GAP. What is the reason to disable this approach in certain situations, by using explicitly created "nice monomorphisms" on the GAP side?
- The function `set_nice_monomorphism` looks dangerous. Its argument `closed` is `true` by default, which means that `G` really acts on `short_vectors`. And why can one set the `IsInjective` flag for the action homomorphism without any condition?

**Comment by simonbrandhorst** [comment]
> I would like to understand the "recursion depth trap" error signaled from GAP which is mentioned in the beginning, but I have not been able to reproduce it with the test example (also with the code just from the first commit). This problem is surely something which must be fixed in the matrix group code.

Setting the `NiceMonomorphism` as injective fixed the recursion trap.
My guess is that for  the kernel computation an inverse mapping is being computed.
But since gap does not know that the map is injective, it tries something which explodes. 
 
> 
> Concerning the proposed changes, I do not understand some details.
> 
>     * The idea behind `compute_order` is that for finite matrix groups over the Rationals or over number fields,  `isomorphic_group_over_finite_field` is regarded as better than delegating to GAP. What is the reason to disable this approach in certain situations, by using explicitly created "nice monomorphisms" on the GAP side?

Hecke computes the orthogonal_group as a subgroup of the symmetric group of the set of 'short enough vectors'.
If this set is not too big, naively, I would expect that this is one of the most efficient representations for the group.
(For the E8 lattice there are 120 shortest vectors, whereas for the Leech lattice there are 196560.)
At least in the examples I tried, computing the order as a permutation group was much faster (I did not try the leech lattice - but I suppose that the Conway group Co_0 is to big anyways... ).

>     * The function `set_nice_monomorphism` looks dangerous. Its argument `closed` is `true` by default, which means that `G` really acts on `short_vectors`. And why can one set the `IsInjective` flag for the action homomorphism without any condition?

There is a natural action on the set of shortest vectors. It is injective if the shortest vectors span the ambient vector space. In the algorithm this is enforced since we consider the sublattice spanned by the shortest vectors. 
Yes, it is certainly dangerous as nothing is checked. So perhaps we should indicate this with a more private underscore?

**Comment by simonbrandhorst** [comment]
with 2c9fe9690329b6ed0926ba7e695ddce05a8e0b4d I still get the recursion depth trap. 
But apparently the definition of N1 was missing. I edited the example.

**Comment by ThomasBreuer** [comment]
Thanks @simonbrandhorst. I tried it again, now I can reproduce the GAP error, but I do not have a fix yet.

**Comment by ThomasBreuer** [comment]
@simonbrandhorst Now I understand the problem with the infinite recursion in GAP, see gap-system/gap/issues/5020.
I think that explicitly setting the injectivity flag is a suitable solution on the Oscar side, but the problem should of course be solved on the GAP side.

**Comment by simonbrandhorst** [comment]
Can we merge this if there are no further comments?

**Comment by ThomasBreuer** [comment]
@simonbrandhorst Let us go back to my earlier comment and your reply to it.

My interpretation of the change in `compute_order` is as follows.

- For a matrix group `G` over the Rationals or over a number field, the GAP group `G.X` does usually not store the flag `IsHandledByNiceMonomorphism`.
- If we know a reasonable ("nice") faithful permutation action of `G` in advance, we can set this flag in `G.X` to `true` and store the action homomorphism in `G.X`, and then this information should be used in the computation of the order.
- If the flag is not known to be `true` then the Oscar code from `isomorphic_group_over_finite_field` shall be preferred.

The problem with the current code is that the call `GAP.Globals.IsHandledByNiceMonomorphism(G.X)` does not just check the value of the flag but starts a computation if the value of the flag is not yet stored.
GAP's viewpoint is that the flag can be set to `true` when the matrix group is finite (no matter how large an automatically computed faithful permutation representation will be), thus the call `GAP.Globals.IsHandledByNiceMonomorphism(G.X)` causes the computation `GAP.Globals.IsFinite(G.X)`.
If the above interpretation is correct then it is better to ask whether the flag is already set and has the value `true`, by calling `GAP.Globals.HasIsHandledByNiceMonomorphism(G.X) and GAP.Globals.IsHandledByNiceMonomorphism(G.X)`; this call will not start a computation of the value of the flag.
A comment line about the idea behind the code of `compute_order` would be appropriate.

Concerning the function `set_nice_monomorphism`, I think the name is too general; the function assumes that its first argument `G` acts faithfully on the second argument `short_vectors` via the action `on_fmpz_mat`.
I suggest to add a comment line about this, and to prefix the name with an underscore (as you had already mentioned).

**Comment by ThomasBreuer** [comment]
@simonbrandhorst Thanks. I have no further comments now.

**Pull request merged**
