### PR TITLE
Adv/serialize power series

### PR DESCRIPTION
**Pull request by antonydellavecchia**
Serialize functionality for power series and laurent series

### CODE REVIEW

**Comment by tthsqe12** [comment]
Where is the supposed bug in AA's powers series?

**Comment by antonydellavecchia** [comment]
> Where is the supposed bug in AA's powers series?

good point, i forgot to open an issue. this is it

```
julia> p = rel_z^2 + 6
z^2 + O(z^10)

julia> pol_length(p)
1

julia> coeffs = map(x -> coeff(p, x), 0:pol_length(p))
2-element Vector{nmod}:
 0
 0

julia> parent(p)
Univariate power series ring in z over Integers modulo 6


```

**Comment by tthsqe12** [comment]
Hold on, I am not sure this is a bug. @thofma

**Comment by antonydellavecchia** [comment]
> Hold on, I am not sure this is a bug. @thofma

ahh, so i should be starting from the valutation, when it's a relative series, sorry for confusing, i didn t have a test on rel series without a non zero constant term, i will add one now

**Comment by thofma** [comment]
Yes, I think you are right and the docstring `?pol_length` is wrong/confusing.

**Comment by tthsqe12** [comment]
The documentation on pol_length is pretty scanty, and the whole thing seems to be a implementation detail.
Unfortunately, from the abstract interface in https://nemocas.github.io/AbstractAlgebra.jl/dev/series_interface/
I am not sure how one would serialize power series.

**Comment by thofma** [comment]
It says
```
  pol_length(a::RelSeriesElem)

  Return the length of the polynomial underlying the given power series. This
  will be zero if the power series has no nonzero terms.
```
which seems to be wrong?

**Comment by tthsqe12** [comment]
The problem is "the polynomial underlying the given power series" is undefined.

**Comment by antonydellavecchia** [comment]
> It says
> 
> ```
>   pol_length(a::RelSeriesElem)
> 
>   Return the length of the polynomial underlying the given power series. This
>   will be zero if the power series has no nonzero terms.
> ```
> 
> which seems to be wrong?

no I think this is okay since the length is taken w.r.t. the valuation, so x^2 + O(x^3) would have length 1 with valuation 2, well i guess it's wrong since it doesn't include the statement about the valuation

**Review by fingolfin — APPROVED** [review]

**Pull request merged**
