### PR TITLE
Booktests: try running vinberg3 in CI

### PR DESCRIPTION
**Pull request by benlorenz**
Lets see how long it takes there and whether it succeeds, ref #3881, cc @simonbrandhorst.

### CODE REVIEW

**Comment by benlorenz** [comment]
It did indeed fail:
```julia
  julia> [representative(elliptic_parameter(Y2, f)) for f in fibers_in_Y2[4:6]]
- 3-element Vector{AbstractAlgebra.Generic.FracFieldElem{QQMPolyRingElem}}:
-  (y//z)//((x//z)*t)
-  ((y//z) + t^3)//((x//z)*t - t^4)
-  ((y//z) + t^3)//((x//z) - t^3)
+ ERROR: AssertionError: found
+ Stacktrace:
+  [1] horizontal_decomposition(X::EllipticSurface{QQField, AbstractAlgebra.Generic.FracFieldElem{…}}, F::Vector{QQFieldElem})
+    @ Oscar ~/work/Oscar.jl/Oscar.jl/experimental/Schemes/src/elliptic_surface.jl:1349
+  [2] elliptic_parameter(X::EllipticSurface{QQField, AbstractAlgebra.Generic.FracFieldElem{QQPolyRingElem}}, F::Vector{QQFieldElem})
+    @ Oscar ~/work/Oscar.jl/Oscar.jl/experimental/Schemes/src/elliptic_surface.jl:1419
+  [3] (::var\"#23#24\")(f::Vector{QQFieldElem})
+    @ Main.__255 ./none:0
+  [4] iterate
+    @ ./generator.jl:47 [inlined]
+  [5] collect(itr::Base.Generator{Vector{Vector{QQFieldElem}}, var\"#23#24\"})
+    @ Base ./array.jl:834
+  [6] top-level scope
+    @ REPL[48]:1
+ Some type information was truncated. Use `show(err)` to see complete types.
```

And it added about 13 minutes to the booktest job. I guess we could afford this since it still finished before a bunch of other jobs in the same run but it is still quite a lot.

**Comment by simonbrandhorst** [comment]
Thanks for the effort! I agree that 13 minutes is (too?) long for a regular test on every PR. Is there a way to run it once for every release?

**Comment by simonbrandhorst** [comment]
In the sense that we have,
tests, long tests, very long tests (but only very few ones)

**Comment by simonbrandhorst** [comment]
Seems like we can speed up things by a factor of  50 ... so we will not need very long tests. Best wait before taking any further steps.

**Comment by simonbrandhorst** [comment]
Since there will be no fix in the near future, I close it. Thanks @benlorenz  for bringing this up.

**Pull request closed without merging**
