### PR TITLE
Sl poly not m poly

### PR DESCRIPTION
**Pull request by fieker**
may/ should also resolve the (to me invisible) problem of Giovanni on ambigous signature for ^:SLPoly, Perm

### CODE REVIEW

**Comment by rfourquet** [comment]
I understand the explanation from the commit message, but I'm curious: does this change solve a concrete problem? (if this solves "Giovanni's problem", it could be added as a test).

**Comment by thofma** [comment]
It turned out that Giovannis problem was unrelated, but it revealed that `SPoly` does not satisfy the `MPoly` interface, so generic algorithms for `MPoly` were not working with `SPoly`.

**Comment by fieker** [comment]
On Sun, Feb 07, 2021 at 02:35:46AM -0800, Rafael Fourquet wrote:
> I understand the explanation from the commit message, but I'm curious: does this change solve a concrete problem? (if this solves "Giovanni's problem", it could be added as a test).
> 
It would have solved Giovanni's problem as well as it would have removed
the ambiguity, however Tommy solved this differently.

But slpoly's are NOT MPoly's as they satisfy only a tiny bit of the
interface, out of neccessity. Calling them a ring is already stretching
it, but that is neccessary for functioning. Consider
 - iterate over coeffs/ terms/ monomials
 - derivative
 - hash/ iszero/ isequal

The clash came over f^p where p is a permutation. This also  illustrated
the problem
 - for SLPoly this is done by evaluating at the array of permuted
   variables
 - for MPoly we permute the exponent vectors directly and sort the
   polynomial.
While the 1st apparoach would work in the second case, it would be
terribly inefficient....

**Comment by rfourquet** [comment]
Thanks. `SLPoly` didn't indeed satisfy the `MPoly` interface, so there was a false promise and some algorithms didn't work on it; but on the other hand, I was wondering whether some (implemented) algorithms would still work on `SLPoly` provided they were `<: MPolyElem`.

**Comment by fieker** [comment]
You're right, eg printing worked using the mpoly show and possible others.
This is why I still like them to be rings, even though they don't satisfy
the ring interface...

**Pull request merged**
