### PR TITLE
Update to latest AA/Nemo/Hecke/Singular

### LINKED ISSUE #1328: `WARNING: could not import Hecke.homology into Oscar`
`WARNING: could not import Hecke.homology into Oscar` shows up when precompiling Oscar...

Why? And how to fix it?

### PR DESCRIPTION
**Pull request by fingolfin**
A separate PR will adjust for the `isFOO` to `is_FOO` renaming, but this might impact other open PRs, so I am not sure how best we want to handle that... but we should update to the latest version of these deps ASAP. So here we go.

Resolves #1328

### CODE REVIEW

**Comment by tthsqe12** [comment]
Seems to be a field of a struct named with is* that appears in the test code as well

**Comment by fingolfin** [comment]
Yeah, there are several of these, already fixed some. That's what happens when you access structs directly instead of via accessors (resp. if one does not provide said accessors and thus forces people to access struct fields directly)

**Comment by fingolfin** [comment]
I wonder what causes the doc failure is? Anyone got an idea? @thofma ?

**Comment by thofma** [comment]
Did we change something?

**Comment by thofma** [comment]
Did we change something?

**Comment by fingolfin** [comment]
I don't think so. But perhaps something in this PR causes a breakage in a way I don't understand. But I just tried `Oscar.build_doc()` in Julia 1.6 with this branch, and it works locally.

I'll restart the job. Also, I just merged PR #1330, and will look out for master's doc CI job passing/failing.

**Comment by fingolfin** [comment]
The documentation errors are caused by the upgrade to the new Hecke version: the problem is that Hecke now also uses DocumenterCitation, and also uses some of the same bib entries. And this confuses Documenter resp. DocumenterCitations.

Not sure how to best deal with this... some ideas:
1. patch `DocumenterCitations` so that it does not treat these as duplicates if the duplicate bib entries are identical, and in that case, point to any one of them, e.g. always the first, or the one with the shortest path (requires an `DocumenterCitations` update )
2. remove Hecke's `reference.md` file when building the Oscar manual (this assumes all of Hecke's bib items are also in the OScar bib file
3. ... ?

**Comment by fingolfin** [comment]
I've now pushed a commit trying out option 2. We'll see how that works out.

**Comment by thofma** [comment]
Thanks for the fix, it seems to work.

**Pull request merged**
