### PR TITLE
Add option to allow unicode output

### LINKED ISSUE #318: Add build option for ASCII/non-ASCII chars
In the following discussion we decided that Nemo/AbstractAlgebra will ban use of non-ASCII characters:

https://github.com/Nemocas/Nemo.jl/issues/1013

During that discussion @kalmark had the recollection that we decided we were going to add a global switch to allow/disallow non-ASCII chars for Oscar and dependencies. This would fix the issue for users, though I believe it will not fix the issue for developers reading code (e.g. from old versions of Windows console) containing such chars, depending how it is implemented.

Therefore a decision needs to be made if:

1) The no-ASCII ban will hold across all Oscar repos; or
2) We implement a global switch

### PR DESCRIPTION
**Pull request by thofma**
Closes #318 

This PR adds two functions
```julia
allow_unicode(::Bool) # exported, for the user
Oscar.is_unicode_allowed() # not exported, for the developer
```
which do the obvious thing. The preference is stored persistently and thus will be remembered across different julia sessions. I have added a "Unicode" section to the developer style guide with an example on how to use it.

There are a few more things to discuss
- [ ] Are the names fine? I personally have no preferences. Maybe `allow_unicode!` with a bang since it mutates some global state?
- [ ] What should the return value of `allow_unicode(..)` be? At the moment it returns the previous state, which is sometimes quite handy when trying to recover the old state (although this should never be done in library code). I am happy to make it return `nothing` or whatever you find helpful.
- [ ] Where to put it in the user documentation?

CC: @fieker @fingolfin @tthsqe12 @micjoswig

### CODE REVIEW

**Comment by micjoswig** [comment]
Thanks for the draft.  While I still like this idea, someone (@benlorenz ?) pointed out that each Julia matrix has a unicode cross symbol in its output.  Is this a problem?

**Comment by thofma** [comment]
Don't know about a cross, but there are some vertical Unicode dots when printing vectors which are too long for the terminal. Let me illustrate how this looks for me when working remotely on some compute server:
```julia
julia> [i for i in 1:100]
100-element Vector{Int64}:
   1
   2
   3
   4
   5
   �
  96
  97
  98
  99
 100
```
Of course julia prints other Unicode characters in various situations:
```julia
(v1.6) pkg> add Polymake
   Resolving package versions...
   Installed lib4ti2_jll ����������� v1.6.10+0
   Installed normaliz_jll ���������� v300.900.100+0
   Installed MongoC_jll ������������ v1.19.1+0
   Installed cddlib_jll ������������ v0.94.13+0
   Installed Mongoc ���������������� v0.6.2
   Installed Parsers ��������������� v2.2.1
   Installed Preferences ����������� v1.2.3
   Installed Polymake �������������� v0.7.0
   Installed polymake_jll ���������� v400.600.0+0
   Installed CxxWrap ��������������� v0.12.0
   Installed libcxxwrap_julia_jll �� v0.9.0+0
   Installed Perl_jll �������������� v5.34.0+1
   Installed PPL_jll ��������������� v1.2.1+0
   Installed GLPK_jll �������������� v5.0.1+0
   Installed MacroTools ������������ v0.5.9
   Installed JSON ������������������ v0.21.2
   Installed Ncurses_jll ����������� v6.2.0+0
   Installed Scratch ��������������� v1.1.0
   Installed bliss_jll ������������� v0.77.0+1
   Installed libpolymake_julia_jll � v0.7.0+0
   Installed TOPCOM_jll ������������ v0.17.8+0
   Installed Zstd_jll �������������� v1.5.0+0
   Installed Ninja_jll ������������� v1.10.3+0
   Installed OpenSSL_jll ����������� v1.1.13+0
   Installed LZO_jll ��������������� v2.10.1+0
   Installed snappy_jll ������������ v1.1.9+0
   Installed FLINT_jll ������������� v200.800.401+1
   Installed Readline_jll ���������� v8.1.1+1
   Installed lrslib_jll ������������ v0.3.3+0
   Installed OpenBLAS32_jll �������� v0.3.12+1
   Installed nauty_jll ������������� v2.6.13+0
   Installed JLLWrappers ����������� v1.4.1
   Installed BinaryWrappers �������� v0.1.2
   Installed boost_jll ������������� v1.76.0+0
```

**Comment by fingolfin** [comment]
@thofma whoa. Is this with your Mac when logging into a Linux server, or what? It renders fine for me in this combo

**Comment by thofma** [comment]
Yes, something like that.

**Comment by joschmitt** [comment]
Feel free to ignore this, but regarding your second point: I would find it somewhat confusing as a user, if I call `allow_unicode(true)` for it to (potentially) return `false`. It just feels like something went wrong.

**Comment by thofma** [comment]
I will add the documentation for the user and then this is good to go. I will keep the name and maybe change the behaviour.

**Comment by fieker** [comment]
Merge?

**Pull request merged**
