### PR TITLE
README.md: update citation info once more

### PR DESCRIPTION
**Pull request by fingolfin**
... with info we just got from the publisher

### CODE REVIEW

**Comment by joschmitt** [comment]
There is also this `CITATION.CFF` file which produces its own bibtex entry. I have a commit https://github.com/joschmitt/Oscar.jl/commit/9ad1f982ed020ef49c06c113b1d67fc12d6ef310 that updates that, but there is no field `series` so I put the series name into `collection-title`. In the automatically produced bibtex, the series name is not shown (as you can see if you click "Cite this repository" on the `js/cite` branch of my fork). So I am not sure whether this (i.e. two different bibtex blocks) is what we want.

**Comment by fingolfin** [comment]
Thanks I'll update the CFF. If CFF does not support features like series, I don't think that should block us from using the correct bibtex.

**Comment by fingolfin** [comment]
See https://github.com/citation-file-format/citation-file-format/issues/394

**Comment by fingolfin** [comment]
Update the CFF file (and also the exact text in the README.md). I decided against using `collection-title` in the CFF as it has different semantics.

**Review by joschmitt — APPROVED** [review]

**Comment by fingolfin** [comment]
Thanks for carefully checking this, @joschmitt . I hope I'll remember the CFF file next time, but in the meantime I am very grateful you are paying close attention :-)

**Pull request merged**
