### PR TITLE
Some more fixes for the fibration hopping.

### PR DESCRIPTION
**Pull request by HechtiDerLachs**
ping @simonbrandhorst

### CODE REVIEW

**Comment by HechtiDerLachs** [comment]
Am I responsible for the failing book tests, or is this a hickup?

**Comment by benlorenz** [comment]
> Am I responsible for the failing book tests, or is this a hickup?

I think that is https://github.com/oscar-system/Oscar.jl/issues/3633 and should disappear after re-running.

**Review by afkafkafk13 — COMMENTED** [review]
All fixes look sensible. Ping me, when everything is in, and I will have a look at it. Current state is a clear approve.

**Comment by HechtiDerLachs** [comment]
I think, it would be great if this could also be merged and backported. The extended version of the notebook which I just uploaded now runs reliably within roughly 30 minutes on this branch. Maybe the `Manifest.toml` and the `Project.toml` in the notebook folder has to be updated after this is merged.

**Review by afkafkafk13 — APPROVED** [review]

**Pull request merged**
