### PR TITLE
add absolute_primary_decomposition over QQ

### PR DESCRIPTION
**Pull request by tthsqe12**
@wdecker

### CODE REVIEW

**Comment by thofma** [comment]
Was there a decision to not do a proper field extension but the "additional variable" hack?

**Comment by tthsqe12** [comment]
What? We decided to do the proper field extension...

**Comment by thofma** [comment]
I misread a comment in the source code code. Ignore my remark.

**Comment by thofma** [comment]
I misread a comment in the source code code. Ignore my remark.

**Comment by wdecker** [comment]
@tthsqe12: Thanks!

**Pull request merged**
