### PR TITLE
added symmetrizations of group characters

### PR DESCRIPTION
**Pull request by ThomasBreuer**
(Some of the functions are needed by @StevellM.)

### CODE REVIEW

**Comment by StevellM** [comment]
Great, thanks! I guess the tests are not passing due to a comparison problem between `Integer` and `QQAbElem` (which is the type of the entries in the character table)... I guess a solution could be to use `data` on the `QQAbElem` which returns a `nf_elem`.

I would like to suggest something though: with these functions, when working with GAP initially, there is the necessity to provide a list of characters. Would it be possible to have these functions available also if one just enters a single character ? I don't know the general use, but I am used to take the `symmetric_parts` of one character at a time and it is a bit inconvenient to have to put it in a list and then extract the result from the list given in output.

**Comment by thofma** [comment]
The error is
```
  Expression: [(exterior_power(chi, 3))[1] for chi = t] == [0, 0, 10, 10, 10, 10, 560, 84, 84, 120, 120]
   Evaluated: QQAbElem{nf_elem}[0, 0, 20, 4, 4, 10, 10] == [0, 0, 10, 10, 10, 10, 560, 84, 84, 120, 120]
```
These seem to be different, independent of the type.

**Comment by StevellM** [comment]
Yes indeed, and I didn't realize that `exterior_power` and `symmetric_power` were doing exactly what I suggested.. well my comment can be ignored then!

**Review by fingolfin — APPROVED** [review]
Thanks, seems fine in principle to me, but of course as other observed the tests need to be fixed :-)

**Pull request merged**
