### PR TITLE
Renaming of some monomial orderings

### PR DESCRIPTION
**Pull request by ederc**
This PR was initiated by #2950.

1. Renames `revlex` to `invlex` and `negrevlex` to `neginvlex`.
2. Introduces the monomial ordering `deginvlex`.
3. Keeps (until next breaking release) `revlex` and `negrevlex` available for compatibility.

### CODE REVIEW

**Comment by thofma** [comment]
Maybe we can add a proper deprecation if we plan to deprecate`revlex` and `negrevlex`?

**Comment by lgoettgens** [comment]
https://github.com/oscar-system/Singular.jl/pull/722 is not available in Singular.jl v0.19.0. I think you first need to make a new breaking Singular.jl release.

**Comment by ederc** [comment]
> Maybe we can add a proper deprecation if we plan to deprecate`revlex` and `negrevlex`?

Yes. How shall I do this?

**Comment by ederc** [comment]
> [oscar-system/Singular.jl#722](https://github.com/oscar-system/Singular.jl/pull/722) is not available in Singular.jl v0.19.0. I think you first need to make a new breaking Singular.jl release.

Argh, my bad, sorry.

**Comment by thofma** [comment]
Add it to https://github.com/oscar-system/Oscar.jl/blob/master/src/deprecations.jl

**Pull request closed without merging**
