### PR TITLE
Two neighbor cleanup

### PR DESCRIPTION
**Pull request by HechtiDerLachs**
CC: @simonbrandhorst

### CODE REVIEW

**Comment by simonbrandhorst** [comment]
Thanks for doing this! Looks good to me once the tests pass.

**Review by simonbrandhorst — APPROVED** [review]

**Comment by HechtiDerLachs** [comment]
Note that now the `weierstrass_chart` of an `EllipticSurface` `X` does not live on the `weierstrass_model`, but on the `relatively_minimal_model` -- which is nothing but `X` itself by now. This second thing is the main inconsistency which has been removed here: We already returned the `relatively_minimal_model` as the `underlying_scheme` of `X`, but didn't use `X` as the `domain` of the blowdown morphism. This has been corrected. However, we might want to reconsider whether a getter like `relatively_minimal_model` is then still suitable. I think what we really need there is something like  `projection_to_weierstrass_model`.

**Comment by HechtiDerLachs** [comment]
Ready for merge from my side.

**Comment by simonbrandhorst** [comment]
Yea, I have pondered about this myself too. I agree that `projection_to_weierstrass_model` is probably better.

**Pull request merged**
