### PR TITLE
Speed up evaluation of maps of `MPolyRing`s which take variables to variables 

### PR DESCRIPTION
**Pull request by HechtiDerLachs**
Some more steps towards addressing #4112 . ~Still WIP but seemingly a speedup of factor 10 already. Timings will follow.~ I think, this is what I can do for the moment.

### CODE REVIEW

**Comment by HechtiDerLachs** [comment]
**Timings:** Again, I am using [this polynomial](https://github.com/user-attachments/files/18123872/poly.txt) as a benchmark.

before:
```julia
julia> f = load("/path/to/poly.txt");

julia> g = copy(f);

julia> S = parent(f);

julia> Oscar.flatten(S);

julia> @time Oscar.flatten(S)(g);
  0.227188 seconds (1.05 M allocations: 46.635 MiB, 53.65% gc time)

julia> g = copy(f);

julia> @time Oscar.flatten(S)(g);
  0.099856 seconds (1.00 M allocations: 46.005 MiB)

julia> g = copy(f);

julia> @time Oscar.flatten(S)(g);
  0.112565 seconds (1.40 M allocations: 57.970 MiB)

julia> g = copy(f);

julia> @time Oscar.flatten(S)(g);
  0.244818 seconds (1.39 M allocations: 56.852 MiB, 46.52% gc time)
```
after:
```julia
julia> f = load("/path/to/poly.txt");

julia> g = copy(f);

julia> S = parent(f);

julia> Oscar.flatten(S);

julia> @time Oscar.flatten(S)(g);
  0.054546 seconds (578.67 k allocations: 27.150 MiB)

julia> g = copy(f);

julia> @time Oscar.flatten(S)(g);
  0.061309 seconds (578.67 k allocations: 27.150 MiB)

julia> g = copy(f);

julia> @time Oscar.flatten(S)(g);
  0.039068 seconds (428.25 k allocations: 20.028 MiB)
```
So roughly a factor 2 in improvement for the special cases covered compared to current master.

**Comment by thofma** [comment]
Are you caching the image of elements by default? Or why is the `copy` necessary in the benchmark?

**Comment by HechtiDerLachs** [comment]
It used to be caching by default. I turned it off here, because I realized that this might lead to bugs with in-place operations. The `copy` could therefore be skipped in these tests, really.

**Comment by HechtiDerLachs** [comment]
On a first glance it seems to me that none of the failing tests is really my fault. Correct me if I'm wrong! 

Otherwise this should be good to go.

**Comment by HechtiDerLachs** [comment]
Picking up on the timings by @fingolfin on #4112 done for the tests of the `EllipticSurface`s:

current master: `310.391684 seconds (2.06 G allocations: 72.914 GiB, 12.26% gc time, 0.12% compilation time)`
~with this PR: `310.526301 seconds (2.08 G allocations: 73.502 GiB, 12.21% gc time, 0.24% compilation time)`~
(edit/update) with this PR: `303.933921 seconds (2.05 G allocations: 72.303 GiB, 11.67% gc time)`

So either the expensive tasks lay elsewhere, or the improvements here just don't pay off as much as anticipated. Both are not unlikely, the first because flattening of rings only plays a role in the computation of gluings which is not the main objective of the algorithms tested there. For the second: We do not have more fine-tuned methods for polynomial- and quotient rings over localizations (yet). These come up naturally in the gluings as we usually glue over principal open subsets. I left a comment in the source code to indicate this as a potential thread for future work. But as this is not a super urgent matter right now, I would prefer to spend my resources differently for the moment.

**Comment by jankoboehm** [comment]
> Picking up on the timings by @fingolfin on #4112 done for the tests of the `EllipticSurface`s:
> 
> current master: `310.391684 seconds (2.06 G allocations: 72.914 GiB, 12.26% gc time, 0.12% compilation time)` with this PR: `310.526301 seconds (2.08 G allocations: 73.502 GiB, 12.21% gc time, 0.24% compilation time)`
> 
> So either the expensive tasks lay elsewhere, or the improvements here just don't pay off as much as anticipated. Both are not unlikely, the first because flattening of rings only plays a role in the computation of gluings which is not the main objective of the algorithms tested there. For the second: We do not have more fine-tuned methods for polynomial- and quotient rings over localizations (yet). These come up naturally in the gluings as we usually glue over principal open subsets. I left a comment in the source code to indicate this as a potential thread for future work. But as this is not a super urgent matter right now, I would prefer to spend my resources differently for the moment.

Agree there, crucial algorithmic problems are elsewhere.

**Comment by lgoettgens** [comment]
The `nightly, book` failure is due to https://github.com/oscar-system/Oscar.jl/issues/4402, so can be disregarded here.

**Review by simonbrandhorst — APPROVED** [review]
Looks good to me. Thanks for tuning the code.

**Pull request merged**
