### PR TITLE
polyhedral: g- and h-vectors

### PR DESCRIPTION
**Pull request by micjoswig**
This is a draft for implementing toric g- and h-vectors (via polymake).

* doctests fail, but I don't understand why
* also rearranged doc of auxiliary functions slightly, by adding subcategories
* `upper_bound_theorem` was not fully functional; now split into three functions, for f-, g- and h-vectors

### CODE REVIEW

**Review by lkastner — APPROVED** [review]

**Comment by lkastner** [comment]
So the `f_vector`, `g_vector`, and `h_vector` fail on the `upper_bound_theorem` polyhedron, because it cannot be determined whether it is bounded. Benjamin suggested introducing a function `isembedded(Polyhedron)` for such cases. Then we could use this to make the other functions work. What do you think?

**Comment by micjoswig** [comment]
> So the `f_vector`, `g_vector`, and `h_vector` fail on the `upper_bound_theorem` polyhedron, because it cannot be determined whether it is bounded. Benjamin suggested introducing a function `isembedded(Polyhedron)` for such cases. Then we could use this to make the other functions work. What do you think?

I thought about this.  This would mean to carry over the polymake semantics.  However, we agreed on making OSCAR simple to use, also for nonexperts. And I have 20 years of experience of explaining to polymake users how the combinatorial polytopes work.  My impression is that this does not scale with the growth that OSCAR wants to achieve.  So, for OSCAR, it is better to take things literally. A polytope is a polytope is a polytope, and not an infinite set of combinatorially equivalent polytopes.

So, in my opinion `isembedded()` should die.  There is nothing wrong with using such tricks internally, but this should not be exposed to the user.

**Comment by micjoswig** [comment]
If I may add: thinking about (polytopes in) OSCAR in a different way than (polytopes in) polymake may be tedious sometimes.  But it also allows us to reflect design decisions that we made in the past. Forcing us to become a bit schizophrenic, will make both projects better, in the end.

**Comment by micjoswig** [comment]
@lkastner : can you tell me what goes wrong with my doc tests?  I tried to understand the error messages, but it did not help me.

**Comment by lkastner** [comment]
> @lkastner : can you tell me what goes wrong with my doc tests? I tried to understand the error messages, but it did not help me.

I am currently trying this out locally.

**Comment by lkastner** [comment]
@micjoswig So locally it works if there is no comment above `f_vector`. Probably one can also document with comments, so the documenter package gets confused if there is a comment that doesn't document and just ignores the actual documentation.

I pushed the fixes.

**Review by lkastner — APPROVED** [review]

**Review by tbrysiewicz — COMMENTED** [review]
Looks good to me. I like how the upper bound situation was handled.
I approve this, but the button "approve" is not appearing for me.

**Pull request merged**
