### PR TITLE
use the "new", sparse free_module only for MPoly

### PR DESCRIPTION
**Pull request by fieker**
if activated by default, it fails a lot of code due do the new
modules not implementing the entire ModuleFP and ModuleFP hom stuff -
and using different abstract types.

It fails in the Group-Cohomology...

### CODE REVIEW

**Comment by fieker** [comment]
Otherwise, e.g.:
```
ERROR: MethodError: no method matching singular_ring(::QabField; keep_ordering=false)
Closest candidates are:
  singular_ring(::QabField) at ~/.julia/dev/Oscar/src/Rings/AbelianClosure.jl:239 got unsupported keyword argument "keep_ordering"
  singular_ring(::AbstractAlgebra.Ring) at ~/.julia/dev/Oscar/src/Rings/mpoly.jl:717 got unsupported keyword argument "keep_ordering"
  singular_ring(::Union{Nemo.FmpzModRing, Nemo.NmodRing}) at ~/.julia/dev/Oscar/src/Rings/mpoly.jl:580 got unsupported keyword argument "keep_ordering"
  ...
Stacktrace:
  [1] singular_module(F::FreeMod{QabElem})
    @ Oscar ~/.julia/dev/Oscar/src/Modules/UngradedModules.jl:700
  [2] Oscar.ModuleGens(O::Vector{FreeModElem{QabElem}})
    @ Oscar ~/.julia/dev/Oscar/src/Modules/UngradedModules.jl:555
  [3] kernel(h::FreeModuleHom{FreeMod{QabElem}, FreeMod{QabElem}})
    @ Oscar ~/.julia/dev/Oscar/src/Modules/UngradedModules.jl:2980
  [4] isinjective(f::FreeModuleHom{FreeMod{QabElem}, FreeMod{QabElem}})
    @ Oscar ~/.julia/dev/Oscar/src/Modules/UngradedModules.jl:4325
  [5] isbijective
    @ ~/.julia/dev/Oscar/src/Modules/UngradedModules.jl:4345 [inlined]
  [6] inv(H::FreeModuleHom{FreeMod{QabElem}, FreeMod{QabElem}})
    @ Oscar ~/.julia/dev/Oscar/src/Modules/UngradedModules.jl:3287
```

**Comment by thofma** [comment]
You need to adjust the `@docs` block in src/CommutativeAlgebra/free_modules.md:38-40.

**Comment by wdecker** [comment]
There is more to be adjusted here. I will discuss this tomorrow with @fieker

**Comment by fingolfin** [comment]
Also CC @jankoboehm @AlexD97

**Pull request merged**
