### PR TITLE
Update TagBot integration

### PR DESCRIPTION
**Pull request by fingolfin**

### CODE REVIEW

**Comment by thofma** [comment]
Will this fix the missing release that we have now? (after retriggering)

**Comment by fingolfin** [comment]
Dunno, but this is what the TagBot repo recommends now and it was added in order to fix some issues with generating tags... Plus it makes it possible to use the `workflow_dispatch` with a configurable "lookback" so that we can re-run it for older commits, such as the 0.12.0 release commit...

Seee https://github.com/JuliaRegistries/TagBot/pull/236 which fixed https://github.com/JuliaRegistries/TagBot/issues/222 and https://github.com/JuliaRegistries/TagBot/issues/229

**Comment by fingolfin** [comment]
So perhaps we just merge this now (running the CI is pointless) and then try and see we'll see if it helps by triggering tagbot manually?

**Comment by thofma** [comment]
https://github.com/oscar-system/Oscar.jl/actions/runs/4700190747

**Comment by thofma** [comment]
Does not seem to work at all (https://github.com/oscar-system/Oscar.jl/actions/runs/4700190747/jobs/8334742285). The error is also different to the reported issues I think. Maybe it does not like retriggering.

**Comment by fingolfin** [comment]
The error there is actually helpful:
```
github.GithubException.RateLimitExceededException: 403 {"message": "API rate limit exceeded for installation ID 6710914.", "documentation_url": "https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting"}
```
That doesn't sound like retrying will help. Maybe we just have to wait a bit?

**Pull request merged**
