### PR TITLE
More consistent spelling for OSCAR

### PR DESCRIPTION
**Pull request by fingolfin**
We at some point agreed the canonical spelling is `OSCAR` because it is
an abbreviation. Then again, the package is named `Oscar`, which leads to
some annoying places where we must write the latter, not the former, and
some where it is not crystal clear.

So perhaps we should rename the package to `OSCAR` -- or perhaps consider
changing the standard spelling to `Oscar` instead?

### CODE REVIEW

**Comment by thofma** [comment]
I think both solutions are fine.

**Comment by wdecker** [comment]
I prefer OSCAR.

Von meinem iPhone gesendet

**Comment by fingolfin** [comment]
Assuming @fieker or @micjoswig have no other strong opinion, let's just merge this as-is then? At least we are less inconsistent this way, and we can always change it in the other direction if we wanted to

**Comment by micjoswig** [comment]
> I prefer OSCAR.

I agree with Wolfram.

**Pull request merged**
