### PR TITLE
ToricVarieties: More on toric morphisms

### PR DESCRIPTION
**Pull request by HereAround**
* This PR allows to compute the maps between class groups and Picard groups as induced by a toric morphism.
[This requires to compute a `preinverse` and `postinverse` for maps of type `GrpAbFinGenMap`, which have been added in Hecke (thank you @thofma).]
* It also includes a bugfix. A constructor of a rational equivalence classes called `istrivial(d)` for `d` a toric divisor. Following the general `OSCAR`-convention, this was changed to `is_trivial` a while back.

### CODE REVIEW

**Comment by thofma** [comment]
If you bump to Hecke 0.16.5, you can use `preinverse`.

**Comment by HereAround** [comment]
> If you bump to Hecke 0.16.5, you can use `preinverse`.

Done.

**Comment by HereAround** [comment]
I do not understand the failures here. They seem to originate from tropical geometry. @lkastner any ideas?

**Comment by thofma** [comment]
https://github.com/oscar-system/Oscar.jl/issues/1675

@tthsqe12 did you disable all them of them?

**Comment by benlorenz** [comment]
This seems to have started with the latest Singular_jll update, the most recent [tests on master also failed](https://github.com/oscar-system/Oscar.jl/actions/runs/3600345293).
Downgrading Singular_jll does help:
```
Singular_jll v403.101.500+0 ⇒ v403.101.400+0
...
julia> include("test/TropicalGeometry/runtests.jl")
Test Summary:  | Pass  Broken  Total  Time
groebner_basis |    4       2      6  9.8s
Test Summary: | Pass  Broken  Total  Time
initial       |    4       1      5  2.6s
```
There are some "broken" tests, but using `@test_broken` only works for tests that already fail. Otherwise `@test_skip` might work.

**Comment by thofma** [comment]
That's bad. Unfortunately we do not test Oscar.jl with new Singular_jll releases.

**Comment by thofma** [comment]
#1784

**Review by lkastner — APPROVED** [review]

**Comment by HereAround** [comment]
Thank you @thofma for fixing the broken tests. Now all checks (including the nightly builds) pass. :+1: 

Thank you @lkastner for approving. I thus rebase and merge.

**Pull request merged**
