### PR TITLE
Rename function to obtain underlying abelian group

### PR DESCRIPTION
**Pull request by thofma**
I picked `grading` as the name to obtain the underlying abelian group of a filtrated/graded ring. I have no preference. I just picked one name to get the discussion started.

CC: @wdecker @fieker @8d1h

### CODE REVIEW

**Comment by thofma** [comment]
Oh, this already has a name. It is called `decoration(R)`. This begs the question, should we change it? At least it needs to be documented.

**Comment by wdecker** [comment]
A grading is more than just the group, the same group may define many different gradings.

**Comment by thofma** [comment]
Does this mean we are happy with `decoration`?

**Comment by wdecker** [comment]
I will think about this and other questions

**Comment by fieker** [comment]
On Tue, Jul 06, 2021 at 09:13:35AM -0700, Wolfram Decker wrote:
> A grading is more than just the group, the same group may define many different gradings.
> 
To creating a grading you have to also pass in a comparison function for
the group. This should also probably be retrievable, legally.

**Comment by thofma** [comment]
`grading_group` it shall be. Once this is merged here, someone can add a docstring.

**Pull request merged**
