### PR TITLE
bump singular to 0.10

### PR DESCRIPTION
**Pull request by tthsqe12**

### CODE REVIEW

**Comment by thofma** [comment]
Somehow
```julia
  cfRead missing
  cfSetMap missing
```
is present in the output, which was not there before.

**Comment by tthsqe12** [comment]
Ok, maybe next time.

**Comment by hannes14** [comment]
https://github.com/Singular/Singular/commit/a83b1f3a4d076d51e7ce1da40c8cffdfbb0b665a
provides dummy routines for the required coefficient routines (of polynomials).
They may be used when calling Singular library routines:
then an error will be reported

**Comment by tthsqe12** [comment]
Thanks, this seems to elliminate the output to stdout.

**Review by fingolfin — APPROVED** [review]
Fine by me, thanks

**Pull request merged**
