### PR TITLE
Fix #3107

### LINKED ISSUE #3107: dualizing does not work for free resolutions
Example due to @wdecker :
```julia
X = veronese();
I = defining_ideal(X);
Pn = base_ring(I)
FI = free_resolution(I)
F = graded_free_module(Pn, 1)
dualFIC = hom(FI.C, F)
```
I suppose the problem is the following: The modules in `FI.C` have different concrete type. Now a list is created from those modules in an incremental way in `src/Modules/UngradedModules/HomologicalAlgebra.jl:361`  with the first element giving a type to that list. The second then does not match anymore.

### PR DESCRIPTION
**Pull request by HechtiDerLachs**
Fix #3107 

CC: @wdecker

### CODE REVIEW

**Comment by HechtiDerLachs** [comment]
I also added some code that can be used as a hotfix to #3108 . @wdecker : Let me know if you would like this to be made available via the `simplify` command.

**Comment by HechtiDerLachs** [comment]
@jankoboehm : If you run `@profview Oscar._alt_simplify(Omega)` in the added test code, then you will see that about 90% of the computing time is spent on inferring the degrees of various generators. This looks suboptimal. So I think #2999 should be looked into at some point.

**Comment by HechtiDerLachs** [comment]
I added methods to drop the grading of graded modules so that it becomes possible to compare timings between the existing implementation of `simplify` and `Oscar._alt_simplify`. Starting from the snippet in #3108 I get the following results:

 * `Oscar._alt_simplify` returns a module with **two** generators while `simplify` returns one with **32**. So my simplification seems to be much better, at least in this particular example. 
 * My code seems to also be better in terms of speed:
```julia
julia> M, iso = forget_grading(Omega);

julia> @time Oscar._alt_simplify(M);
  1.236710 seconds (4.73 M allocations: 218.460 MiB)

julia> @time simplify(M);
  7.122538 seconds (7.66 M allocations: 184.271 MiB)
```
To me these results suggest that we may just replace the current `simplify` function by what is now `Oscar._alt_simplify` in this branch.

**Comment by HechtiDerLachs** [comment]
I was intrigued by #3239 to compare performance. It turned out that Singular was faster in the beginning.

With the latest commit we're both on the same speed and memory consumption:
```
julia> @time M1, iso1 = prune_with_map(M);
  0.578935 seconds (2.31 M allocations: 115.540 MiB)

julia> @time M2, iso2, iso2_inv = Oscar._alt_simplify(M);
  0.515923 seconds (2.12 M allocations: 113.318 MiB)
```
My offer stands to incorporate `_alt_simplify` as the default simplification routine in case of modules over non-polynomial rings.

**Review by jankoboehm — APPROVED** [review]

**Pull request merged**
