### PR TITLE
Collect export

### PR DESCRIPTION
**Pull request by HereAround**
Cf. https://github.com/oscar-system/Oscar.jl/issues/1971. This is just a start, by trying to achieve this for all the code in `AlgebraicGeometry` and (since it turned out to be simple enough) also `Combinatorics`.

### CODE REVIEW

**Comment by afkafkafk13** [comment]
I understand the intention of this cleanup, but now the export statements of several Geometry subpackages ended up all in one file without the information which package / subdirectory each originates from. For the future this is good, but:

Did you find any name clashes etc while doing this? 

If so, we should save this information to resolve the name clashes (by changing names or by seeing that the functions have the same purpose in different settings).

**Comment by HereAround** [comment]
Yes, functions with the same name but different signature do exist. I had a little script do (most of) the work in this PR. Among others, this sorted the exports alphabetically and remove duplicates. So I cannot give you a complete list of "clashes". At least not now. Still, you can rest assured that `dim` is part of that list.

I am skeptical towards keeping track of "clashes":
1. Such a list is likely outdated the moment I create it.
2. Someone has to maintain it.
3. There are other ways to find out about such "clashes", e.g. just run `git grep dim` or `git grep "dim("` or `git grep "function dim"` etc. within `OSCAR`. This seems much more convenient for all parties involved.

Besides, most likely not all of these "clashes" do need attention. An instance that would require attention -- most likely the ones that you are thinking of -- is for instance if we ever intend to have `hirzebruch_surface` or `del_pezzo_surface` as schemes. The toric counterparts already exist. The protoype for handling this is `projective_space`. We can then easily mimic this procedure.

Let me ping @fingolfin who originally raised this issue, and @thofma who also seemed interested.

Note also that @ThomasBreuer accomplished a similar task for `src/Groups` in https://github.com/oscar-system/Oscar.jl/pull/2007

**Comment by afkafkafk13** [comment]
Actually, I did not think of a list to keep updated forever. I thought more of a 'heads up' to the teams so that everyone is reminded of this, has a short look at the differences and proceeds as they see appropriate (i.e. ignoring the majority which is without problems like 'dim', taking care of the few bad ones). 

My idea was in the sense of: While doing a 'uniq' on the export list anyway, let us know about the 'diff' before and after, because this is just one additional command -- assuming that you were scripting this.

**Comment by HereAround** [comment]
> Actually, I did not think of a list to keep updated forever. I thought more of a 'heads up' to the teams so that everyone is reminded of this, has a short look at the differences and proceeds as they see appropriate (i.e. ignoring the majority which is without problems like 'dim', taking care of the few bad ones).
> 
> My idea was in the sense of: While doing a 'uniq' on the export list anyway, let us know about the 'diff' before and after, because this is just one additional command -- assuming that you were scripting this.

My script is very elementary and quite a few tasks need to be performed by hand. Since you seem to care deeply, I can try to give you a list. But this will take time. Maybe I get to it late in the evening today.

**Review by afkafkafk13 — APPROVED** [review]

**Comment by HereAround** [comment]
For the record, @afkafkafk13 and I talked yesterday and agreed that we are happy to proceed *without* the list of duplicate exports.

**Pull request merged**
