### PR TITLE
CI: adjust test subgroups, try macos aarch64 runner for one subgroup and doctests

### PR DESCRIPTION
**Pull request by benlorenz**

### CODE REVIEW

**Comment by benlorenz** [comment]
The macos-14 label is the new M1 runner: https://github.blog/changelog/2024-01-30-github-actions-introducing-the-new-m1-macos-runner-available-to-open-source/
The tests seem to work and run a bit faster, which is good for our macos tests.

**Review by fingolfin — APPROVED** [review]

**Comment by fingolfin** [comment]
Great

**Comment by lgoettgens** [comment]
Do we care that we now don't test on maxOS x86?

**Comment by benlorenz** [comment]
> Do we care that we now don't test on maxOS x86?

I kept the testgroup for the larger testsets `long` on the `macos-latest` label which runs on `x86_64`. So we do have both, but not every test on both architectures.
Another reason for this choice is that the new M1 runners only have 7GB of RAM which might become a problem for some of the larger testsets (the `x86_64` runners have 14GB).

**Pull request merged**
