### PR TITLE
Remove .travis and add github actions

### PR DESCRIPTION
**Pull request by thofma**

### CODE REVIEW

**Comment by thofma** [comment]
I also removed the travis webhook.

**Comment by thofma** [comment]
This is good to go from my part and gives us coverage for linux and ubuntu on 1.3 - nightly.

**Review by fingolfin — APPROVED** [review]
Thanks. Now we need the same for our other repos (at least those still using Travis), hopefully we can use this here as a blueprint.

**Comment by thofma** [comment]
I just noticed that I need to update the badges, but I will do this in a separate PR.

**Pull request merged**
