### PR TITLE
Properties covered schemes

### PR DESCRIPTION
**Pull request by afkafkafk13**
add some standard properties of covered schemes as attributes
(work in progress, in parts untested)

### CODE REVIEW

**Comment by fingolfin** [comment]
@afkafkafk13 my best guess at this point is the test is stuck because there is now a conflict that must be resolved.

**Comment by afkafkafk13** [comment]
Yes, this is from the restructuring PR that was merged half an hour ago. I am working on the conflictsl

**Comment by simonbrandhorst** [comment]
Needs a rebase.

**Comment by afkafkafk13** [comment]
replaced by #2009

**Pull request closed without merging**
