### PR TITLE
Add absolute_automorphism_group(::Type{PermGroup}, ...)

### PR DESCRIPTION
**Pull request by thofma**

### CODE REVIEW

**Review by fieker — COMMENTED** [review]
what happened to the caching introduced in #2436?

**Review by fieker — APPROVED** [review]
we'll have to sort out the caching, but I'd suggest to do this independently

**Comment by fieker** [comment]
There is (?) a missing elem_type for sets of morphisms?

**Comment by thofma** [comment]
Yes, I am on it.

**Pull request merged**
