### PR TITLE
Connect our serialization with Julia serialization

### PR DESCRIPTION
**Pull request by antonydellavecchia**
Minimal working example of distributed processing in oscar. 
Needs https://github.com/thofma/Hecke.jl/pull/1219 before merge due to conflicting
serialize methods.

Extends serialize for Oscar types that aren't julia types. Introduces two Oscar serializer types
The JSONSerializer is how the serialization in Oscar has ben used so far. The IPCSerializer
aims at being efficient by not sending the refs, which then leaves it up to the user
to guarantee that the appropriate refs are sent to processes that need them.

See included test for an example.

### CODE REVIEW

**Comment by antonydellavecchia** [comment]
needs a release of Hecke to resolve errors in tests, a fix was merged in Hecker https://github.com/thofma/Hecke.jl/pull/1219

**Comment by antonydellavecchia** [comment]
This was merged in Hecke https://github.com/thofma/Hecke.jl/pull/1219 
and the tests require a Hecke release to pass

**Comment by thofma** [comment]
There is already a new version. I have restarted CI.

**Review by fingolfin — APPROVED** [review]
It seemed OK on a quick look, let's merge and refine later

**Pull request merged**
