### PR TITLE
Speed up `stabilizer` methods for the natural action of permutation groups, and the actions on sets, tuples, and vectors of pos. integers

### PR DESCRIPTION
**Pull request by ThomasBreuer**
change the code such that the special GAP methods are used for the natural action of permutation groups,
and the actions on sets, tuples, and vectors of pos. integers

### CODE REVIEW

**Comment by ThomasBreuer** [comment]
Here we get a failure in one of the RPTU runs:
```
Worker 4 terminated.
Unhandled Task ERROR: EOFError: read end of file
```
Perhaps @aaruni96 has an idea what is going on here.

**Comment by benlorenz** [comment]
> Here we get a failure in one of the RPTU runs:
> 
> ```
> Worker 4 terminated.
> Unhandled Task ERROR: EOFError: read end of file
> ```
> 
> Perhaps @aaruni96 has an idea what is going on here.

The relevant error is a few lines above:
```
      From worker 4:	[58185] signal (11.2): Segmentation fault: 11
      From worker 4:	in expression starting at /Users/aaruni/Desktop/oscar-runners/runner-2/_work/Oscar.jl/Oscar.jl/experimental/BasisLieHighestWeight/test/MainAlgorithm-test.jl:34
      From worker 4:	_ZNK10__cxxabiv120__si_class_type_info12__do_dyncastElNS_17__class_type_info10__sub_kindEPKS1_PKvS4_S6_RNS1_16__dyncast_resultE at /Users/aaruni/Desktop/oscar-runners/runner-2/_work/_tool/julia/1.10.6/aarch64/lib/julia/libstdc++.6.dylib (unknown line)
      From worker 4:	_ZNK10__cxxabiv117__class_type_info9can_catchEPKNS_16__shim_type_infoERPv at /usr/lib/libc++abi.dylib (unknown line)
```
This looks like some C++ exception handling issue, maybe related to the mixing of different C++ libraries (libstdc++ / libc++). I have seen this a few times but only on the macos RPTU runner. It usually disappears when re-running the job.

**Comment by mjrodgers** [comment]
Oh this is great, there are huge speed improvements here.

**Review by mjrodgers — APPROVED** [review]
This all looks in order, and we can now do a lot of these calculations much more quickly (and many that were not possible before even).

**Pull request merged**
