### PR TITLE
Migration of schemes part iv

### PR DESCRIPTION
**Pull request by HechtiDerLachs**
This migrates the covered schemes. 

The PR is built on #1681 and the relevant changes will significantly decrease, once that is merged.

### CODE REVIEW

**Comment by HereAround** [comment]
@HechtiDerLachs Please rebase to the latest master.

**Comment by HereAround** [comment]
Thank you @HechtiDerLachs - similar to the previous migrations, this looks good to me.

Q: Does this complete the schemes code migration for the time being? Is this ready for review?

**Comment by HechtiDerLachs** [comment]
> Q: Does this complete the schemes code migration for the time being? Is this ready for review?

Yes, this should comprise the remainder of what's necessary to link the toric varieties to the schemes code for the time being. 

And yes, this is ready for review.

**Review by HereAround — APPROVED** [review]
Thank you @HechtiDerLachs . Looks good to me. I merge.

**Pull request merged**
