### PR TITLE
basic function field support

### PR DESCRIPTION
**Pull request by jieaosong**
The idea is to be able to use parameters in coefficients and still compute Gröbner basis using Singular. For now `AbstractAlgebra.RationalFunctionField` only supports one parameter.
```julia
julia> F, a = RationalFunctionField(QQ, "a");

julia> R, (x,y) = PolynomialRing(F, ["x", "y"]);

julia> singular_ring(R)
Singular Polynomial Ring (0,a),(x,y),(lp(2),C)

julia> I = ideal([x^3+a*y, x+(a+1)*y]); groebner_basis(I)
2-element Vector{AbstractAlgebra.Generic.MPoly{AbstractAlgebra.Generic.Rat{fmpq}}}:
 x + (a + 1)*y
 (a^3 + 3*a^2 + 3*a + 1)*y^3 - a*y
```

There is an annoying ambiguity issue with `(::MPolyRing)(::spoly)` so I just duplicated the code.

### CODE REVIEW

**Comment by wdecker** [comment]
May be I misunderstand what is meant here, but there are already fraction fields:

julia> T, (s, t) = PolynomialRing(QQ, ["s", "t"]);

julia> QT = FractionField(T)
Fraction field of Multivariate Polynomial Ring in s, t over Rational Field

julia> R, (x, y, z) = PolynomialRing(QT, ["x", "y", "z"])
(Multivariate Polynomial Ring in x, y, z over Fraction field of Multivariate Polynomial Ring in s, t over Rational Field, AbstractAlgebra.Generic.MPoly{AbstractAlgebra.Generic.Frac{fmpq_mpoly}}[x, y, z])

julia> I = ideal([x*y-3*x,y^3-2//s*x^2*y])
ideal generated by: x*y - 3*x, -2//s*x^2*y + y^3

julia> groebner_basis(I)
3-element Array{AbstractAlgebra.Generic.MPoly{AbstractAlgebra.Generic.Frac{fmpq_mpoly}},1}:
 x*y - 3*x
 -6//s*x^2 + y^3
 x^3 - 9//2*s*x

julia> singular_ring(R)
Singular Polynomial Ring (Coeffs(17)),(x,y,z),(lp(3),C)

**Comment by thofma** [comment]
@wdecker We have conversions between Oscar coefficient rings and Singular coefficient rings. This adds a conversion for the Oscar univariate rational function field.

It would be great to have tests for this. Maybe @tthsqe12 could help with this if you don't have time for this?

**Comment by jieaosong** [comment]
> May be I misunderstand what is meant here, but there are already fraction fields:

Thanks, that does work too. I had [this issue](https://github.com/oscar-system/Singular.jl/issues/416) in Singular.jl so I thought it might be better to use native Singular coefficients whenever possible.

Also I guess native Singular coefficients compute faster: I tried cyclic5 over `GF(32003)` with one parameter, and it's 10 times faster than using fraction field. Maybe it would be better if we could convert multivariate fraction fields to Singular coefficients too.

**Edit.** I added conversion for multivariate fraction fields. But unfortunately it seems that using native Singular coefficients is slower than using fraction fields in general, so maybe this is unnecessary after all.

**Review by tthsqe12 — APPROVED** [review]
Very nice. I guess we will have to move
`(F::Singular.N_FField)(x::gfp_elem)`
and
`(F::Singular.N_FField)(x::fmpq)`
to singular

**Comment by tthsqe12** [comment]
For the various "function field" constructions possible (outside of singular), I listed my understanding here https://github.com/Nemocas/AbstractAlgebra.jl/pull/849#issuecomment-838215478

**Comment by hannes14** [comment]
To use the different implementations for Groebner basis computations efficiently,
one needs fast "clear denominators" and "content" (beside the usual operations)-
Depending on their origin, the different implementations may optimize differently.

**Comment by jieaosong** [comment]
Not to mention the performance, using Singular coefficients also sometimes leads to the following error
```julia
julia> F = FractionField(PolynomialRing(QQ, ["s", "t"])[1]);

julia> R, (x,y) = PolynomialRing(F, ["x", "y"]);

julia> I = ideal([rand(R, 0:5, 0:5, 0:5, 0:5, 0:5) for i in 1:5]); groebner_basis(I);
Flint exception (Divide by zero):
    Divide by zero in fmpz_mpoly_divides_monagan_pearceERROR: Problem in the Flint-Subsystem
```
while the same ideal can be handled without the `singular_ring` conversion...

**Pull request merged**
