### PR TITLE
Change Array -> Vector / Matrix (ON HOLD until Julia 1.6)

### PR DESCRIPTION
**Pull request by fingolfin**
In Julia 1.5 and later, the type of 1 resp. 2 dimensional arrays is printed as
Vector resp. Matrix, and thus doctests need to be adjusted accordingly. The
easiest way to do that was to change this with a regex everywhere, which also
modifies code. I think this makes sense for consistency reasons, though, and
also seems in line with the vision of the Julia team.

Note to self: to regenerate this PR, use
```
git ls-files | xargs perl -pi -e 's/Array\{([^{}]+(\{((?>[^{}]+)|(?2))*\})?),\s*2\s*\}/Matrix{\1}/g'
git ls-files | xargs perl -pi -e 's/Array\{([^{}]+(\{((?>[^{}]+)|(?2))*\})?),\s*1\s*\}/Vector{\1}/g'
git ls-files | xargs perl -pi -e 's/Array\{([^{}]+(\{((?>[^{}]+)|(?2))*\})?),\s*1\s*\}/Vector{\1}/g'
```
and then manually tweak a few remaining cases.

Related PRs:
- https://github.com/Nemocas/AbstractAlgebra.jl/pull/962
- https://github.com/Nemocas/Nemo.jl/pull/1129
- https://github.com/thofma/Hecke.jl/pull/352
- https://github.com/oscar-system/Polymake.jl/pull/352
- https://github.com/oscar-system/Singular.jl/pull/475
- https://github.com/oscar-system/GAP.jl/pull/672

### CODE REVIEW

**Comment by fieker** [comment]
On Wed, Mar 17, 2021 at 02:54:19AM -0700, Max Horn wrote:
> In Julia 1.5 and later, the type of 1 resp. 2 dimensional arrays is printed as
> Vector resp. Matrix, and thus doctests need to be adjusted accordingly. The
> easiest way to do that was to change this with a regex everywhere, which also
> modifies code. I think this makes sense for consistency reasons, though, and
> also seems in line with the vision of the Julia team.
> You can view, comment on, or merge this pull request online at:
> 

I think the merging of this needs to be timed carefully... will it
produce merge conflicts everywhere if code has been changed further?

**Comment by fingolfin** [comment]
Probably. Good thing is that 95% of it is was created by simple perl one liner. So I can exclude some files / directories in this PR now and deal with them later. Presumably the code in `src/Rings`? 

And/or, as you put it, "time it carefully", i.e., merge it just before @wdecker & friends start working on a new round of changes. I am open to either.

**Comment by thofma** [comment]
This did not change in 1.5, but will change in 1.6.

**Comment by thofma** [comment]
I would wait with this until 1.6 is out and people are using it. Otherwise we cannot run the doctests locally.

**Comment by fingolfin** [comment]
@thofma is of course right. I mixed this up (I changed my `julia` to 1.6 a few days ago and forgot about this when I tried get the doctest working yesterday 🤦

**Comment by thofma** [comment]
We could just use https://github.com/JuliaLang/julia/pull/37085#issuecomment-683356098.

**Comment by fingolfin** [comment]
The doctestfilter rule from that Julia PR is buggy, it does not deal with nested declarations like `Array{Array{...,1},2}` correctly. This can be fixed, but maybe the overall question is: which of the two formats should be the default, `Array` or `Vector`/`Matrix`? Since Julia >= 1.6 clearly prefers the later, I think it makes sense to prefer that moving forward (also in new code, and perhaps slowly revising old code to use the new style, too?), and have doctestfilters in "the other direction" to allow testing with older Julia versions.

Anyway: here's a PCRE2 regex that correctly matches Array type declarations with nested braces: `Array\{[^{}]+(\{((?>[^{}]+)|(?1))*\}),\s*1\s*\}`. This matches e.g. `Array{Array{Int,1},1}`. The "1" near the end of the pattern can of course be changed to "2".

And here is how to regenerate this PR without manual tweaks
```sh
git ls-files | xargs perl -pi -e 's/Array\{([^{}]+(\{((?>[^{}]+)|(?2))*\})?),\s*2\s*\}/Matrix{\1}/g'
git ls-files | xargs perl -pi -e 's/Array\{([^{}]+(\{((?>[^{}]+)|(?2))*\})?),\s*1\s*\}/Vector{\1}/g'
git ls-files | xargs perl -pi -e 's/Array\{([^{}]+(\{((?>[^{}]+)|(?2))*\})?),\s*1\s*\}/Vector{\1}/g'
```

**Comment by thofma** [comment]
I would be in favor of moving to the new syntax (`Vector/Matrix`).

**Comment by fingolfin** [comment]
Superseded by PR #600

**Pull request closed without merging**
