### PR TITLE
support group extensions of matrix groups

### PR DESCRIPTION
**Pull request by ThomasBreuer**
- admit `Oscar.GAPGroupElem` not only `Oscar.BasicGAPGroupElem` in evaluating 2-cochains (we need in particular `Oscar.MatrixGroupElem`)

- add a `isomorphism(::Type{FPGroup}, A::AbstractAlgebra.Generic.FreeModule)` method, which is needed by `extension` if we want to support G-modules created from matrix groups acting on vector spaces

- add tests

### CODE REVIEW

**Comment by fieker** [comment]
Mostly happy, but in Cohomology.m we already have 
```
# return an f.p. group `F` and an isomorphism `M -> F`
function fp_group_with_isomorphism(M::AbstractAlgebra.FPModule{<:FinFieldElem})
  p, mp = pc_group_with_isomorphism(M, refine = false)
  mf = isomorphism(FPGroup, p)
  return codomain(mf), mf*mp
end
```
I think we need to consolidate this (and make a consistent interface?) At least as a promise, the "old" function is more general as in accepts not only prime fields, and not only free_modules.
I have no idea if the way via pc-group is efficient though, so an independent implementatino might be useful

**Comment by fieker** [comment]
What about also adding (maybe later)
 - natural_gmodule for matrix groups
 - natural_representation

**Comment by ThomasBreuer** [comment]
Concerning a consistent interface, the code anyhow needs `isomorphism`, thus the natural solution seems to be to move the general implementations from `pc_group_with_isomorphism` and `fp_group_with_isomorphism` to corresponding `isomorphism` methods.

Concerning `natural_gmodule`, there are currently two methods which return a G-module of dimension equal to the group order (what is usually called regular module).
Thus I did not dare to use the name natural module for the G-module that is given by the action of a matrix group of degree n via right multiplication on a n-dimensional vector space.
(Similarly for the action of a permutation group of degree n on a free module of dimension n.)

**Comment by fieker** [comment]
The existing functions will have to be renamed into `regular_gmodule`. And possibly also tied to `getindex(R::Ring, G::Group)` to support `Z[G]`

**Review by fieker — APPROVED** [review]

**Comment by ThomasBreuer** [comment]
O.k., I can adjust the pull request according to the above discussion.

**Comment by ThomasBreuer** [comment]
Concerning the idea

> The existing functions will have to be renamed into `regular_gmodule`. And possibly also tied to `getindex(R::Ring, G::Group)` to support `Z[G]`

There is already a matching `getindex` method in Hecke that constructs a `GroupAlgebra` object.
Thus the question is what we want here.

**Comment by ThomasBreuer** [comment]
@fieker I have updated the pull request as we had discussed.
See the commit message of 757ad59 for the details.

**Comment by fieker** [comment]
on first glance: looks good!

**Comment by fingolfin** [comment]
I'll discuss this next week with @fieker and @ThomasBreuer to see if we can merge (and I'll try to get in a review I before that, too)

**Review by fingolfin — APPROVED** [review]
Looks good to me as well, @fieker should be in the office within the next hour and we can then let him merge it

**Pull request merged**
