### PR TITLE
Toric morphisms to morphisms of covered schemes

### PR DESCRIPTION
**Pull request by HechtiDerLachs**
Continuation of #2741 . To be rebased eventually.

### CODE REVIEW

**Comment by HereAround** [comment]
Rebased just now, since https://github.com/oscar-system/Oscar.jl/pull/2741 has been merged.

**Comment by HechtiDerLachs** [comment]
Looks like we should override the print method for toric morphisms once again. For now it seems to default to the one for morphisms of covered schemes which entails actually computing the whole thing. We definitely want to avoid that.

**Comment by HereAround** [comment]
> Continuation of #2741 . To be rebased eventually.

Just rebased to the latest master.

**Comment by HereAround** [comment]
Based on conversations with @HechtiDerLachs, this is ready for review. As the title says, this PR allows to convert a toric morphism to a morphism of (covered) schemes. In this regard, this PR is again at the interface between toric geometry and algebraic geometry. Hence, it seems reasonable to bring expertise from both areas to check on this PR. Let me thus call in @lkastner @simonbrandhorst - what do you think of this PR?

(The upshot of all this is to enable blowup functionality, including proper/strict transforms in the toric setting and then to make use of these tools in the context of the FTheoryTools. I am sure @apturner will be very happy with the changes in this PR and the next couple that @HechtiDerLachs and I are working on/discussing.)

**Review by simonbrandhorst — APPROVED** [review]
I was looking forward to this! Well done.

**Pull request merged**
