### PR TITLE
PolyhedralGeometry: Add mixed integer linear programs (MILP)

### PR DESCRIPTION
**Pull request by lkastner**
Also remove some clutter from docs of LP

### CODE REVIEW

**Comment by tthsqe12** [comment]
Let me just make sure this works for my purposes.

**Review by benlorenz — APPROVED** [review]

**Comment by tthsqe12** [comment]
So I tried it on the problem
```
minimize x + y subject to
1. x,y in ZZ
2. x >= 1
3. y >= 1
4. x + y >= 0
```
and it is not liking this problem. Here is my snippet
```
@show AA
@show b
  P = Polyhedron(AA, b)
@show P
  c = ones(Int, out_sigma)
@show c
  LP = MixedIntegerLinearProgram(P, c; convention = :min)
@show LP
  s = optimal_solution(LP)
@show s
```

and here is the output
```
AA = BigInt[-1 0; 0 -1; -1 -1]
b = BigInt[-1, -1, 0]
P = A polyhedron in ambient dimension 2
c = [1, 1]
LP = A mixed integer linear program
polymake:  WARNING: could not compute 'MINIMAL_SOLUTION' probably because of unsatisfied preconditions:
precondition : BOUNDED ( to.milp: MILP.MINIMAL_VALUE, MILP.MINIMAL_SOLUTION : MILP.LINEAR_OBJECTIVE, FACETS | INEQUALITIES ) ( applied to parent )
precondition : FEASIBLE ( VERTICES, LINEALITY_SPACE, CONE_DIM : CONE_AMBIENT_DIM ) ( applied to parent )
precondition : FEASIBLE ( FACETS, AFFINE_HULL, CONE_DIM : CONE_AMBIENT_DIM ) ( applied to parent )
precondition : POINTED ( BOUNDED: ) ( applied to parent )
s = nothing
```

**Comment by tthsqe12** [comment]
At this point, when minimizing `c.x`, I will just add the condition `c.x <= 10^6`.

**Review by tthsqe12 — APPROVED** [review]

**Comment by tthsqe12** [comment]
Is general, is optimization over unbounded domains disallowed?

**Comment by lkastner** [comment]
> Is general, is optimization over unbounded domains disallowed?

No, it should be possible. But the backend `to` here cannot deal with unbounded things. We have an interface to [SCIP](https://scipopt.org/), but this is not yet available in Oscar. Benjamin is looking into this. There is a SCIP_jll available, I am not completely sure whether that is legal, since SCIP comes with another license...

There is also still https://github.com/oscar-system/Oscar.jl/issues/585 in this context.

**Pull request merged**
