### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by thofma**

### CODE REVIEW

**Comment by thofma** [comment]
@benlorenz Can you add the new Polymake version here?

**Comment by thofma** [comment]
probably also needs #1466

**Comment by benlorenz** [comment]
The new `libpolymake_julia` was built as a patch-level bump so this should have been compatible, but it turned out that there were some tests in Oscar that relied on some output ordering which changed with the update, with #1466 merged these tests should be fine now.

New failure is from `iso_oscar_gap`:
```
(p, d) = (2, 1): Error During Test at /home/runner/work/Oscar.jl/Oscar.jl/test/GAP/iso_oscar_gap.jl:58
  Got exception outside of a @test
  MethodError: no method matching embed(::FqFiniteField, ::FqDefaultFiniteField)
Closest candidates are:
  embed(::T, ::T) where T<:FinField at ~/.julia/packages/Nemo/cIKEX/src/embedding/embedding.jl:367
  Stacktrace:
    [1] _iso_oscar_gap_field_finite_functions(FO::FqDefaultFiniteField, FG::GAP_jll.GapObj)
    @ Oscar~/work/Oscar.jl/Oscar.jl/src/GAP/iso_oscar_gap.jl:133
    [2] _iso_oscar_gap(FO::FqDefaultFiniteField)
    @ Oscar~/work/Oscar.jl/Oscar.jl/src/GAP/iso_oscar_gap.jl:186
...
```

**Comment by tthsqe12** [comment]
This is a strange failure, and I will have a look tomorrow.

**Comment by thofma** [comment]
@tthsqe12 just push directly here

**Comment by tthsqe12** [comment]
So we (I) update all of the rats now?

**Comment by thofma** [comment]
Do you have the bandwidth? I can also do it.

**Comment by tthsqe12** [comment]
I will do them with our 650 Mbps

**Comment by thofma** [comment]
I guess this looks. I will merge later today if there are no objections.

**Comment by tthsqe12** [comment]
Fine by.

**Pull request merged**
