### PR TITLE
Implement `simplify` for `ComplexOfMorphisms`

### PR DESCRIPTION
**Pull request by HechtiDerLachs**
Now the code for `canonical_bundle` looks sane. 

What happened? There was no method `simplify(::ComplexOfMorphism)`. And there could not be any reasonable such method which would not switch to the new lazy complexes as return values, since the `ComplexOfMorphism`s would need a lot of extra care to become sufficiently lazy. Hence I added that method and everything works just fine. No dubious calls to special methods in the code for `canonical_bundle` anymore. 

Ping @wdecker @jankoboehm

### CODE REVIEW

**Comment by fingolfin** [comment]
I am confused by the title, "switch to lazy complexes". The other complexes are also lazy.

**Comment by lgoettgens** [comment]
I am confused as well. You don't touch any code inside `canonical_bundle`, so how could become sane now?

**Comment by HechtiDerLachs** [comment]
I do touch code in `canonical_bundle`. Before you had to use a special method of `free_resolution` which takes the desired type for the output (`Oscar.SimpleFreeResolution`) as first argument. The type is not exported and it would be weird to explain to any outsider why you would have to make this sophisticated special call to get the unleashed functionality of the hypercomplexes. Now you can just call the classical `free_resolution` and the passage to hypercomplexes is done by the corresponding new method for `simplify` one line below. This makes the use more streamlined and intuitive and it "hides" the passage to hypercomplexes. 

Earlier on I was deliberately hiding the access to the hypercomplexes a bit, since at the time I didn't want to interfere with the classical `ComplexOfMorphism`s too much. But now that people want to use it and we eventually fuse them with the existing functionality, this is a step forward. 

As I said: Having `simplify` return a `ComplexOfMorphisms` would most likely not be desirable, so the implementation given here seems legitimate.

**Comment by HechtiDerLachs** [comment]
I was unaware of the existence of `canonical_bundle` as an Oscar function, hence the confusion. Before, I only changed the body of such a function with the same name which was declared locally in a test file. After consulting with @wdecker today, I now adjusted the actual OSCAR code.

**Comment by jankoboehm** [comment]
It does exactly what we discussed, so I think we can go ahead.

**Review by wdecker — APPROVED** [review]

**Pull request merged**
