### PR TITLE
Prepare for GAP 4.12

### PR DESCRIPTION
**Pull request by fingolfin**

### CODE REVIEW

**Comment by fingolfin** [comment]
Tests fail in the invariant code:
```
julia> K, a = CyclotomicField(9, "a")
(Cyclotomic field of order 9, a)

julia> M = matrix(K, 2, 2, [ a, 0, 0, -a^3 ])
[a      0]
[0   -a^3]

julia> RG = invariant_ring(M)
Invariant ring of
Matrix group of degree 2 over K
with generators
AbstractAlgebra.Generic.MatSpaceElem{nf_elem}[[a 0; 0 -a^3]]

julia> invars = primary_invariants(RG)
ERROR: Error thrown by GAP: Error, no method found! For debugging hints type ?Recovery from NoMethodFound
Error, no 1st choice method found for `Enumerator' on 1 arguments at /Users/mhorn/.julia/artifacts/277259a1ec06cd0e4f6f209ea1a0608cc52e2a1a/share/gap/lib/methsel2.g:249 called from
Enumerator( C ) at /Users/mhorn/.julia/artifacts/277259a1ec06cd0e4f6f209ea1a0608cc52e2a1a/share/gap/lib/coll.gi:831 called from
for x in v do
p := Position( f, x );
sy := n * sy + (p - 1);
od; at /Users/mhorn/.julia/artifacts/277259a1ec06cd0e4f6f209ea1a0608cc52e2a1a/share/gap/lib/dicthf.gi:125 called from
hash!.intKeyFun( key ) at /Users/mhorn/.julia/artifacts/277259a1ec06cd0e4f6f209ea1a0608cc52e2a1a/share/gap/lib/dict.gi:759 called from
AddDictionary( dict, img, Length( orb ) ); at /Users/mhorn/.julia/artifacts/277259a1ec06cd0e4f6f209ea1a0608cc52e2a1a/share/gap/lib/grpmat.gi:307 called from
DoSparseLinearActionOnFaithfulSubset( grp, OnRight, sort ) at /Users/mhorn/.julia/artifacts/277259a1ec06cd0e4f6f209ea1a0608cc52e2a1a/share/gap/lib/grpmat.gi:502 called from
...  at *defin*:0

Stacktrace:
 [1] error(s::String)
   @ Base ./error.jl:35
 [2] ThrowObserver(depth::Int32)
   @ GAP ~/Projekte/OSCAR/GAP.jl/src/GAP.jl:67
```

I'll look into what causes this regression. But I'll also see if we can't improve this backtrace at least a bit, as right now it gives zero indication as to which Julia code lead to it ...

**Comment by fingolfin** [comment]
@ThomasBreuer is working on a fix in https://github.com/gap-system/gap/pull/5188 I think

**Comment by fingolfin** [comment]
The updated GAP_lib_jll with the fix by @ThomasBreuer seems to work fine. Just pushed another minor fix for a docstring, hopefully this is complete now.

**Comment by thofma** [comment]
Out of curiosity, was the `transitivity` function giving wrong results?

**Comment by fingolfin** [comment]
Yes and no... one could call it buggy, but strictly speaking, it just behaved weirdly in edge cases that were not covered explicitly by the documentation. Specifically, if you gave an action "domain" that was not actually orbit-closed under the action, it gave strange results... Like if you ask for the transitivity of `Sym(5)` acting on `{1,2,3}`... well, it doesn't really act on it, does it? But it still gave "3" as answer... Wwhy? dunno what good answer to give... one could certainly come up with a justification, but in the end most people I talked to agreed this is more confusing and source of potential bugs than helpful. So we changed it in GAP. Right now it returns 0 because it does not act transitively -- it doesn't act *at all* on that set. So perhaps instead of 0 we should raise an error, I am open to that, too. But the old behavior IMHO was just bad and confusing.

**Comment by thofma** [comment]
Ah thanks for the explanation. I did not check too carefully. FWIW, I would opt for error.

**Comment by fingolfin** [comment]
Yeah... I now actually wonder why we didn't go for an error on the GAP side, too -- @ThomasBreuer do you remember?

BTW this affects other things, e.g. the primitivity check.

**Comment by fingolfin** [comment]
(On the GAP side, I'd return `fail` instead of an error, as that makes it easier to handle there... on the Julia/OSCAR said, we could then turn that into an exception)

**Comment by ThomasBreuer** [comment]
Concerning the definition of transitivity:
Yes, this question should have been raised in the discussion about gap-system/gap/pull/4907 or gap-system/gap/issues/4904 because the same arguments hold for `Transitivity` that are valid for `IsTransitive`.

I will create a pull request for GAP to change `Transitivity`, and will also create a pull request for Oscar that changes `transitivity` independent of the underlying GAP code.

**Review by ThomasBreuer — APPROVED** [review]

**Pull request merged**
