### PR TITLE
Global h2

### PR DESCRIPTION
**Pull request by fieker**

### CODE REVIEW

**Comment by fieker** [comment]
of course, requires GlobalH2 in Nemo and Hecke...

**Comment by thofma** [comment]
I released a new Hecke and bumped the version here. Let's see how well it fares.

**Comment by thofma** [comment]
@fieker this looks good. Not sure if you want to add some small example, so merge at your own discretion.

**Comment by fieker** [comment]
Great thanks. I merge to to get it done, and then proceed

**Pull request merged**
