### PR TITLE
Improvements and bug fixes for toric varieties

### PR DESCRIPTION
**Pull request by HereAround**
* Use graded_polynomial_ring to construct the ideal of linear relations. (So far, no grading was given to its ambient ring.)
* Add checks to (weighted) projective space and affine space to prevent edge cases/inconsistent input.

Hopefully, we can also fix the inconsistent behavior among affine_space and projective_space of dimension 0. Details below.

### CODE REVIEW

**Comment by HereAround** [comment]
As reported by @mgemath , there is an inconsistency among affine and projective spaces of dimension 0. Specifically, it looks to me like `projective_space(NormalToricVariety,0)` returns the desired object, but affine space of dimension 0 seems to return an inconsistent fan.

Essentially, `affine_space(NormalToricVariety,0)` executes the following:
```julia
C = positive_hull(identity_matrix(ZZ, 0))
polyhedral_fan(C)
```
But this polyhedral fan seems inconsistent. For instance, it has no maximal cones, whereas I would expect to have as only (maximal) cone the cone that consists only of the origin. If I recall correctly, calling `polyhedral_fan` with a list of cones checks for such inconsistencies. Indeed,
```julia
polyhedral_fan(maximal_cones(polyhedral_fan(C)))
ERROR: no matching overloaded instance of Polymake::fan::check_fan_objects() at -e line 0.
        eval {...} called at -e line 0
```
I am a bit confused by the error message. @lkastner, what do you think?

**Comment by fingolfin** [comment]
(sorry for the spurious changes I just reverted, I was sleepily editing the wrong window / wrong PR 😬 )

**Comment by benlorenz** [comment]
The issues with trivial fans will be resolved with #2951.

**Comment by HereAround** [comment]
> The issues with trivial fans will be resolved with #2951.

Thank you. Great!

**Comment by HereAround** [comment]
There is an overlap of this PR with https://github.com/oscar-system/Oscar.jl/pull/2944. I will merge https://github.com/oscar-system/Oscar.jl/pull/2944 first, then rebase this PR. Once complete, this will be ready for review.

**Comment by HereAround** [comment]
All covered in https://github.com/oscar-system/Oscar.jl/pull/2944, so I close this PR/draft.

**Pull request closed without merging**
