### PR TITLE
Make new versions of AA, Nemo, Hecke available

### PR DESCRIPTION
**Pull request by lgoettgens**
This PR collects everything that has to be adapted to keep master green.

GroupsCore: includes and thus closes #3139, closes #3070
Padics: includes and thus closes #3196

[skip ci]

### CODE REVIEW

**Comment by joschmitt** [comment]
Somebody else has to cherry-pick https://github.com/oscar-system/Oscar.jl/pull/3230/commits/0c0e8c878da1e2d0a1754c64500d893466162359 . I don't have "write" rights.

**Comment by lgoettgens** [comment]
> Somebody else has to cherry-pick [0c0e8c8](https://github.com/oscar-system/Oscar.jl/commit/0c0e8c878da1e2d0a1754c64500d893466162359) . I don't have "write" rights.

I do that once I come across this on my list.

**Comment by fingolfin** [comment]
Yeah and we'll likely (?) need #3196 and #3139 and probably more...

**Comment by lgoettgens** [comment]
Local testing against https://github.com/oscar-system/Singular.jl/commit/f5db18373ddce174cbdecf1f51201d2668bbfc52 succeeds now. So I think the only thing missing now is a Singular.jl release (and adjustments to everything else contained in there, e.g. https://github.com/oscar-system/Singular.jl/pull/764).

**Review by fingolfin — APPROVED** [review]

**Review by thofma — APPROVED** [review]

**Pull request merged**
