### PR TITLE
move functions into Hecke for this branch

### PR DESCRIPTION
**Pull request by fieker**

### CODE REVIEW

**Comment by fieker** [comment]
`ngens` is migrated to Hecke and available in master. Merging needs to wait until a new Hecke release...

**Comment by fingolfin** [comment]
@fieker @thofma any plans for that new Hecke release then? Would be nice to have for the next Oscar.jl release, too, I guess?

**Comment by thofma** [comment]
Will do today.

**Comment by fieker** [comment]
On Thu, Nov 11, 2021 at 11:54:37PM -0800, Tommy Hofmann wrote:
> Will do today.

Great! Thanks

**Review by fingolfin — APPROVED** [review]

**Pull request merged**
