### PR TITLE
Scheme development

### PR DESCRIPTION
**Pull request by HechtiDerLachs**
This is a pull request from our work in progress on Schemes. 

Questions and comments are very welcome.

### CODE REVIEW

**Comment by thofma** [comment]
This needs to be rebased.

**Comment by fingolfin** [comment]
A rebase may be non-trivial, though. This PR / branch looks as if one or more merges went really wrong / had bas conflict resolution

**Comment by HechtiDerLachs** [comment]
Ok, I'm not sure I really understand what that means. Maybe we meet some time in Gather tomorrow and review this? If yes, let me know which time suits you best.

**Comment by thofma** [comment]
Changes are high that we don't want to preserve the history, so that you could just start with an up to date Oscar master branch and copy the files around. We have the usual meeting at 3 pm. We could discuss this before the meeting.

**Comment by HechtiDerLachs** [comment]
Ok, that sounds fine with me. 

I remember that I had once pulled from the original repository to my branch in order to be up to date and that had f***ed up everything. I spent one whole afternoon fixing that (by now, it would probably take less time, though...) 

Either way, I will give it a try tomorrow and we can try to figure everything out before our meeting; say around 2:30?

**Comment by thofma** [comment]
Sounds good.

**Pull request closed without merging**
