### PR TITLE
Issue/772 and SubObjectIterator

### PR DESCRIPTION
**Pull request by alexej-jordan**
To solve the stated issue, I introduce a new iterator. This iterator stores a `Polymake.BigObject` to directly access its sub-objects via polymake's methods. The advantage compared to the existing iterators is that already computed data (e.g. volume of a polytope which was determined as part of the volume of a complex) is preserved this way. On the other hand, the already existing iterators store as few information as possible, which can help in different contexts.

This iterator should of course be applicable in different situations, and these can look very different. So the one of the fields is a julia `Function` object (with first argument our `Polymake.BigObject` and second one is the index), which is called within the `getindex` method. We can easily define new functions/methods and always use the `SubObjectIterator`, so the user does not have to deal with hundreds of different iterators.

#772 is closely related to #749 which is why I based this branch there. Depending on when the latter one is to be merged we might have to rebase this branch.

EDIT: Thanks to @benlorenz this branching has been resolved.

### CODE REVIEW

**Review by lkastner — APPROVED** [review]
If you have time it would be great if you could write some tests for the new functionality too. Does `PolyhedralFan(maximal_cones(PF))` work? Or would it be `PolyhedralFan(rays(PF), maximal_cones(PF))`?

I like this very much, also since it reduces the code to be better to understand.

**Comment by lkastner** [comment]
Also it seems like the old functions are still in the docs.

**Comment by alexej-jordan** [comment]
> If you have time it would be great if you could write some tests for the new functionality too.
While we can test specific applied cases (i.e. `maximal_cones`) like always, directly testing the `SubObjectIterator` might not prove meaningful (beyond very basic stuff like subtyping) due to the `Function` object stored inside. I will see how much I can do.

> Does `PolyhedralFan(maximal_cones(PF))` work? Or would it be `PolyhedralFan(rays(PF), maximal_cones(PF))`?
Together with the change on the corresponding branch in the Polymake.jl repository, we have `PolyhedralFan(maximal_cones(PF))` (using polymake's `check_fan_objects`, working for any `AbstractVector{Cone}`), or you can use `PolyhedralFan(rays(PF), incidence_matrix(maximal_cones(PF))`.

**Comment by lkastner** [comment]
Ok, we can have it work like that. Nevertheless, going via the `check_fan_objects` method is much more expensive than the actual constructor, since it will check whether the intersection of any two cones is a face of both. So a lot of unnecessary convex hull. But I see the problem, why it would be hard to avoid on the technical side.

**Review by benlorenz — COMMENTED** [review]
This looks very reasonable, thanks!
Currently the `maximal_cones` function is somewhat inconsistent with the `cones` function which has the additional `as::Type{T} = Cone` argument. Looking at the design of this here I am once more wondering whether to remove it for `cones` or add it here.
We could maybe add a reference to the `BigObject` in the other iterators (`VectorIterator`, `HalfspaceIterator`) as well and then use something like `ray_indices(facets(cone))`, `ray_indices(cones(fan, dim))`, or `facet_indices(...)` to retrieve the indices directly from the polymake object. But we would need slightly different names instead of just `incidence_matrix` then to make it clear what kind of indices this refers to.

Apart from this here, I have added a comment in the associated PR here https://github.com/oscar-system/Polymake.jl/pull/369 regarding the use of the `Array{BigObject}`.

**Comment by benlorenz** [comment]
> > > Does `PolyhedralFan(maximal_cones(PF))` work? Or would it be `PolyhedralFan(rays(PF), maximal_cones(PF))`?

> > Together with the change on the corresponding branch in the Polymake.jl repository, we have `PolyhedralFan(maximal_cones(PF))` (using polymake's `check_fan_objects`, working for any `AbstractVector{Cone}`), or you can use `PolyhedralFan(rays(PF), incidence_matrix(maximal_cones(PF))`.

> Ok, we can have it work like that. Nevertheless, going via the `check_fan_objects` method is much more expensive than the actual constructor, since it will check whether the intersection of any two cones is a face of both. So a lot of unnecessary convex hull. But I see the problem, why it would be hard to avoid on the technical side.

Can we just add a special case for this using some `PolyhedralFan(cones::SubObjectIterator)` ?

**Comment by lkastner** [comment]
> Can we just add a special case for this using some `PolyhedralFan(cones::SubObjectIterator)` ?

I would say yes, but then we need to be careful not to use this iterator for lists of weird cones that intersect non-properly.

**Comment by alexej-jordan** [comment]
> > Can we just add a special case for this using some `PolyhedralFan(cones::SubObjectIterator)` ?
> 
> I would say yes, but then we need to be careful not to use this iterator for lists of weird cones that intersect non-properly.

Does polymake have `BigObject`s such that that can have a weird collection of cones as its sub-objects? If no, this could be save to use for this iterator.

**Comment by lkastner** [comment]
I think polymake should be fine.

**Review by lkastner — APPROVED** [review]

**Review by lkastner — APPROVED** [review]

**Review by benlorenz — APPROVED** [review]

**Pull request merged**
