### PR TITLE
Module

### PR DESCRIPTION
**Pull request by dschaefetu-kl**

### CODE REVIEW

**Comment by thofma** [comment]
Could you rebase with current master branch? Then we get a CI run.

**Comment by fingolfin** [comment]
Just FYI, you can also close & reopen a PR to force a CI re-run of any PR (assuming it merges cleanly)

**Comment by thofma** [comment]
It had already run since he force pushed.

**Comment by dschaefetu-kl** [comment]
Considering that the tests for the nightly builds do not pass, how can I attack this issue?

**Comment by thofma** [comment]
Not your fault. This is good to go as far as tests/CI is concerned.

**Pull request merged**
