### PR TITLE
`GModule`: replace `_hom`

### PR DESCRIPTION
**Pull request by ThomasBreuer**
Create the images of generators directly, instead of first creating pseudo-inverses and compositions of maps.
(Eventually, restricting the group action to a submodule should become a function of its own.)

(also fixed a call of `maximal_submodule_bases`)

### CODE REVIEW

**Comment by fieker** [comment]
On Fri, Apr 12, 2024 at 05:22:21AM -0700, Thomas Breuer wrote:
> Create the images of generators directly, instead of first creating pseudo-inverses and compositions of maps.
> (Eventually, restricting the group action to a submodule should become a function of its own.)
> 
I think sub(GModule, module or similar) already exists...

**Comment by ThomasBreuer** [comment]
O.k., `sub(M::GModule, phi::Map)` shall take an embedding with codomain `M` and shall return `S, emb` such that `S` is a `GModule` for the same group as `M` but with module `S`.
(I have not found this, will add it.)

**Comment by fieker** [comment]
On Fri, Apr 12, 2024 at 05:47:06AM -0700, Thomas Breuer wrote:
> O.k., `sub(M::GModule, phi::Map)` shall take an embedding with codomain `M` and shall return `S, emb` such that `S` is a `GModule` for the same group as `M` but with module `S`.
> (I have not found this, will add it.)
> 
I thought you even fixed a bug in it...

**Comment by ThomasBreuer** [comment]
There is `Oscar.sub(C::GModule{<:Any, <:AbstractAlgebra.FPModule{T}}, m::MatElem{T}) where {T <: FinFieldElem}` but this is a different situation.

**Review by fingolfin — APPROVED** [review]

**Pull request merged**
