### PR TITLE
Fixes divides for quotient rings

### LINKED ISSUE #645: Something goes wrong with divides in quotient rings
Try the following code in julia: 

`using Oscar`

`R, vars = QQ["x","y"]`
`x = vars[1]`
`y = vars[2]`
`I = ideal(R, [zero(R)] )`
`Q, proj = quo(R,I)`
`f = proj(x*y)`
`# This command works:`
`divides( one(R), x*y )`
`# this one doesn't:`
`divides( one(Q), f )`

What's going wrong there?

### PR DESCRIPTION
**Pull request by ederc**
Should fix #645

### CODE REVIEW

**Comment by thofma** [comment]
If I understand it correctly, this means not calling `exp_groebner_assure` anymore by default. Is `exp_groebner_assure` itself still broken?

**Comment by ederc** [comment]
Well, `exp_groebner_assure` is now only locally used in experimental/ModStd where it is also defined. I wasn't aware that there was another `groebner_assure` outside of groebner.jl.

**Comment by thofma** [comment]
Yes and in #645 an error was found in the function `exp_groebner_assure`, correct? . My question is, whether this error is fixed with this PR here or is still present.

**Comment by ederc** [comment]
I have not touched `exp_groebner_assure` besides renaming, I don't know the effects on @fieker 's modstd implementations. I just isolated it such that we use `groebner_assure` from groebner.jl besides experimental/ModStd.

**Comment by thofma** [comment]
OK,  so the "fix" is to just call another function and to leave the original one (`exp_groebner_assure`) broken with a known but untracked bug.

**Comment by ederc** [comment]
Well, the PR is called "Fixes divides for quotient rings #647 " and not "Fixes exp_groebner_assure". And the "fix" is not only to call a different function as one can see.

**Pull request merged**
