### PR TITLE
ToricVarieties: Extend Chow ring to non-complete varieties

### PR DESCRIPTION
**Pull request by HereAround**
The Chow ring can also be computed for toric varieties that are merely simplicial (and not complete). This opens an avenue for examples of toric varieties whose Chow ring is identical to that of certain matroids. The corresponding functionality (respectively, extending the computability of Chow rings to non-complete but simplicial toric varieties) has been added for @bschroter.

~~For my convenience, this includes the changes in https://github.com/oscar-system/Oscar.jl/pull/1650.~~

### CODE REVIEW

**Comment by tthsqe12** [comment]
@HereAround couldn't find email so here it is
```
julia> using Oscar

julia> does_it_accept_it(a) = false;

julia> does_it_accept_it(a::MPolyElem{fmpq}) = true;

julia> R, (x, y) = PolynomialRing(QQ, ["x", "y"]);

julia> typeof(x)
fmpq_mpoly

julia> does_it_accept_it(x)
true

julia> R, (x, y) = GradedPolynomialRing(QQ, ["x", "y"]);

julia> typeof(x)
MPolyElem_dec{fmpq, fmpq_mpoly}

julia> does_it_accept_it(x)
true
```

**Comment by HereAround** [comment]
~~While working on this draft, I noticed a few points in the bibliography that required a separate fix (cf. https://github.com/oscar-system/Oscar.jl/pull/1749 and https://github.com/thofma/Hecke.jl/pull/888). For my convenience, these changes are currently included here. Upon rebase, these will be gone eventually once the above PRs have been merged.~~

Completed.

**Comment by HereAround** [comment]
@bschroter Is this as you desired?

**Review by fingolfin — APPROVED** [review]
Sounds plausible to me but I can't judge the math in here. So I guess @bschroter's input would be helpful

**Comment by bschroter** [comment]
It looks good to me. As I mentioned in a privat `Slack' discussion with @HereAround, the docs might need an update, and it would be nice to construct a function that compares two quotient rings. This could be used for an example in the book as well as a testcase for the code. The code to produce both Chow rings looks like this:

```
M = uniform_matroid(2,4)
pm_fan = Polymake.tropical.matroid_fan{min}(M.pm_matroid)
fan_rays = pm_fan.RAYS[1:length(flats(M))-2,3:length(M)+1]
fan_cones = pm_fan.MAXIMAL_POLYTOPES[1:pm_fan.N_MAXIMAL_POLYTOPES,1:length(flats(M))-2]
polyfan = PolyhedralFan(fan_rays,fan_cones)
tv = NormalToricVariety(polyfan)
tCH = chow_ring(tv)
mCH = chow_ring(M)
```

**Review by lkastner — APPROVED** [review]
Thanks.

I figured out my problem with `bibtool`. Apparently it sorts first by key, which I find a bit confusing.

**Comment by HereAround** [comment]
Thank you all for the feedback.

@bschroter I have fixed the documentation issue that you pointed out on slack. (In an earlier draft, I introduced `chow_ring(v::AbstractNormalToricVariety; check_complete::Bool = true)`. Eventually, I removed `check_complete::Bool = true` expect for one place. That is what I fixed now.)

Regarding your code sample, I see two possibilities:
1. If you suggestion works for all matroids, then we could introduce an attribute `toric_variety(a_matroid)`, which executes
```julia
M = "a matroid"
pm_fan = Polymake.tropical.matroid_fan{min}(M.pm_matroid)
fan_rays = pm_fan.RAYS[1:length(flats(M))-2,3:length(M)+1]
fan_cones = pm_fan.MAXIMAL_POLYTOPES[1:pm_fan.N_MAXIMAL_POLYTOPES,1:length(flats(M))-2]
polyfan = PolyhedralFan(fan_rays,fan_cones)
tv = NormalToricVariety(polyfan)
```
2. If this is more specialized, then we could at least improve the example in question.

I would suggest to reserve this for a separate PR and to discuss in more detail on slack. Do you agree?

For the comparison of quotient rings (i.e. could one add a method in `Oscar` (or maybe `Singular.jl`?) which accepts two quotient rings and tells if those are isomorphic): I believe that is also best discussed separately. Nonetheless, let me ping @tthsqe12.

**Comment by bschroter** [comment]
I agree this is a task for its own. In particular, when we include the isomorphism test. The pice of code should work for all loopless matroids as long as I picked all indices correctly.

Feel free to contact me whenever you ready to prepare the next PR.

**Pull request merged**
