### PR TITLE
make `docs/make_local.jl` work again

### PR DESCRIPTION
**Pull request by ThomasBreuer**

### CODE REVIEW

**Comment by ThomasBreuer** [comment]
Sorry, I misunderstood the situation after #502.
Apparently one is no longer expected to build the documentation locally via `include("make_local.jl")`; instead one can now call `using Oscar; Oscar.build_doc()`.
Wouldn't it be better to get rid of the file `docs/make_local.jl`, such that one is not tempted to just `include` it?

**Comment by fingolfin** [comment]
Yeah, probably -- unless I am missing something (@fieker?)

**Comment by fieker** [comment]
On Mon, Jul 05, 2021 at 01:51:54PM -0700, Max Horn wrote:
> Yeah, probably -- unless I am missing something ***@***.***?)
> 
Be my guest - I guess this is part of the developer docu/ workflow.
... there are also some importatnt differences:
 - include ... will work in the current "project" where typically the
   documeter tools are not installed
 - build_doc() works in the documenter env, where typicallyl nothing is
   installed, thus
 - doc_init() to install all documenter deps
 - dov_update_deps() to update the toolchain

**Comment by fingolfin** [comment]
So I was missing something, it *is* used:
```
$ git grep -n -P "\bmake(|_work|_local)\.jl"
.github/workflows/Docu.yml:25:        run: julia --project=docs/ docs/make.jl
docs/make.jl:6:include(normpath(joinpath(Oscar.oscardir, "docs", "make_work.jl")))
docs/make_local.jl:4:include(normpath(Oscar.oscardir, "docs", "make_work.jl"))
src/Oscar.jl:125:    Base.include(Main, joinpath(oscardir, "docs", "make_local.jl"))
```
But I have not yet fully understood how this all fits together...

**Comment by fieker** [comment]
On Wed, Jul 07, 2021 at 03:42:52AM -0700, Max Horn wrote:
> So I was missing something, it *is* used:
> ```
> $ git grep -n -P "\bmake(|_work|_local)\.jl"
> .github/workflows/Docu.yml:25:        run: julia --project=docs/ docs/make.jl
> docs/make.jl:6:include(normpath(joinpath(Oscar.oscardir, "docs", "make_work.jl")))
> docs/make_local.jl:4:include(normpath(Oscar.oscardir, "docs", "make_work.jl"))
> src/Oscar.jl:125:    Base.include(Main, joinpath(oscardir, "docs", "make_local.jl"))
> ```
> But I have not yet fully understood how this all fits together...
> 

make.jl is necessary for julia's Doc building excercise

make_local.jl defines the functions used to have Oscar.build_doc()

The actual doc building code is in make_work - which is included in
make.jl (and then executed)
and included in make_local (and not executed, but stored in some Module)

But we can chat...

**Pull request closed without merging**
