### PR TITLE
remove an import to suppress a warning

### PR DESCRIPTION
**Pull request by simonbrandhorst**
@fieker @micjoswig  
Hopefully this will fix your warning.

### CODE REVIEW

**Comment by thofma** [comment]
@lgoettgens was faster than you, and he also kept `is_effective` in #3056. Which one should we take?

**Comment by lgoettgens** [comment]
is_effective has methods both in and outside the PlaneCurve submodule. So we should keep it

**Comment by simonbrandhorst** [comment]
Alright. I close this one then.

**Comment by micjoswig** [comment]
Thanks.  Works now.

**Pull request closed without merging**
