### PR TITLE
Added Laurent Mpoly elem and ideals to serialization

### PR DESCRIPTION
**Pull request by antonydellavecchia**
Added Laurent Mpoly elem and ideals to serialization

### CODE REVIEW

**Comment by thofma** [comment]
A test would be nice

**Review by micjoswig — APPROVED** [review]
Code looks good to me, with one exception (which is not actually about the serialization).

@thofma The name of the type AbstractAlgebra.Generic.LaurentMPolyWrapRing does not look very OSCAR-ish. Can't that be exported as LaurentMPolyRing or such?

**Comment by lgoettgens** [comment]
> Code looks good to me, with one exception (which is not actually about the serialization).
> 
> @thofma The name of the type AbstractAlgebra.Generic.LaurentMPolyWrapRing does not look very OSCAR-ish. Can't that be exported as LaurentMPolyRing or such?

This has been discussed recently on slack. See https://oscar-system.slack.com/archives/C5B2H11BQ/p1690446806159369?thread_ts=1690446806.159369&cid=C5B2H11BQ
@joschmitt asked for the same, but the solution seems to be a lot more involved than expected (rename most of AbstractAlgebras structs and update everything downstream).

**Comment by thofma** [comment]
Just to elaborate a bit more on what @lgoettgens said. There is already a `LaurentMPolyRing`, so we cannot just rename it.

**Pull request merged**
