### PR TITLE
pbw_algebra: add opposite_algebra and right ideals

### PR DESCRIPTION
**Pull request by tthsqe12**
will require a new libsingualr-julia

### CODE REVIEW

**Comment by fingolfin** [comment]
So, who will update libsingular-julia? Didn't @YueRen want to do that?

**Comment by YueRen** [comment]
> So, who will update libsingular-julia? Didn't @YueRen want to do that?

True, I will look into it on Thursday.

**Comment by tthsqe12** [comment]
Your next step is 3 on https://github.com/oscar-system/Singular.jl/blob/master/README.maintainer.md#updating-the-singular-kernel
I would just like to point out that the next libsingular_julia should contain the latest master commits; ping me on the yggdrasil pr, and I will check it.

**Comment by tthsqe12** [comment]
@wdecker could you just make sure the added tests look sensible?
https://github.com/tthsqe12/Oscar.jl/blob/f6cdc388964c18cbee45b5b7dedc271096c10423/test/Rings/PBWAlgebra-test.jl#L72-L104

**Comment by tthsqe12** [comment]
going to add a little bit more functionality

**Comment by tthsqe12** [comment]
@wdecker for Weyl algebras, I think we can (roughly) say that:
left ideal addition <=> intersection of subspaces of functions
left ideal intersection <=> addition of subspaces of functions

It at least works in this example:
`<dx>` has solutions `any constant wrt y`
`<dy>` has solutions `any constant wrt x`
`<dx> + <dy> = <dx, dy>` has solutions `any constant (wrt x and y)`
`intersect(<dx>, <dy>) = <dx*dy>` has solutions of the form `any constant wrt x + any constant wrt y`

**Review by wdecker — APPROVED** [review]
Good to go!

**Pull request merged**
