### PR TITLE
Milnor

### PR DESCRIPTION
**Pull request by afkafkafk13**
first steps toward hypersurface and complete intersection germs 
- types
- construtors
- first application: Milnor number

still draft: documentation and tests still to come

### CODE REVIEW

**Comment by fingolfin** [comment]
Since this is `experimental` anyway, is it necessary to wait for documentation and tests? You just increase the risk of merge conflicts as this ages, right?

**Comment by afkafkafk13** [comment]
> Since this is `experimental` anyway, is it necessary to wait for documentation and tests? You just increase the risk of merge conflicts as this ages, right?

I had not been able to merge this before the coding sprint (and have been away from my computer for the last 2 weeks) so that I am only now picking up the PR again. I hope to merge by the end of the week (including documentation and tests).

**Comment by afkafkafk13** [comment]
to be reopened

**Comment by afkafkafk13** [comment]
Obsoleted by #2860

**Pull request closed without merging**
