### PR TITLE
Some renaming & avoid running doctests on two different CI jobs

### PR DESCRIPTION
**Pull request by fingolfin**

### CODE REVIEW

**Comment by benlorenz** [comment]
This would remove the doctests from the coverage measurement, which might not even be that bad, as I would prefer to have everything covered by proper tests. But coverage will probably drop a bit, I am somewhat interested in how much.

And it would remove macOS from the doctests, maybe we can add macOS to the docs job here but run the deploy step only on ubuntu (currently it is in the same actions step as the build but maybe we can add a flag for that)?

**Comment by thofma** [comment]
Yes, this is the question. Are you proposing to not count the doctests towards coverage @fingolfin? I know that some people only write doctests and no tests.

**Comment by simonbrandhorst** [comment]
Why should doctests not be proper tests? I think they should count for coverage, e.g. for the show methods.

**Comment by benlorenz** [comment]
> Why should doctests not be proper tests? I think they should count for coverage, e.g. for the show methods.

For the show methods it does make sense.
For other code having only doctests means that it is only run with julia 1.6 and not with any more recent version.

**Comment by lgoettgens** [comment]
Just for reference, this has been suggested in https://github.com/oscar-system/Oscar.jl/issues/1929#issuecomment-1489284942.

**Comment by fingolfin** [comment]
I did not realize that this removes doctests from coverage computations, so that was not an intended side effect.

I am relatively open either way, i.e.:
1. dropping the coverage intentionally
2. keeping it by not applying this PR
3. keeping it by applying this PR after augmnting it to enable coverage tracking for the documentation CI workflow

The argument by @benlorenz as to why 1. might even be a good thing has some merit. Unfortunately, I don't see how we could use doctest to get coverage "only for `show` methods".

On the other hand, in practice it is relatively rare for us to get failures that affects only some Julia versions; and when they happen, then usually it relates to our bridges to GAP/Polymake/Singular. I don't recall any issues of that kind that would have been found by doctests only (then again, such issues might already be there, and we don't know about them yet, precisely because we don't run doctests...)

In an ideal world, yes, we'd also test everything in a regular test world, but that seems like a lot of effort for a relatively small gain?
(Side note: I wish I had a way to specify `@test`s for a function right next to its code, instead of artificially placing it into some file in `test/`)

I'd be more interested to find out if it would be possible to have the doctests run in e.g. Julia 1.7, 1.8 and 1.9 simultaneously ... or maybe 1.8+1.9 ... or are there really differences between *each* Julia version in our printing? One would hope that some of these things might eventually stabilize...

**Pull request closed without merging**
