### PR TITLE
uses Int instead of UUIDs for backref ids

### LINKED ISSUE #1340: Serialization: why do we store UUIDs to implement backreferences
A minor question:

We (@fieker and me) were wondering why the serialization format uses UUIDs to implement backreferences (which are rather big and slow), instead of the "traditional" approach, which would be to just use an incrementing positive integer (1, 2, 3, ...). We can speculate a bit, but it'd be nice if this was either documented somewhere (a simple code comment in one of the .jl files would be fine by me). Or else the code be changed to the more light weight approach.

### PR DESCRIPTION
**Pull request by antonydellavecchia**
Changing from UUID to Ints for backref will produce smaller files. 

previously we had 

```
julia> L = ones(fmpz,10000)

julia> save("/home/antony/test_file.json", L)
760197
```

with the change we get 

```
julia> L = ones(fmpz,10000)

julia> save("/home/antony/test_file.json", L)
410162
```
where the output to save is the number of bytes.
If we agree that this change should be made as a first step to reduce file sizes, this would introduce a breaking change 
in the file format and an update script will need to be written.

### CODE REVIEW

**Comment by benlorenz** [comment]
If we use simple integer ids they need to stay strictly per-file and cannot be used to re-associate objects.

I think at some point we wanted to keep the possibility open to support the following: save two polynomials from one ring to two separate files and upon loading them again it should be possible to add the polynomials (to each other and to the original polynomials).

**Comment by fingolfin** [comment]
Orthogonal to this PR: how about for `fmpz` (or more generally, integers) we don't both storing a backref at all? Those should be harmless to "duplicate", as they are conceptually immutable, aren't they? Or perhaps we only store a backref if the magnitude of the fmpz is so large that it could pay off?

**Comment by antonydellavecchia** [comment]
> Orthogonal to this PR: how about for `fmpz` (or more generally, integers) we don't both storing a backref at all? Those should be harmless to "duplicate", as they are conceptually immutable, aren't they? Or perhaps we only store a backref if the magnitude of the fmpz is so large that it could pay off?

Looking at the files, specifically this example, it does seem quite funny to store a bunch of backrefs for the number 1, and so making it inefficient. I was also thinking that storing containers could be handled a bit differently, for example storing Vector{fmpz} we could just put the integers in the array and keep track of the type  and other information outside the entry, this would save a lot of space, this could be handled if we don't use backrefs for these sorts of types.

I imagine that this would already make such files much smaller, and then the example where adding backrefs could payoff might not even exist?

**Comment by antonydellavecchia** [comment]
I also think, that  this change may be diverted by first introducing a no backref policy of container{basic} types and seeing how good this is. This would probable be a better first change, since the change in this branch is breaking and it would be nice to avoid if we could (at least for now)

**Comment by fingolfin** [comment]
Yes, I agree it makes more sense to first investigate other approaches. You mention two that @fieker and me also discussed today:
1. there are more things we may not want to store backreferences for at all.. Right now we don't do it for primitive types (such as `Int`) nor for singleton types; and this check is hard coded. Perhaps we can make this more flexible, say by adding a function `type_needs_backref(::Type{T})` which for now does the current check; but one would be able to turn it off for more types... Also, perhaps we shouldn't store backrefs for "immutable" types at all? Then again, if an object is big, it might be worthwhile to store a backref after all...?
2. Looking at how `Vector{Int}` is serialized, it is indeed odd that type `Int` is stored separately for each entry... Perhaps we could use a rule like this: when serializing `Vector{T}`, then if `T` is concrete, we only need to store the type at the top level, but not in the vector entries.  Otherwise, `T` must be stored in the entries... this shouldn't be too much of a hassle because it kinda fits with our existing model for serializing vectors. (Similar rules could apply for other parametric container types).

But aren't all of these changes breaking changes? 

And do we care about backwards compatibility at this point? Do we expect people to use this for non-experimental work at this stage?

**Comment by lkastner** [comment]
> And do we care about backwards compatibility at this point? Do we expect people to use this for non-experimental work at this stage?

Even if we don't care, wouldn't it be a good idea to use this as an "exercise"?

**Comment by fingolfin** [comment]
@lkastner agreed

**Comment by antonydellavecchia** [comment]
no longer relevant , for now

**Pull request closed without merging**
