### PR TITLE
Some more changes for the book

### PR DESCRIPTION
**Pull request by HechtiDerLachs**
This is for cleaning up our joint chapter with @simonbrandhorst .

### CODE REVIEW

**Review by simonbrandhorst — APPROVED** [review]

**Comment by HechtiDerLachs** [comment]
Tests fail and look pretty bad. Does anyone know, what's going on? 

@benlorenz

**Comment by benlorenz** [comment]
So far only ubuntu+1.10+long failed and this is the same as reported in #3184.

**Comment by HechtiDerLachs** [comment]
> So far only ubuntu+1.10+long failed and this is the same as reported in #3184.

Alright! Thanks for having a look!

**Comment by benlorenz** [comment]
Regarding the macos failures: we added a workaround in #3203, but this is not yet included in the merge commit for this PR, so we can ignore these for now.

**Pull request merged**
