### PR TITLE
Fix some seemingly broken functionality for zero modules.

### PR DESCRIPTION
**Pull request by HechtiDerLachs**
This should fix some bugs and missing functionality I encountered when playing with the modules.

### CODE REVIEW

**Comment by HechtiDerLachs** [comment]
@jankoboehm @AlexD97 : Can you patch this to your local repo? I would like to discuss the functionality for direct sums at some point.

**Comment by fingolfin** [comment]
If this is a fix, what was the bug? It'd be nice if there was a test case verifying/demonstrating the bug fix.

**Comment by HechtiDerLachs** [comment]
Yes, that's true. Sorry, I'm still learning how to provide reasonable patches, so thanks for the info. 

Let me at least try to remember: 

* One thing was that the `-(f::ModuleHomomorphism)` operator was missing. 
* Next, there was some issue with the composition of maps M -> N -> P when N = 0 was the zero module. Whenever I had two such compositions, say g*f and a*b, then g*f + a*b would throw an error. I didn't really get what was going wrong, but also didn't care very much after I found out that with my modifications to the code things simply worked out. 
* Last, I wanted to have a method for direct sums which does not only return the object itself, but also the associated maps. This should probably be debated in a broader sense. From what I saw in the code it was just not clear to me how to obtain these maps in a systematic way. But @wdecker told me that this had been successfully addressed somewhere else already, so maybe my 'fix' is not that useful for this particular aspect.

**Comment by AlexD97** [comment]
The problem was not with composition, but just that + for SubQuoHom was missing.

**Pull request closed without merging**
