### PR TITLE
add vdim(::MPolyIdeal)

### PR DESCRIPTION
**Pull request by tthsqe12**
@AlexD97 @jankoboehm I made a silly mistake in my example. No problems here.

### CODE REVIEW

**Comment by thofma** [comment]
Can we please have a better name?

**Comment by wdecker** [comment]
@thofma We have already `dim` for Krull dimension. So why not `vdim` for vector space dimension? Or, do you want to change `dim`, too?

**Comment by thofma** [comment]
All is good.

**Comment by fieker** [comment]
On Thu, Nov 24, 2022 at 06:03:57AM -0800, Wolfram Decker wrote:
> @thofma We have already `dim` for Krull dimension. So why not `vdim` for vector space dimension? Or, do you want to change `dim`, too?
> 
we have s.th. for vector spaces alread as well.... dim
Math is inconsistent.
but this seems to be a dim (of a vector space) that has not been
constructed yet, thus no natural name is possible.
Also, if vdim(I) = vector_space_dim(quo(R, I)) then this is even for a more
remote object...

**Comment by wdecker** [comment]
@tthsqe12 : I think, @thofma is right here: We should rather implement `vdim` as `vdim(A::MPolyQuo)` and change the docu text accordingly. I am sorry for the inconvenience.

**Comment by wdecker** [comment]
Would that do the job? Do we need to assert that we work over a field?

@doc Markdown.doc"""
    vdim(A::MPolyQuo)

If, say, $A = R/I$, where $R$ is a multivariate polynomial ring over a field $K$, and $I$ is an ideal of $R$, return the dimension of $A$ as a $K$-vector space if  $I$ is zero-dimensional (otherwise, return $-1$).
"""
function vdim(A::MPolyQuo)
  I = A.I
  G = groebner_assure(I)
  singular_assure(G)
  return Singular.vdim(G.S)
end

**Review by wdecker — APPROVED** [review]

**Pull request merged**
