### PR TITLE
Fundamental invariants

### PR DESCRIPTION
**Pull request by joschmitt**
I implemented King's algorithm for the computation of fundamental invariants directly in Julia. My impression is that this is about twice as fast as the implementation in Singular. However, the runtime is heavily dominated by the evaluation of the Reynolds operator, so this would be a good starting point for future optimisation.
With this I could now remove all Singular.LibFinvar wrappers but the one `primary_invariants` method we decided to keep as it provides another algorithm.

This is in general good to go, but there are some things I want to mention/discuss:
* I wrote a function to compute degree truncated Gröbner bases, but if this should be available for the user, somebody who knows about Gröbner bases (and their interface in OSCAR) should integrate this in the corresponding functionality. That is to say: I have everything I need for my purposes right now, but probably nobody else will find it.
* There is a Singular function `kbase` which should be properly wrapped in OSCAR. Or maybe reimplemented? I'm not sure whether there is a deep algorithm behind this.
* How hard is it to decide whether a given matrix group is cyclic? If this is easy, we would get somewhat better bounds for the degrees of fundamental invariants, which makes the algorithm potentially faster.

### CODE REVIEW

**Comment by fingolfin** [comment]
Cool! Some remarks:
- just talked to Wolfram who told me that access to (his) old `primary_invariants` code is not needed (unless perhaps if you know cases where it is better somehow?)
- "degree truncated Gröbner bases" -- can't really comment, but yeah, the "Commutative Algebra people" should take a look at that. Perhaps you can open an issue requesting this?
- `kbase`: this computes a basis of the quotient space, if it is finite dimensional. AFAIK there is nothing clever to be done here: one just takes the collection of all monomials not divisible by `lm(g)`, where `g` ranges over the Gröbner basis. I would imagine that it can be efficiently reimplemented in pure Julia
- there is an alternative Reynolds operator implemented by @fieker in [`examples/Reynolds.jl`](https://github.com/oscar-system/Oscar.jl/blob/master/examples/Reynolds.jl) which should (?) be faster for large groups. Perhaps you can give it a try. Feel free to move it into `experimental/InvariantTheory/` (and perhaps we should start thinking about promoting  *that* to `src/InvariantTheory/` ?)
- "How hard is it to decide whether a given matrix group is cyclic" -- depends a bit on what you mean. Do you assume the groups is finite (I guess so...?) And: Before or after we computed an isomorphic GAP group? In the latter case, it should be very efficient. In the former case, one could implement something based on the minimal polynomials of the generators (roughly: take one of the minimal polynomials of largest degree; test that all other minpolys divide it (otherwise can't be cyclic); then we can compute in one of various ways, e.g. one can compute the order of the matrices using the minpolys, and then the rest is trivial)

**Comment by joschmitt** [comment]
Thanks for the feedback.
I removed the Singular primary invariants now and added the check for cyclic groups (this happens after an isomorphic GAP group is constructed as we need the order of the group anyway).
I leave the groebner bases and `kbase` to the respective experts (at least for now). I reopened my groebner basis issue #1430 .
Regarding the Reynolds operator: I check this approximation method, but not in this PR. I just wanted to point out that in general a good starting point for optimisation would be making the Reynolds operator better than just adding all the elements.

And because you mentioned it: I think that `InvariantTheory` could move into `src`. It is at least not experimental in the sense of "the user interface might change" any more.

**Comment by wdecker** [comment]
From my point of view this is good to go as soon as the tests will pass. I strongly support to move this to `src`.

**Comment by thofma** [comment]
There is something off with the doctests (which is not your fault it seems). I am also in favour of moving this to `src` in a followup PR.

**Comment by thofma** [comment]
Do you want to add a test for the cyclic case? It seems to not be covered.

**Pull request merged**
