### PR TITLE
Towards knots

### PR DESCRIPTION
**Pull request by fieker**
When run, the following will produce a nice Gap problem:
```
using Oscar
Oscar.example("H2.jl")
A = abelian_group(PermGroup, [2,2])
B = [sub(A, [A[1]])[1], sub(A, [A[2]])[1]]
Main.H2_G_QmodZ_mod.H2_G_QmodZ_kern_restriction(A, B)
```
namely:
```
julia> Main.H2_G_QmodZ_mod.H2_G_QmodZ_kern_restriction(A, B)
ERROR: AssertionError: GAP.Globals.HasIsWholeFamily(G.X) && GAPWrap.IsWholeFamily(G.X)
Stacktrace:
 [1] quo(G::FPGroup, elements::Vector{FPGroupElem})
   @ Oscar ~/.julia/dev/Oscar/src/Groups/sub.jl:333
```
using the "/" in Gap directly can compute the quotient...
@fingolfin , @ThomasBreuer ?

### CODE REVIEW

**Comment by fieker** [comment]
a slightly differetn versio produced:
```
julia> Main.H2_G_QmodZ_mod.H2_G_QmodZ_kern_restriction(G, [x[1] for x = U])
ERROR: Not a known type of group
Stacktrace:
 [1] error(s::String)
   @ Base ./error.jl:35
 [2] _get_type(G::GAP_jll.GapObj)
   @ Oscar ~/.julia/dev/Oscar/src/Groups/types.jl:395
 [3] quo(G::FPGroup, N::FPGroup)
   @ Oscar ~/.julia/dev/Oscar/src/Groups/sub.jl:408
```
I think this was obtained by doing `quo(k, sub(k, ...)[1])`, ie. explicitly using sub first

**Comment by fieker** [comment]
when playing, one should not try this:
```
julia> [describe(Main.H2_G_QmodZ_mod.H2_G_QmodZ(transitive_group(8, i))) for i=1:22]
ERROR: Error thrown by GAP: Error, no method found! For debugging hints type ?Recovery from NoMethodFound
Error, no 1st choice method found for `RelatorsOfFpGroup' on 1 arguments at /home/fieker/.julia/artifacts/70f7ea74308ce9d94343b89b97f71ce69490cf51/share/gap/lib/methsel2.g:249 called from
<function "HANDLE_METHOD_NOT_FOUND">( <arguments> )
 called from read-eval loop at *defin*:0

Stacktrace:
  [1] error(s::String)
    @ Base ./error.jl:35
  [2] ThrowObserver(depth::Int32)
    @ GAP ~/.julia/dev/GAP/src/GAP.jl:88
  [3] _call_gap_func(func::GAP_jll.GapObj, a1::GAP_jll.GapObj)
    @ GAP ~/.julia/dev/GAP/src/ccalls.jl:258
  [4] call_gap_func_nokw
    @ ~/.julia/dev/GAP/src/ccalls.jl:224 [inlined]
  [5] GapObj
    @ ~/.julia/dev/GAP/src/ccalls.jl:235 [inlined]
  [6] RelatorsOfFpGroup
    @ ~/.julia/dev/Oscar/src/GAP/wrappers.jl:371 [inlined]
  [7] relators(G::FPGroup)
    @ Oscar ~/.julia/dev/Oscar/src/Groups/GAPGroups.jl:1475
  [8] describe(G::FPGroup)
    @ Oscar ~/.julia/dev/Oscar/src/Groups/GAPGroups.jl:1849
  [9] (::var"#65#66")(i::Int64)
```

**Comment by fieker** [comment]
(this is from i==1, the group is trivial (order() returns 1, but describe is unhappy)

**Comment by ThomasBreuer** [comment]
The current situation with quotient groups of finitely presented groups in GAP is as follows.
If `G`  is a full free group or a full finitely presented group (i.e., not a subgroup of this full group) then one can form the quotient of `G` by the normal closure of a given set of elements of `G`.
For subgroups of such full groups, GAP either issues an error or returns some object. In the case of subgroups of free groups, a returned object is corrupted, that is why I had added the assertion on the Oscar side. (See also gap-system/gap/issues/4897 for a change that improves this situation.)
In the current example, the subgroup of an f.p. group shall be factored by an empty list, and apparently GAP has some applicable method for that; however, I fear that this is a bug in GAP because this is a method for semigroups. In any case, the object returned by GAP is not a group in the sense of GAP, in particular it cannot be turned into an Oscar group, hence the `Not a known type of group` error on the Oscar side.

**Comment by fingolfin** [comment]
Is the file `examples/GaloisLattice.jl` removed intentionally?

Should we merge this PR now?

**Comment by fieker** [comment]
On Thu, Jan 19, 2023 at 02:42:45PM -0800, Max Horn wrote:
> Is the file `examples/GaloisLattice.jl` removed intentionally?
Yes
> 
> Should we merge this PR now?
probably _ I haven't looked at it in a while

**Comment by thofma** [comment]
This now needs a rebase

**Comment by fieker** [comment]
too much git-fu required. I am happy to remove this PR as the change is a one-liner in examples...

**Comment by fingolfin** [comment]
On current master, I get this (no error, and w/o the patch in this PR):
```
julia> Oscar.example("H2.jl")
Main.H2_G_QmodZ_mod

julia> A = abelian_group(PermGroup, [2,2])
Group([ (1,2), (3,4) ])

julia> B = [sub(A, [A[1]])[1], sub(A, [A[2]])[1]]
2-element Vector{PermGroup}:
 Group([ (1,2) ])
 Group([ (3,4) ])

julia> Main.H2_G_QmodZ_mod.H2_G_QmodZ_kern_restriction(A, B)
(Group([ <identity ...>, (F2*F1)^2, <identity ...> ]), Group homomorphism from
Group([ <identity ...>, (F2*F1)^2, <identity ...> ])
to
Group([ <identity ...>, (F2*F1)^2, <identity ...> ]))
```
Note that this returns a tuple, while the version in this patch just returns the group from the first tuple entry.

Anyway, I think this means this PR is not needed?

**Comment by fieker** [comment]
On Mon, Jan 30, 2023 at 02:56:44AM -0800, Max Horn wrote:
> On current master, I get this (no error, and w/o the patch in this PR):
> ```
> julia> Oscar.example("H2.jl")
> Main.H2_G_QmodZ_mod
> 
> julia> A = abelian_group(PermGroup, [2,2])
> Group([ (1,2), (3,4) ])
> 
> julia> B = [sub(A, [A[1]])[1], sub(A, [A[2]])[1]]
> 2-element Vector{PermGroup}:
>  Group([ (1,2) ])
>  Group([ (3,4) ])
> 
> julia> Main.H2_G_QmodZ_mod.H2_G_QmodZ_kern_restriction(A, B)
> (Group([ <identity ...>, (F2*F1)^2, <identity ...> ]), Group homomorphism from
> Group([ <identity ...>, (F2*F1)^2, <identity ...> ])
> to
> Group([ <identity ...>, (F2*F1)^2, <identity ...> ]))
> ```
> Note that this returns a tuple, while the version in this patch just returns the group from the first tuple entry.
> 
> Anyway, I think this means this PR is not needed?
> 
Quite likely - I shall remove it

**Comment by ThomasBreuer** [comment]
The reported problem with `quo` had been solved with pull request #1837. As I had said above, using GAP's `\/` directly yields a result on the GAP side that cannot be used by Oscar.
Thus it was the right solution to close this pull request without merging it.

**Pull request closed without merging**
