### PR TITLE
JA homogenizer

### PR DESCRIPTION
**Pull request by JohnAAbbott**
First round of improvements after feedback via GitHub

### CODE REVIEW

**Comment by JohnAAbbott** [comment]
**QUICK QUESTION**  should I remove the old interface (namely the function `homogenization`)?

**Comment by wdecker** [comment]
Please remove the old interface.

**Comment by JohnAAbbott** [comment]
I have just pushed the revised implementation.
Updated: doc, tests, calls to homogenization in other people's code.  Removed old implementation.
I hope this is practically final now.

**Comment by fieker** [comment]
@HechtiDerLachs  will review (and APPROVE) it

**Review by HechtiDerLachs — APPROVED** [review]
If it works, it's good enough for me. Code seems to follow most conventions now. Type parametrization is still missing, but also not super important. 

It looks like more of the old tests were deleted than new ones added. If this is the case: Is it possible to convert more of the old tests into tests for the new implementation?

**Pull request merged**
