### PR TITLE
Fix #403

### LINKED ISSUE #403: Weird behaviour with all latest masters [maybe Oscar.Integer should be the same as Base.Integer]
So I have everything dev'd and at the latest masters. I don't understand why Hecke's definition of ^ (https://github.com/thofma/Hecke.jl/blob/master/src/Misc/Integer.jl#L1476) is being used instead of oscar's (https://github.com/oscar-system/Oscar.jl/blob/master/src/Rings/MPolyQuo.jl#L206). I am just posting this here to see if others can reproduce it/offer ideas.
```julia
$ julia
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.6.0-rc1 (2021-02-06)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

(@v1.6) pkg> status
      Status `~/.julia/environments/v1.6/Project.toml`
  [c3fe647b] AbstractAlgebra v0.15.1 `~/.julia/dev/AbstractAlgebra`
  [1f15a43c] CxxWrap v0.11.2
  [e30172f5] Documenter v0.26.3
  [3e1990a7] Hecke v0.10.2 `~/.julia/dev/Hecke`
  [7073ff75] IJulia v1.23.2
  [2edaba10] Nemo v0.22.0
  [f1435218] Oscar v0.5.2-DEV `~/.julia/dev/Oscar`
  [295af30f] Revise v3.1.14
  [bcd08a7b] Singular v0.5.1 `~/.julia/dev/Singular`
  [2913bbd2] StatsBase v0.33.4
  [43d676ae] Singular_jll v402.0.104+0
  [9a3f8284] Random
  [8dfed614] Test

julia> using Oscar
[ Info: Precompiling Oscar [f1435218-dba5-11e9-1e4d-f1a5fab5fc13]
WARNING: Method definition PolynomialRing##kw(Any, typeof(AbstractAlgebra.PolynomialRing), AbstractAlgebra.Ring, Int64, String) in module AbstractAlgebra at /home/schultz/.julia/dev/AbstractAlgebra/src/AbstractAlgebra.jl:724 overwritten in module Hecke at /home/schultz/.julia/dev/Hecke/src/Misc/MPoly.jl:7.
  ** incremental compilation may be fatally broken for this module **

WARNING: Method definition PolynomialRing##kw(Any, typeof(AbstractAlgebra.PolynomialRing), AbstractAlgebra.Ring, Int64) in module AbstractAlgebra at /home/schultz/.julia/dev/AbstractAlgebra/src/AbstractAlgebra.jl:724 overwritten in module Hecke at /home/schultz/.julia/dev/Hecke/src/Misc/MPoly.jl:7.
  ** incremental compilation may be fatally broken for this module **

WARNING: Method definition PolynomialRing(AbstractAlgebra.Ring, Int64, String) in module AbstractAlgebra at /home/schultz/.julia/dev/AbstractAlgebra/src/AbstractAlgebra.jl:724 overwritten in module Hecke at /home/schultz/.julia/dev/Hecke/src/Misc/MPoly.jl:7.
  ** incremental compilation may be fatally broken for this module **

WARNING: Method definition PolynomialRing(AbstractAlgebra.Ring, Int64) in module AbstractAlgebra at /home/schultz/.julia/dev/AbstractAlgebra/src/AbstractAlgebra.jl:724 overwritten in module Hecke at /home/schultz/.julia/dev/Hecke/src/Misc/MPoly.jl:7.
  ** incremental compilation may be fatally broken for this module **

 -----    -----    -----      -      -----   
|     |  |     |  |     |    | |    |     |  
|     |  |        |         |   |   |     |  
|     |   -----   |        |     |  |-----   
|     |        |  |        |-----|  |   |    
|     |  |     |  |     |  |     |  |    |   
 -----    -----    -----   -     -  -     -  

...combining (and extending) ANTIC, GAP, Polymake and Singular
Version 0.5.2-DEV ... 
 ... which comes with absolutely no warranty whatsoever
Type: '?Oscar' for more information
(c) 2019-2021 by The Oscar Development Team

julia> R, (x, y, z) = PolynomialRing(QQ, ["x", "y", "z"])
(Multivariate Polynomial Ring in x, y, z over Rational Field, fmpq_mpoly[x, y, z])

julia> Q, _ = quo(R, x^2 - y^2)
(Quotient of Multivariate Polynomial Ring in x, y, z over Rational Field by ideal generated by: x^2 - y^2, Map from
Multivariate Polynomial Ring in x, y, z over Rational Field to Q defined by a julia-function with inverse
)

julia> (x, y, z) = gens(Q)
3-element Vector{Oscar.MPolyQuoElem{fmpq_mpoly}}:
 x
 y
 z

julia> x^2
ERROR: StackOverflowError:
Stacktrace:
     [1] _generic_power(a::Oscar.MPolyQuoElem{fmpq_mpoly}, n::Int64)
       @ Hecke ~/.julia/dev/Hecke/src/Misc/Integer.jl:1483
     [2] ^(a::Oscar.MPolyQuoElem{fmpq_mpoly}, n::Int64)
       @ Hecke ~/.julia/dev/Hecke/src/Misc/Integer.jl:1476
--- the last 2 lines are repeated 39990 more times ---
 [79983] _generic_power(a::Oscar.MPolyQuoElem{fmpq_mpoly}, n::Int64)
       @ Hecke ~/.julia/dev/Hecke/src/Misc/Integer.jl:1483
```

### PR DESCRIPTION
**Pull request by thofma**

### CODE REVIEW

**Comment by thofma** [comment]
@fingolfin I thought that CI is running the tests on a merge with master?

**Comment by thofma** [comment]
@fingolfin I thought that CI is running the tests on a merge with master?

**Comment by thofma** [comment]
@fingolfin I thought that CI is running the tests on a merge with master?

**Comment by fingolfin** [comment]
@thofma it should, but the question is when it regenerates that merge -- in the past closing and re-opening the issue caused it to redo the "virtual" merge against the latest master HEAD. No more, it seems? Anyway, I'll just merge it, as the failures are clearly resolved in reality.

**Pull request merged**
