### PR TITLE
Add IntegerUnion

### PR DESCRIPTION
**Pull request by fingolfin**

### CODE REVIEW

**Comment by fingolfin** [comment]
Hmm, it seems the Julia 1.7 and nightly tests are failing due to something in Polymake? @benlorenz @lkastner any idea?

**Comment by benlorenz** [comment]
Yeah, this is because two merges in Yggdrasil (https://github.com/JuliaPackaging/Yggdrasil/pull/3609 + https://github.com/JuliaPackaging/Yggdrasil/pull/3610) are still open and 1.7 is currently using the 1.5 binaries currently.

**Comment by fingolfin** [comment]
@benlorenz https://github.com/JuliaPackaging/Yggdrasil/pull/3609 was merged, can you mark https://github.com/JuliaPackaging/Yggdrasil/pull/3610 as "ready for review" (i.e. remove the "draft" flag)?

**Comment by benlorenz** [comment]
> @benlorenz [JuliaPackaging/Yggdrasil#3609](https://github.com/JuliaPackaging/Yggdrasil/pull/3609) was merged, can you mark [JuliaPackaging/Yggdrasil#3610](https://github.com/JuliaPackaging/Yggdrasil/pull/3610) as "ready for review" (i.e. remove the "draft" flag)?

done, and requested the final merge. Do merges for 1.7 binaries still need manual intervention in the registry?

**Pull request merged**
