### PR TITLE
Bump to 0.11.1

### PR DESCRIPTION
**Pull request by thofma**
Since OSCAR 0.11, there has been a version bump in Hecke from 0.15 to 0.16. So I would like to release OSCAR 0.11.1 to make it not lag behind.

### CODE REVIEW

**Comment by fingolfin** [comment]
also good for GAP

**Review by fingolfin — APPROVED** [review]

**Review by fingolfin — CHANGES_REQUESTED** [review]
Please use the `etc/update_version.sh` script to ensure the version is updated in all places it appears.

**Comment by thofma** [comment]
ah uups, thanks for the reminder

**Comment by thofma** [comment]
done

**Review by fingolfin — APPROVED** [review]

**Comment by thofma** [comment]
Hm, the doctests errors look rather strange, happening because the `save` command returns something different. Are these real errors @benlorenz @antonydellavecchia?

I am inclined to suppress the output via `;` in the doctest.

**Comment by benlorenz** [comment]
I think the number indicates the number of bytes written, and that includes the full version information in the file, and the change `"prerelease": ["DEV"]` to `"prerelease": []` does fit to the five bytes difference.
I would suggest that we drop that return value directly in the save function.

**Comment by thofma** [comment]
Yes, that makes sense. For now I have decorated those `save` calls with `;` to unblock this PR.

**Pull request merged**
