### PR TITLE
use new function Singular.LibNormal.isNormal

### PR DESCRIPTION
**Pull request by tthsqe12**
maybe should wait for https://github.com/oscar-system/Oscar.jl/pull/1244 so I can use coefficient_ring

### CODE REVIEW

**Review by fingolfin — APPROVED** [review]
Looks good to me although indeed one might want to wait for PR #1244 and use that in here...

**Review by wdecker — COMMENTED** [review]
@tthsqe12 
!!! warning
    The function computes the normalization of `A`. This may take some time.
This function may be more efficient than computing the full normalization of `A`.
"""
I suggest the following change:

!!! note
    This function performs the first step of the normalization algorithm of Greuel, Laplagne, and Seelisch [GLS10](@cite) and may, thus, be more efficient than computing the full normalization of `A`.

**Comment by tthsqe12** [comment]
Ok, I will change it in the next commit.

**Comment by fingolfin** [comment]
PR #1244 was merged so you can also updated accordingly

**Pull request merged**
