### PR TITLE
fix prining of QabElem

### LINKED ISSUE #552: Printing roots of unity
Writing elements of the abelian closure of QQ looks horrible:
```
julia> binomial_primary_decomposition(I)
3-element Array{Tuple{MPolyIdeal{AbstractAlgebra.Generic.MPoly{Oscar.QabModule.QabElem}},MPolyIdeal{AbstractAlgebra.Generic.MPoly{Oscar.QabModule.QabElem}}},1}:
 (ideal generated by: x1 + -1 in Q(z_1)*x2, x1^3 + -1 in Q(z_1), x2^2*x3 + -1 in Q(z_1)*x3, x3, x2 + -z_3 in Q(z_3), x1 + -z_3 in Q(z_3), ideal generated by: x1*x2^2 + -1 in Q(z_1), x2 + -z_3 in Q(z_3), x3)
 (ideal generated by: x1 + -1 in Q(z_1)*x2, x1^3 + -1 in Q(z_1), x2^2*x3 + -1 in Q(z_1)*x3, x3, x2 + (z_3 + 1 in Q(z_3)), x1 + (z_3 + 1 in Q(z_3)), ideal generated by: x1*x2^2 + -1 in Q(z_1), x2 + (z_3 + 1 in Q(z_3)), x3)
 (ideal generated by: x2 + -1 in Q(z_1), x1 + -1 in Q(z_1), x1*x2 + -1 in Q(z_1), ideal generated by: x2 + -1 in Q(z_1), x1 + -1 in Q(z_1), x1*x2 + -1 in Q(z_1))
```
Two questions to start a discussion:
1. Isn't -1 in Q(z_1) just -1?
2. Can I print (z_3 + 1 in Q(z_3)) by introducing a greek letter such as \zeta_3: (\zeta_3+1)

### PR DESCRIPTION
**Pull request by tthsqe12**
fixes #552  now it prints the "... in Q(z_n)" only when printed in isolation and does the "correct" thing when trying to compose with other printing.
```julia
julia> Oscar.binomial_primary_decomposition(I)
5-element Vector{Tuple{MPolyIdeal{AbstractAlgebra.Generic.MPoly{Oscar.QabModule.QabElem}}, MPolyIdeal{AbstractAlgebra.Generic.MPoly{Oscar.QabModule.QabElem}}}}:
 (ideal generated by: x1^2*x3^2 - x2^2*x3^2, x1^4*x3 - x2^4*x3, x3^3, x3, x3^2, ideal generated by: x3)
 (ideal generated by: x1^2*x3^2 - x2^2*x3^2, x1^4*x3 - x2^4*x3, x3^3, x1 - x2, ideal generated by: x1 - x2, x3)
 (ideal generated by: x1 - z_4*x2, x3^2, ideal generated by: x1 - z_4*x2, x3)
 (ideal generated by: x1^2*x3^2 - x2^2*x3^2, x1^4*x3 - x2^4*x3, x3^3, x1 + x2, ideal generated by: x1 + x2, x3)
 (ideal generated by: x1 + z_4*x2, x3^2, ideal generated by: x1 + z_4*x2, x3)

julia> collect(coefficients(gens(ans[end][1])[1]))
2-element Vector{Oscar.QabModule.QabElem}:
 1 in Q(z_1)
 z_4 in Q(z_4)
```

### CODE REVIEW

**Comment by thofma** [comment]
Improves the status quo, so why not. But you have to adjust the documentation (needs to be done with 1.5).

**Comment by wdecker** [comment]
I am still wondering whether it makes sense to use the greek letter \zeta for z. Can we have a short discussion on that?

**Comment by thofma** [comment]
Chances are high that there is a setup which cannot print it properly.

Changes are even higher that people have no idea how to enter it (although this might not be a problem here).

PS.: Developing by copy pasting strings is no fun. I don't even know if @tthsqe12 knows how to enter it in his fancy editor.

**Comment by thofma** [comment]
I am merging this as is, since it improves the status quo. I am currently working on improving it further.

**Pull request merged**
