### PR TITLE
add `map_word` for `PcGroupElem`

### PR DESCRIPTION
**Pull request by ThomasBreuer**
addresses #3468 

There is still a problem with the requirements for `gens` of pc groups (corresponding to the generators of the underlying presentation) and `gens` of abelian groups (corresponding to the given orders of cyclic factors):
`abelian_group([2,3,4])` has 3 generators but the presentation on the GAP side has 4 generators.
Perhaps we have to use GAP's Pcp groups for all such groups (not just for the infinite ones).

### CODE REVIEW

**Comment by fieker** [comment]
On Thu, Feb 29, 2024 at 12:34:09PM -0800, Thomas Breuer wrote:
> addresses #3468 
> 
> There is still a problem with the requirements for `gens` of pc groups (corresponding to the generators of the underlying presentation) and `gens` of abelian groups (corresponding to the given orders of cyclic factors):
> `abelian_group([2,3,4])` has 3 generators but the presentation on the GAP side has 4 generators.
in snf, it should have only 2 gens: [2, 12] but there is no conection
between the gens as GrpAb and PcGroup thay we need to maintain.
A differnt question is if we want/ can use the more general pc where the
(relative) orders do not have to be prime.

**Comment by ThomasBreuer** [comment]
@fieker Sorry, I meant `abelian_group(PcGroup, [2,3,4])`.

And yes, my remark about GAP's Pcp groups vs. Pc groups is about the generators: Pc groups have their presentations in as many generators as the number of prime factors in the group order, Pcp groups do not.

**Comment by ThomasBreuer** [comment]
One test fails, `1.11-nightly, long, ubuntu-latest`:
```
Starting tests for /home/runner/work/Oscar.jl/Oscar.jl/test/AlgebraicGeometry/ToricVarieties/toric_schemes.jl

GC: pause 89.53ms. collected 170.920189MB. incr 
Heap stats: bytes_mapped 640.16 MB, bytes_resident 474.38 MB,
heap_size 693.25 MB, heap_target 727.91 MB, Fragmentation 0.648
[...]
GC: pause 50.47ms. collected 233.091125MB. incr 
Heap stats: bytes_mapped 832.20 MB, bytes_resident 763.00 MB,
heap_size 1008.49 MB, heap_target 1083.48 MB, Fragmentation 0.639
ERROR: LoadError: Package Oscar errored during testing (received signal: 11)
```
I restart the test.

**Comment by lgoettgens** [comment]
@ThomasBreuer if you change the "addresses https://github.com/oscar-system/Oscar.jl/issues/3468" in the PR description to "resolves https://github.com/oscar-system/Oscar.jl/issues/3468", merging this PR will automatically close the linked issue. See https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/using-keywords-in-issues-and-pull-requests#linking-a-pull-request-to-an-issue for details

**Comment by ThomasBreuer** [comment]
@lgoettgens No, I do not want to merge this pull request automatically, in particular it has not been approved yet.
(For a clean solution, I mentioned that `abelian_group(PcGroup, exponents)` should be changed to use a GAP group of type `IsPcpGroup` instead of `IsPcGroup`.)

**Comment by fieker** [comment]
That is between you @ThomasBreuer and @fingolfin . map_word as it is useful, in fact I have already stolen this into my code.
The Pc vs. Pcp is independent and MUCH harder, but completely independent of this PR .
Thus I will approve.

**Review by fieker — APPROVED** [review]

**Comment by ThomasBreuer** [comment]
I have now added an assertion that should catch problems with groups like `abelian_group(PcGroup, [2,3,4])`,
and added documentation that mentions to which vector of group elements `genimgs` corresponds.
Now the pull request may be merged (apart from one test failure in an unrelated place).

**Review by fingolfin — APPROVED** [review]

**Pull request merged**
