### PR TITLE
Add some dummy hash functions for the geometry

### PR DESCRIPTION
**Pull request by HechtiDerLachs**
See #2222

### CODE REVIEW

**Comment by HechtiDerLachs** [comment]
Seems that the tests have passed. @lgoettgens : Can we merge this? Or do I need to correct some more things?

**Review by lgoettgens — APPROVED** [review]
I have no ideas about the types here, but these hash functions are all valid (but stupid), but I may be the case that this is the best we can do here.

**Comment by lgoettgens** [comment]
If there are still things missing will probably be easier to check once this is merged by running the script from #2222 again.

**Comment by HechtiDerLachs** [comment]
> but I may be the case that this is the best we can do here.

I'm afraid so. These comparisons are all expensive and the user should know how to avoid them in the first place.

**Pull request merged**
