### PR TITLE
Support more types in `graded_polynomial_ring`

### LINKED ISSUE #2088: Support more `graded_polynomial_ring` argument variants
This works:
```julia
R, (x,y,z,u,v) = graded_polynomial_ring(GF(31991), ["x","y","z","u","v"])
```
This doesn't but should:
```julia
R, (x,y,z,u,v) = graded_polynomial_ring(GF(31991), [:x,:y,:z,:u,:v])
```
In general I think it should support all variants for specifying variables which are supported by `polynomial_ring`, shouldn't it?

(Ping @mgkurtz -- this might or might not overlap with what you are doing)

### PR DESCRIPTION
**Pull request by mgkurtz**
Now supports the same vector and tuple types like `polynomial_ring` (as of Nemocas/AbstractAlgebra.jl#1282) for the list of variable names. Fixes #2088.

### CODE REVIEW

**Comment by simonbrandhorst** [comment]
tests fail

**Review by simonbrandhorst — APPROVED** [review]
Thank you.

**Comment by mgkurtz** [comment]
The doctest (and thus also Julia 1.6 test) failure is due to creating polynomial rings with variables `'x':'z'` not yet released in AbstractAlgebra. (Supported as of Nemocas/AbstractAlgebra.jl#1282.) If this is the only problem, I will replace that doctest by a more casual one.

**Comment by fingolfin** [comment]
```
┌ Error: reference for '`polynomial_ring(C, [:x])`' could not be found in src/CommutativeAlgebra/rings.md.
└ @ Documenter.CrossReferences ~/.julia/packages/Documenter/H5y27/src/Utilities/Utilities.jl:32
```

**Pull request merged**
