### PR TITLE
doctest_fix: try setting fixed default terminal size

### PR DESCRIPTION
**Pull request by benlorenz**
These should be the correct defaults, I tried this with a few functions and it did not modify the output.
Would be great if someone else could try as well!

cc: @HechtiDerLachs

### CODE REVIEW

**Review by fingolfin — APPROVED** [review]
Good idea and seems sensible to me, but I have not (yet) tested it myself.

**Comment by joschmitt** [comment]
I just tried this and `Oscar.build_doc(doctest = :fix)` still produces changes like this for me:
```
--- a/experimental/FTheoryTools/src/AbstractFTheoryModels/attributes.jl
+++ b/experimental/FTheoryTools/src/AbstractFTheoryModels/attributes.jl
@@ -1677,7 +1677,8 @@ julia> components_of_dual_graph(qsm_model)
  "C7"
  "C8"
  "C9"
- ⋮
+ "C13"
+ "C14"
  "C16"
  "C17"
  "C21"
```
(It also adds stacktraces to several intentional errors.)

**Comment by benlorenz** [comment]
> I just tried this and `Oscar.build_doc(doctest = :fix)` still produces changes like this for me:
> 
> ```
> --- a/experimental/FTheoryTools/src/AbstractFTheoryModels/attributes.jl
> +++ b/experimental/FTheoryTools/src/AbstractFTheoryModels/attributes.jl
> @@ -1677,7 +1677,8 @@ julia> components_of_dual_graph(qsm_model)
>   "C7"
>   "C8"
>   "C9"
> - ⋮
> + "C13"
> + "C14"
>   "C16"
>   "C17"
>   "C21"
> ```
> 
> (It also adds stacktraces to several intentional errors.)

I only touched the `Oscar.doctest_fix` function and not `build_doc`, but I guess that would also make sense. Not sure if we can do anything about the stacktraces.

**Comment by joschmitt** [comment]
> > I just tried this and `Oscar.build_doc(doctest = :fix)` still produces changes like this for me:
> > ```
> > --- a/experimental/FTheoryTools/src/AbstractFTheoryModels/attributes.jl
> > +++ b/experimental/FTheoryTools/src/AbstractFTheoryModels/attributes.jl
> > @@ -1677,7 +1677,8 @@ julia> components_of_dual_graph(qsm_model)
> >   "C7"
> >   "C8"
> >   "C9"
> > - ⋮
> > + "C13"
> > + "C14"
> >   "C16"
> >   "C17"
> >   "C21"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > (It also adds stacktraces to several intentional errors.)
> 
> I only touched the `Oscar.doctest_fix` function and not `build_doc`, but I guess that would also make sense. Not sure if we can do anything about the stacktraces.

Oh, sorry, my mistake.

**Comment by joschmitt** [comment]
I can confirm that `doctest_fix` works better with this pull request.

**Comment by HechtiDerLachs** [comment]
Thank you @benlorenz ! I didn't try it, yet, but I will eventually.

**Comment by benlorenz** [comment]
I added the environment variables to build_doc as well. Running the whole docs with `:fix` now only caused the stacktraces to appear (which is a known documenter issue) but no other changes.

**Comment by joschmitt** [comment]
Thank you! Works on my machine.

**Review by joschmitt — APPROVED** [review]

**Pull request merged**
