### PR TITLE
Remove Base.getproperty methods for MatrixGroup(Elem) and SesquilinearForm

### PR DESCRIPTION
**Pull request by fingolfin**
Should have been done in May after PR #3671 and friends but it seems we forgot about it.

Just was cleaning out old branches locally and stumbled over this. As such I don't remember if this was 100% complete but CI will tell.

### CODE REVIEW

**Comment by thofma** [comment]
pretty please

**Review by ThomasBreuer — APPROVED** [review]
The relevant `GapObj` methods were already available, and apparently their code has been copied from the `getproperty` methods in question; no idea why the `getproperty` methods were not removed yet.

**Comment by fingolfin** [comment]
Ugh a bunch of CI tests were still failing...

**Comment by thofma** [comment]
hm, really? the button was all green for me, sorry

**Comment by thofma** [comment]
The last "More" commit has everything green for me: https://github.com/oscar-system/Oscar.jl/pull/4362/commits/ad06d4c492d8e7ffa6da974864398f949feaefb2

**Comment by thofma** [comment]
I think the display is bugged (hopefully)

**Pull request merged**
