### PR TITLE
add permutation action on `FreeAssAlgElem`s

### PR DESCRIPTION
**Pull request by ThomasBreuer**
(can be merged as soon as Nemocas/AbstractAlgebra.jl/pull/1418 is available in Oscar)

### CODE REVIEW

**Comment by thofma** [comment]
I wonder whats up with coverage.

**Comment by ThomasBreuer** [comment]
The failures look different than earlier ones (where either the job got canceled or some specific error was shown). How can I interpret the current failures?

**Comment by benlorenz** [comment]
> I wonder whats up with coverage.

> > Report is 62 commits behind head on master.
> > The diff coverage is `0.00%`.

This seems to be comparing a pretty old commit from master (base commit of this branch, 16 days ago) with the merge commit from this branch with master (since CI runs on a temporary merge)?

**Comment by benlorenz** [comment]
> The failures look different than earlier ones (where either the job got canceled or some specific error was shown). How can I interpret the current failures?

Sometimes it helps to use `View raw logs`, but in this case one of those also doesn't work. The failures for 1.10 and nightly on ubuntu can be ignored and are caused by the usual OOM issues.

**Comment by thofma** [comment]
Let's see if a rebase fixes the coverage

**Comment by thofma** [comment]
Still not working, no clue why

**Review by thofma — APPROVED** [review]

**Pull request merged**
