### PR TITLE
Better organization of algebraic geometry code (both source and documentation)

### LINKED ISSUE #1973: Algebraic geometry: Standard constructions & organization of documentation
On the OSCAR website, we have in the subsection Algebraic Geometry an entry for Standard constructions:

https://docs.oscar-system.org/stable/AlgebraicGeometry/StandardConstructions/standard_constructions/

I believe we should discuss this. Among others, the following questions come to my mind:
* This sections is very short. Maybe we could integrate it better in an existing context?
* One might argue that `projective spaces`, `blowups`, ... are also standard constructions. Maybe the name is misleading? Is `Grassmanians` maybe a better title?
* It appears that OSCAR provides no functionality for Grassmanians other than the `Grassmann Plücker Ideal`. I am not using them (as of now), but just wanted to bring this to people's attention. Are there plans to provide such functionality?

Ping @wdecker @simonbrandhorst @afkafkafk13 @HechtiDerLachs .

### PR DESCRIPTION
**Pull request by HereAround**
* Source code, documentation code and tests concerning (specialized areas of) algebraic geometry is grouped in folder `src/algebraic_geometry`, `docs/src/algebraic_geometry` and `tst/src/algebraic_geometry` respectively. (Code in experimental is *explicitly* excluded from this move).
* For the docs folder and the website to align more closely (easier to find things/maintain), I rename the section "FinitelyPresentedAlgebras" on the website into "Noncommutative Algebra".
* As discussed with @wdecker, I rename the standard constructions of algebraic geometry into miscellaneous.

~~This contains the changes in https://github.com/oscar-system/Oscar.jl/pull/1976. Once this other PR is merged (it should definitely be merged first), the required rebase should be trivial.~~

Once merged, this closes https://github.com/oscar-system/Oscar.jl/issues/1973.

### CODE REVIEW

**Comment by afkafkafk13** [comment]
This one sits on top of PR #1976 to which I already commented. I will await the merge of it and the rebase of this one before reviewing the genuine changes in this one.

**Comment by HereAround** [comment]
This needs rebasing. But I wait with this until the big renaming (https://github.com/oscar-system/Oscar.jl/pull/1982) has been merged. Hence turned into draft.

**Review by lkastner — APPROVED** [review]

**Comment by lkastner** [comment]
Please don't forget `test/`.

**Comment by afkafkafk13** [comment]
@HereAround: #1982 and #1976 are both merged. Do you want to rebase, before this PR acquires even more conflicts?

**Comment by HereAround** [comment]
> @HereAround: #1982 and #1976 are both merged. Do you want to rebase, before this PR acquires even more conflicts?

Yes, this seems like a good opportunity now. I just updated this PR.

**Comment by HereAround** [comment]
> Please don't forget `test/`.

Thank you. That is good pointer indeed. I have organized the tests in https://github.com/oscar-system/Oscar.jl/pull/1977/commits/6c774cd8c0a344380ab4d78128c6d782ceb0a356.

**Review by simonbrandhorst — APPROVED** [review]

**Review by afkafkafk13 — APPROVED** [review]

**Pull request merged**
