### PR TITLE
(re-)enable some more tests

### PR DESCRIPTION
**Pull request by benlorenz**
ref #1724

### CODE REVIEW

**Review by lkastner — APPROVED** [review]
I think we should reenable these tests. ;)

**Comment by thofma** [comment]
My bad, sorry.

**Comment by lkastner** [comment]
> My bad, sorry.

Benjamin is right. PRs can be merged much faster this way.
Probably I already have / will do something similar in the future... :/

**Review by fingolfin — APPROVED** [review]

**Comment by thofma** [comment]
I cancelled some other runs so that we can get this in here fast. I will restart the others once this is merged.

**Pull request merged**
