### PR TITLE
[FTheoryTools] Small QOL changes

### PR DESCRIPTION
**Pull request by emikelsons**
- Expanded display_all_literature_models() so that now it's possible to filter for models with desired properties(gauge algebra etc.). 
- Made new file model_indices.json that keeps track of a model's index. Running _create_literature_model_index() updates this file, but I still need to improve this by removing indices if a model is removed, for example

### CODE REVIEW

**Comment by emikelsons** [comment]
@HereAround @apturner

**Comment by HereAround** [comment]
@emikelsons Thank you for working on this. This looks very promising.

Just to clarify: Are you still working on this (e.g. to add more features)?

**Comment by emikelsons** [comment]
> @emikelsons Thank you for working on this. This looks very promising.
> 
> Just to clarify: Are you still working on this (e.g. to add more features)?

Yes, I still wanted to add some improvements

**Comment by HereAround** [comment]
Thank you for working on this @emikelsons . This looks great!

**Review by HereAround — APPROVED** [review]

**Comment by HereAround** [comment]
@emikelsons I understand that the commit messages in git are supposed to be nice and short, so that the log remains quickly readable (as in, one immediately has a bird's eye perspective of what changes did happen). Consider making your commit messages shorter in the future. Is a small nitpick though.

**Pull request merged**
