### PR TITLE
Applying naming conventions for the schemes

### PR DESCRIPTION
**Pull request by HechtiDerLachs**
This addresses this morning's discussion. 

In particular, I migrated the code for `ClosedEmbedding`. Eventually, we may want to also introduce a type `ClosedSubSpec` or something, but that can (and should) also be done later.

### CODE REVIEW

**Review by fingolfin — APPROVED** [review]
Looks good to me

**Comment by HechtiDerLachs** [comment]
Any objections? @afkafkafk13 @simonbrandhorst @HereAround @fieker ?

**Review by afkafkafk13 — COMMENTED** [review]
Looks good to me.

**Comment by simonbrandhorst** [comment]
I can live with it.

**Pull request merged**
