### PR TITLE
Serialize some stuff in FTheoryTools

### PR DESCRIPTION
**Pull request by lkastner**
Loading isn't available yet and I still have to think about families of these models.

*** update

loading is available for Global Tate Model. We can either continue and work on the families?
or move the families to another pull request?

*** unrelated serialization changes that happen in this pull request and a note on serialization in experimental

I moved the serialization include between Oscar source and experimental. (which means I had to pull out the Laurent module and put it into source). I think that any serialization code that is written for anything in experimental 
should be put into experimental.

### CODE REVIEW

**Comment by antonydellavecchia** [comment]
@thofma I moved the Laurent Module into source here. Maybe makes sense for you to take a quick look and make sure I didn't mess anything up there

**Comment by HereAround** [comment]
Thank you for working on this @antonydellavecchia . I am not sure I understand why Laurent monomials (a.k.a. the Laurent module) are touched in this PR. Why is this necessary?

**Comment by thofma** [comment]
Looks good for the Laurent things

**Comment by HereAround** [comment]
I discussed with @apturner yesterday. Generally speaking, Andrew and I prefer smaller changes/more PRs (otherwise, too much could change in the meantime etc.). So we are very happy to first have the serialziation for the global tate models and have the other models (which sadly are - at least in part - still subject to change) addressed in separate PRs.

**Comment by antonydellavecchia** [comment]
> Thank you for working on this @antonydellavecchia . I am not sure I understand why Laurent monomials (a.k.a. the Laurent module) are touched in this PR. Why is this necessary?

they are unrelated. I just had to move somethings around in the includes, and I had serialized somethings for the laurent module that was in experimental without realizing. We decided to move laurent into src to deal with it. Thats why i tagged Tommy in this pull request as well.

**Comment by antonydellavecchia** [comment]
> I discussed with @apturner yesterday. Generally speaking, Andrew and I prefer smaller changes/more PRs (otherwise, too much could change in the meantime etc.). So we are very happy to first have the serialziation for the global tate models and have the other models (which sadly are - at least in part - still subject to change) addressed in separate PRs.

Since tests are passing, if you approve of the changes submit an approving review and we can get this merged

**Review by HereAround — APPROVED** [review]
Thank you for working on this @lkastner and @antonydellavecchia . As I see it (and as @thofma is ok with the changes on the Laurent module), this should be good to go. We can address the serialization of the other models in a separate PR.

**Pull request merged**
