### PR TITLE
WIP: Toric varieties and covered schemes

### PR DESCRIPTION
**Pull request by HechtiDerLachs**
We are finally in the position to introduce and build toric varieties as abstract covered schemes. This PR shall serve as a platform for exhibition, discussion, and proposals on how to achieve that. 

Personally, I am interested in this, because of the following. For toric varieties there are a lot of algorithms and strategies to compute invariants that are hardly accessible for general schemes, such as cohomology of line bundles, topological Betti numbers, etc. My hope is that by building the bridge between the two setups, we get a better understanding of which methods can be carried over and/or adapted. Ideally, we can derive new algorithms from that and then also have the possibility to compare their output to those coming from the original toric counterparts. 

Comments and questions are welcome! 

(CC @HereAround @lkastner )

### CODE REVIEW

**Comment by fingolfin** [comment]
Was this ready for merging? The title still says "wip"

**Comment by lkastner** [comment]
> Was this ready for merging? The title still says "wip"

I was still investigating some things... :(

**Comment by HechtiDerLachs** [comment]
We have no clue what's going on here. Nobody remembers having merged this. Still investigating...

**Comment by benlorenz** [comment]
The audit logs shows:
```
simonbrandhorst – pull_request.indirect_merge
Merged (indirect) the pull request oscar-system/Oscar.jl #1544.
Germany 1 hour ago
```
And this `indirect_merge` seems to indicate that all commits were included in a different branch that was merged, in this case #1561.

**Comment by HechtiDerLachs** [comment]
Alright, so what I think has happend: In [this](https://github.com/oscar-system/Oscar.jl/pull/1561) PR I had once locally merged the branch for toric varieties to get generic updates. Then I deleted the specific toric files in there. But nevertheless, GitHub now thinks that this pr is completely contained in the master. 

I suggest, we leave this as is for the time being. @lkastner @HereAround : You still have the link to this PR and we can discuss our stuff amongst us. When the time is ripe, I/we will then do a proper PR again.

**Comment by fingolfin** [comment]
Ahhh... So this PR here had been merged into #1561 at some point and then later reverted there? Then yes, it's clear what happened:

When the head commit of a PR (here: this PR) is pushed to the repository (e.g. because it was part of another PR that is merged, and not rebased or squashed): In that case GitHub closes the PR as merged (as technically, it has been merged, albeit indirectly).

As a hint for future operations (CC @simonbrandhorst): The problem then could have been avoided by doing a "squash" merge instead of a plain merge. In my personal, subjective view, this would have been better here anyway as the history on the other PR contained a 36 commits including a bunch of merges, "trying to fix something" commits and which were not arranged in a very deliberate way (no offense intended -- I merely want to contrast to PRs where there are a bunch of PRs that are clearly separated into independent steps)

Anyway: what's done is done; as long a we understand what happened, we'll cope :-). )

**Comment by simonbrandhorst** [comment]
Sorry, for the confusion. Next time I will remember to squash.

**Pull request merged**
