### PR TITLE
Do not cache polynomial rings

### PR DESCRIPTION
**Pull request by ederc**
This PR disables caching of `polynomial_ring` in `Rings/*`. See discussion in #2455.

### CODE REVIEW

**Comment by ederc** [comment]
@HechtiDerLachs Any idea what to do with these tests from `test/Rings/ReesAlgebra.jl`?
```
  # Both algebras should be the same despite being created differently.
  @test all(x->iszero(RM(x)), gens(modulus(Rg)))
  @test all(x->iszero(Rg(x)), gens(modulus(RM)))
```

**Comment by HechtiDerLachs** [comment]
I'm afraid, I do not yet fully understand the question, sorry. Should I run the test on this branch and look into the error messages?

**Comment by ederc** [comment]
These tests will fail since the corresponding requirement that the parents are equal no longer holds. As discussed in #2455 this is the behaviour wanted. I just do not know how to adjust the corresponding tests, this is something I would like you to decide.

**Comment by HechtiDerLachs** [comment]
Alright, thanks for the clarification. At the moment I can not so easily switch branches since I'm currently working on something else, but I will look into it the next possible moment.

**Comment by fingolfin** [comment]
Orthogonal to this issue, but: @HechtiDerLachs you can have multiple Oscar.jl clones in parallel (or even use a single clone with multiple worktrees). So that you can e.g. have Oscar master and your active development branch and *another* branch all ready and running in different Julia sessions... I can happily help you set that up, too (not saying this to put pressure on you to look into this issue, just to improve your workflow in the future)

**Comment by HechtiDerLachs** [comment]
@ederc : Could you replace the lines in the test by the following:
```julia
@test all(x->iszero(evaluate(x, gens(RM))), gens(modulus(Rg)))
@test all(x->iszero(evaluate(x, gens(Rg))), gens(modulus(RM)))
```
I think that should do the job. At least it does for me locally. 
Thank you and sorry about the delay.

**Comment by ederc** [comment]
@HechtiDerLachs Thanks, I applied your changes.

**Review by joschmitt — APPROVED** [review]
Thank you!

**Pull request merged**
