### PR TITLE
Add docs on complex algorithms

### PR DESCRIPTION
**Pull request by lkastner**
This is the suggestion to have a dedicated page on the more complex algorithms in OSCAR to point users at, so we can avoid having the users ask the same question for the 1001th time.

### CODE REVIEW

**Comment by fieker** [comment]
Fine, but what is the goal/ where is the limit? Should we also add
 - CosetEnumeration, IsFinite on FP-groups
 - (integer) factoring, disc. log and class groups (sub-exponential)
As those come to mind as well....

**Review by fieker — APPROVED** [review]

**Comment by lkastner** [comment]
> Fine, but what is the goal

The goal is to be able to give someone who is experiencing code which doesn't terminate a starting point such that they are themselves able to figure out what is expensive about their code. They might then themselves be able to figure out a way to avoid those operations or reduce their number.

> where is the limit?

I don't know? We should try to restrict ourselves to functions that happen in the background a lot, that is why I chose to start with Groebner bases and convex hulls. These are almost always necessary when working with ideals or polytopes, but it doesn't always become obvious from other definitions that these can only be checked with such an operation.

**Comment by fieker** [comment]
Then I'd add factoring and Todd coxeter(?)

**Comment by fieker** [comment]
I'll merge it tomorrow unless there are complaints. We can add more hard algos whenever we find them

**Pull request merged**
