### PR TITLE
Some improvements to make the QSM models accessible for scheme theoretic analysis

### PR DESCRIPTION
**Pull request by HechtiDerLachs**
@HereAround : These are some things I needed today to make your QSM model run. I could add a test file, but at the moment it depends on your other PR. Maybe we can come up with something smaller?

### CODE REVIEW

**Comment by HechtiDerLachs** [comment]
Btw, this would be the test-file:
```julia
qsm_model = literature_model(arxiv_id = "1903.00009", model_parameters = Dict("k" => 283));

H = qsm_model.hs_model

ambient_space(H)

cox_ring(base_space(H))

h = hypersurface_equation(H)

S = cox_ring(ambient_space(H))

parent(h) === S # fails!

stanley_reisner_ideal(ambient_space(H))

var_names = symbols(parent(h))

S.R.S = var_names

H.hypersurface_equation = Oscar.eval_poly(string(h), S)

explicit_model_sections(H)
dd = explicit_model_sections(H)
B = base_space(H)
b = basis_of_global_sections(anticanonical_bundle(B))
A = QQFieldElem[3//8 -1//4 -1//2 -5//4 -3//4 2//3 -1//3 7//3 1//2 9 -2 1//7 2//5 4//7 -1//6 3 -1//3 -1; -3//5 -1//10 3//5 -1//2 -3//10 8//3 -1//8 -10//9 3 -2//5 1//2 -1//2 -1 5//6 1//2 -10//3 0 5; 1 1//5 3 3 -1//2 1//10 1//3 -7//6 8 -1//6 5//8 -4//5 -5//4 0 6//5 8//7 2//3 9; -7//4 -2 1//8 -2 -3//4 5//3 -7 -7 7//5 1//2 -3 -1//5 -1//9 1//10 1//2 -1//10 -7//5 -1//2; 9//4 -4//3 2//7 -9//7 -9 2 -7//10 -1 -6//7 -3//2 -4//3 -1 7//4 -5//9 -7//2 9//7 -1//3 0]
dd["s3"] = prod(gens(parent(dd["s3"])))
dd["s1"] = sum(A[1, j]*b[j] for j in 1:length(b); init=zero(b[1]))
dd["s2"] = sum(A[2, j]*b[j] for j in 1:length(b); init=zero(b[1]))
dd["s5"] = sum(A[3, j]*b[j] for j in 1:length(b); init=zero(b[1]))
dd["s6"] = sum(A[4, j]*b[j] for j in 1:length(b); init=zero(b[1]))
dd["s9"] = sum(A[5, j]*b[j] for j in 1:length(b); init=zero(b[1]))
H2 = tune(H, dd)

W = ambient_space(H2)
S = cox_ring(W)
I = ideal(S, hypersurface_equation(H2))
II = ideal_sheaf(W, I);
Y, inc_Y = sub(II)
set_attribute!(Y, :is_irreducible=>true)
set_attribute!(Y, :is_reduced=>true)
set_attribute!(Y, :is_equidimensional=>true)

p = next_prime(256)
FF = GF(p)
dirty_red(x) = FF(numerator(x))//FF(denominator(x))

Yp, bc_Y = base_change(dirty_red, Y)

Wp, bc_W = base_change(dirty_red, W)

_, bc_inc, _ = base_change(dirty_red, inc_Y, domain_map=bc_Y, codomain_map=bc_W)


set_attribute!(Yp, :is_irreducible=>true)
set_attribute!(Yp, :is_reduced=>true)
set_attribute!(Yp, :is_equidimensional=>true)

Jp = Oscar.ideal_sheaf_of_singular_locus(Yp);
K = pushforward(bc_inc, Jp);
comps = Oscar.maximal_associated_points(K)
```
I get 18 one-dimensional components for the singular locus of this model.

**Comment by HechtiDerLachs** [comment]
@simonbrandhorst : This is also interesting for us since it contains several fixes for `base_change` and reduction mod p.

**Comment by HechtiDerLachs** [comment]
Tests pass. Ready for merge from my side.

Brief summary:

 * disable some internal checks
 * fix some internal restrict routines to handle change of coefficient rings
 * make `base_change` preserve `ClosedEmbedding`s and `CoveredClosedEmbedding`s
 * make pushforwards of ideal sheaves along closed embeddings lazy. 

This now allows us to reduce (toric) schemes mod p and get some idea about their geometry in positive characteristic. I pushed this a bit further and could do partial resolutions of the qsm-model above, at least in positive characteristic.

**Review by simonbrandhorst — APPROVED** [review]
looks plausible

**Pull request merged**
