### PR TITLE
Rename .bib item for ATLAS

### PR DESCRIPTION
**Pull request by fingolfin**

### CODE REVIEW

**Comment by thofma** [comment]
Is there a problem with WWTSPNNLBA? I thought everybody knew that this is the ATLAS.

**Comment by lgoettgens** [comment]
Can we wait with this until #2605 is merged? The conflict will be much easier to handle here instead of there.

**Comment by fingolfin** [comment]
I agree 100% this should wait for #2605 !

@thofma err.... I am not quite sure to respond; are you serious?

**Comment by thofma** [comment]
No, it was a (poor) attempt at humour.

**Review by lgoettgens — APPROVED** [review]

**Review by ThomasBreuer — APPROVED** [review]
No problem with this change.
(The original idea was that contrary to LaTeX, Documenter.jl does not create labels for showing the bib entries but just uses the given programmatic labels.)

**Pull request merged**
