### PR TITLE
list group types that can be serialized

### PR DESCRIPTION
**Pull request by ThomasBreuer**
addresses #3761

### CODE REVIEW

**Review by micjoswig — APPROVED** [review]
Good.

**Comment by lgoettgens** [comment]
This should ideally get backported, right?

**Comment by benlorenz** [comment]
> This should ideally get backported, right?

We can probably do that but need to make sure the types are also serializable there, `SubPcGroup` doesn't even exist on the release branch.

**Comment by lgoettgens** [comment]
@benlorenz If you create a new `backports-release-1.0` branch, I can create a PR with this change here adapted against that.

**Comment by benlorenz** [comment]
> @benlorenz If you create a new `backports-release-1.0` branch, I can create a PR with this change here adapted against that.

I recreated the branch.

**Comment by lgoettgens** [comment]
The backport PR is https://github.com/oscar-system/Oscar.jl/pull/3771.

**Pull request merged**
