### PR TITLE
Rename blowdown to blowup

### PR DESCRIPTION
**Pull request by paemurru**
Command used:
```
sed --follow-symlinks -i \
-e "s;blowdown;blowup;g" \
-e "s;blow-down;blow-up;g" \
-e "s;Blow-down;Blow-up;g" \
-e "s;Blowdown;Blowup;g" \
-e "s;BlowDown;BlowUp;g" \
$(git ls-files)

mv "./test/AlgebraicGeometry/ToricVarieties/toric_blowdowns.jl" "./test/AlgebraicGeometry/ToricVarieties/toric_blowups.jl"
mv "./docs/src/AlgebraicGeometry/ToricVarieties/BlowdownMorphisms.md" "./docs/src/AlgebraicGeometry/ToricVarieties/BlowupMorphisms.md"
```

### CODE REVIEW

**Comment by afkafkafk13** [comment]
Looks good to me.  Ping @HereAround  for the toric side, please. (In case of his approval, this can be merged.)

**Comment by afkafkafk13** [comment]
Do we need to deprecate to save some code that people have written but not merged yet?

**Comment by HechtiDerLachs** [comment]
I'm afraid that an `n`-th layer of deprecation is necessary. Maybe we can even roll back in some cases? I don't know how to handle this. Other than that, I'm ok with the changes.

**Comment by lgoettgens** [comment]
From a purely technical POV, deprecations are not necessary here, as there are no (non-comment) changes to `src/`, and no changes to the book.
However, adding deprecations for things in `experimental/` is still a nice convenience for users.

(cc @lkastner)

**Comment by mjrodgers** [comment]
Discussed in triage, looks okay to merge.

**Review by afkafkafk13 — APPROVED** [review]

**Pull request merged**
