### PR TITLE
A few complements to recent PRs

### PR DESCRIPTION
**Pull request by wdecker**

### CODE REVIEW

**Comment by thofma** [comment]
Is this ready to be merged @wdecker? The failing doctests are blocking the other PRs, so we should fix those quickly.

**Comment by wdecker** [comment]
Which failing doctests? 
In any case, this is ready to be merged.

**Comment by thofma** [comment]
For every PR the tests are failing right now, because the doctests fail.

**Review by thofma — APPROVED** [review]

**Comment by wdecker** [comment]
O.K. I understand now, sorry, may be I am already tired.
This whole thing needs more thoughts because of the printing of presentations and free resolutions.
We had this discussion before ...

**Pull request merged**
