### PR TITLE
Fix for binomial primary decomposition

### PR DESCRIPTION
**Pull request by CarloSircana**

### CODE REVIEW

**Comment by CarloSircana** [comment]
I just noticed that there is a conflict with the pull request #455, that handles the Groebner basis problem properly. Don't merge this for now.

**Comment by thofma** [comment]
Needs a rebase now.

**Comment by thofma** [comment]
Some tests are failing.

**Comment by thofma** [comment]
Some tests are still failing @CarloSircana?

**Comment by thofma** [comment]
Finally we made it.

**Comment by wdecker** [comment]
great!

**Comment by wdecker** [comment]
@CarloSircana, @thofma: I found the following problem:

julia> R, x = PolynomialRing(QQ, "x"=>1:3)
(Multivariate Polynomial Ring in x[1], x[2], x[3] over Rational Field, fmpq_mpoly[x[1], x[2], x[3]])

julia> I = ideal(R, [x[3]^2*(x[1]^2-x[2]^2), x[3]*(x[1]^4-x[2]^4), x[3]^3])
ideal generated by: x[1]^2*x[3]^2 - x[2]^2*x[3]^2, x[1]^4*x[3] - x[2]^4*x[3], x[3]^3

julia> iscellular(I)
(true, [1, 2])

julia> cellular_minimal_associated_primes(I)
ERROR: UndefVarError: QabField not defined
Stacktrace:
 [1] cellular_minimal_associated_primes(::MPolyIdeal{fmpq_mpoly}) at /Users/decker/.julia/dev/Oscar/src/Rings/binomial_ideals.jl:670
 [2] top-level scope at REPL[14]:1

**Comment by wdecker** [comment]
@CarloSircana, @thofma: Sorry, another problem

julia> I = ideal(R, [x[1]*x[4]^2-x[2]*x[5]^2, x[1]^3*x[3]^3-x[2]^4*x[4]^2, x[2]*x[4]^8-x[3]^3*x[5]^6])
ideal generated by: x[1]*x[4]^2 - x[2]*x[5]^2, x[1]^3*x[3]^3 - x[2]^4*x[4]^2, x[2]*x[4]^8 - x[3]^3*x[5]^6

julia> binomial_primary_decomposition(I)
ERROR: input ideal is not cellular
Stacktrace:
 [1] error(::String) at ./error.jl:33
 [2] partial_character_from_ideal(::MPolyIdeal{fmpq_mpoly}, ::FmpqMPolyRing) at /Users/decker/.julia/dev/Oscar/src/Rings/binomial_ideals.jl:419
 [3] cellular_associated_primes(::MPolyIdeal{fmpq_mpoly}, ::AbstractAlgebra.Generic.MPolyRing{Oscar.QabModule.QabElem}) at /Users/decker/.julia/dev/Oscar/src/Rings/binomial_ideals.jl:626
 [4] cellular_primary_decomposition(::MPolyIdeal{fmpq_mpoly}, ::AbstractAlgebra.Generic.MPolyRing{Oscar.QabModule.QabElem}) at /Users/decker/.julia/dev/Oscar/src/Rings/binomial_ideals.jl:731
 [5] binomial_primary_decomposition(::MPolyIdeal{fmpq_mpoly}) at /Users/decker/.julia/dev/Oscar/src/Rings/binomial_ideals.jl:779
 [6] top-level scope at REPL[23]:1

**Comment by fingolfin** [comment]
@wdecker perhaps best to open an issue for that?

**Pull request merged**
