### PR TITLE
Fix some combinatorics

### PR DESCRIPTION
**Pull request by joschmitt**
Fixes some of the issues mentioned in #3850.

### CODE REVIEW

**Comment by JohnAAbbott** [comment]
@joschmitt  in file `test/Combinatorics/EnumerativeCombinatorics/compositions.jl`  should there be an `@inferred` at line 58?

**Review by JohnAAbbott — APPROVED** [review]
This looks very good to me; I've not tried running the improved tests, but they look to be quite thorough!  I have written one (unimportant?) question in the chat.

**Comment by joschmitt** [comment]
> @joschmitt in file `test/Combinatorics/EnumerativeCombinatorics/compositions.jl` should there be an `@inferred` at line 58?

Yes, I should also put it there. Thank you!

**Comment by joschmitt** [comment]
@benlorenz It would be good to have this in 1.1. It contains some bugfixes and might be nice to have for the Begehung.

**Pull request merged**
