### PR TITLE
Add sparse multivariate polynomial rings to experimental

### PR DESCRIPTION
**Pull request by lgoettgens**
When computing stuff on low degree polynomials in polynomial rings with a lot of variables, the usual implementations (e.g. `AbstractAlgebra.Generic.MPolyRing`) are not efficient to use at all.
A sparse polynomial does not save the whole exponent vector for each monomial, but only pairs of (variable id, exponent) for non-zero exponents.

The increase in speed gets visible in the following example:
```julia
R, x = ZZ["y"]

S, varlist = PolynomialRingSparse(R, 10000)
@time sum(gens(S));   # 1.086290 seconds

T, varlist = PolynomialRing(R, 10000)
@time sum(gens(T));   # 124.527147 seconds
```

A lot of tests could be used from `AbstractAlgebra.Generic.MPolyRing`.

### CODE REVIEW

**Comment by tthsqe12** [comment]
I think this is a good idea, but unfortunately I won't be able to review for a few more days. Maybe AA should have some conformance tests for the mpoly interface...

**Comment by thofma** [comment]
OK, I'll add you to the review.

**Comment by lgoettgens** [comment]
the errors are probably due to some import issues. after my oscar installation works again, I will sort them out. in my current workaround (just use Hecke and AA) they do not occur

**Comment by lgoettgens** [comment]
tests should be working now, at least they do on my now working oscar installation

**Comment by tthsqe12** [comment]
I have not forgotten about this.

**Review by tthsqe12 — COMMENTED** [review]
This is a good start! Two points:
1. Complex arithmetic operators (divrem(?), sqrt, gcd, factor, ...) are probably best done in the dense exponent domain because no one wants to roll out these functions again. Probably something like a conversion between sparse <-> dense (only using the variables that are actually present in the sparse) would allow us to check these boxes off much faster.
2. I have started annotating my structs with ownership conventions. If these are clear in this code, I could decide if all of the deep copies on the exponents are necessary.
3. I see the exponent vector interface includes the usual `Vector{Int}` and the new `Vector{Tuple{Int, Int}}`. I know Oscar has sparse vectors inherited from Hecke https://github.com/thofma/Hecke.jl/blob/master/src/HeckeTypes.jl#L289 . We _could_ eventually add `SRow{Int}` or `SRow{fmpz}` to the `set_exponent_vector!`. As for getting exponent vectors in a specified format, the current AA interface need to be extended so that we are not locked into `Vector{Int}`s everywhere.

**Comment by lgoettgens** [comment]
1. I was a bit afraid to start re-implementing all those algorithms again. Your approach seems good to me. I'll try to set up this conversion.
2. The ownership should be the same as e.g. for Generic.FreeAssAlgebra, as they are pretty similar in structure and implementation. Do you have a comment snippet laying somewhere to add here?

**Comment by lgoettgens** [comment]
1. is done

**Comment by lgoettgens** [comment]
@tthsqe12 I would highly appreciate it if you could take a look at the ownership and necessity of copying, as I am not that familiar with it in Julia. Hopefully, some of the copies can be omitted since right now I observe a slowdown by a factor of 2 compared to `Generic.MPoly`

**Comment by tthsqe12** [comment]
slowdown by a factor of two in what operations, how many variables?
Can you post your profiling code?

**Comment by lgoettgens** [comment]
nevermind. the enormous slowdown of 2x was between `MPolySparse` and `fmpq_mpoly`. Comparing `MPolySparse` to `Generic.MPoly`, the former gets significantly faster the more variables are used (as expected; almost the same for ~20 vars, 30% faster for ~290 vars).
My current benchmarking code does not benchmark the MPoly-interface, but its use in a larger project (specify the used constructor in [source file](https://gitlab.com/johannesflake/pbwdeformations.jl/-/blob/lg/sparse_polynomials/src/SmashProductDeformLie.jl#L243) and then run [benchmark file](https://gitlab.com/johannesflake/pbwdeformations.jl/-/blob/lg/sparse_polynomials/scripts/Benchmark.jl).

Nevertheless, there may be unnecessary occurrences of `deepcopy` in the code whose removal could speed up `MPolySparse` even more.

**Comment by tthsqe12** [comment]
Alright. Generic.MPoly currently packs into 64 bits and fmpq_mpoly currently packs into as few as 8 bits.
Once an ownership convention is placed on the exponents, the possibly unnecessary occurrences of deepcopy can be resolved and a proper add! can be implemented. For now, this is good by me.

**Pull request merged**
