### PR TITLE
Try to fix resolvent

### PR DESCRIPTION
**Pull request by Pi-tree**

### CODE REVIEW

**Comment by fingolfin** [comment]
@fieker can you please have a look? (Would it make sense to add a test for this? @Pi-tree can you provide an example which is fixed by this change?)

**Comment by Pi-tree** [comment]
Well, for me it didn't work at all because there seems to be no function 'evaluate' with three arguments where the third is a fmpz_poly.

**Comment by fingolfin** [comment]
Sure, but can you just write down an input that was broken before this and fixed afterwards? Then this can be turned into a test. Thanks!

**Comment by fieker** [comment]
The error is that the function Helena replaces was never written - it was meant as an optimisation that wasn't implemented. This is fine to go as is....

**Pull request merged**
