### PR TITLE
Make experimental packages more self-contained

### PR DESCRIPTION
**Pull request by lgoettgens**
Resolves the first bullet point in the list in https://github.com/oscar-system/Oscar.jl/issues/3408.

With this PR, removing an experimental project is now as easy as deleting the corresponding folder in `experimental/` (and maybe removing it from `oldexppkgs` or `orderedpkgs` in `experimental/Experimental.jl`), in particular `using Oscar` and `Aqua.test_undefined_exports(Oscar)` succeed. The exemption is `experimental/Rings/` which, currently, needs to be available for Oscar to load.
Tests in general, will not work yet, see https://github.com/oscar-system/Oscar.jl/issues/3408 for a roadmap on how to achieve that.

This PR does not change any current behaviour/exports/deprecations/etc., it just moves them to a more suited places.

### CODE REVIEW

**Comment by benlorenz** [comment]
@lgoettgens I am not really sure why this should be in 1.0, it is mostly meant to help keep the code-bases separate but there will not be much further development on the release branch. Moving lots of stuff around now seems not helpful for the release.

**Comment by lgoettgens** [comment]
Yes, you are right. I think my intention was to reduce the number of potential conflicts occurring while backporting

**Comment by benlorenz** [comment]
Maybe it would make sense to wait with merging this PR until we are done with most of the backporting, to avoid any conflicts, both for master and for the backports.

**Comment by lgoettgens** [comment]
Yeah, waiting a few more days until all of the feature backports are done is more than fine. The minor doc changes later shouldn't become an issue with conflicts

**Review by fingolfin — APPROVED** [review]
Looks good to me

**Comment by benlorenz** [comment]
I changed it to draft so that we don't accidentally merge this right now, we can change it back some time next week I guess.

**Comment by fieker** [comment]
What is the motivatio to further tinker with the experimental stuff? As far as I can see: it works.
Is there any real, known, problem with the current situation?

**Comment by lgoettgens** [comment]
> What is the motivatio to further tinker with the experimental stuff? As far as I can see: it works. Is there any real, known, problem with the current situation?

Please see https://github.com/oscar-system/Oscar.jl/issues/3408 for the motivation. And let's keep the fundamental discussion there.

**Review by lkastner — APPROVED** [review]
Thanks for taking care of this.

**Comment by lgoettgens** [comment]
> Maybe it would make sense to wait with merging this PR until we are done with most of the backporting, to avoid any conflicts, both for master and for the backports.

Since 1.0 is now released and the bulk of backports is done, I think we could continue with this.

**Review by benlorenz — APPROVED** [review]

**Comment by lgoettgens** [comment]
Can we get this merged before any more conflicts come up?

**Pull request merged**
