### PR TITLE
Make `elements` even faster

### PR DESCRIPTION
**Pull request by fingolfin**
Also change some doctest examples to use `order(G)` instead of `length(elements(G))`

CC @SyxP

### CODE REVIEW

**Review by thofma — APPROVED** [review]
Looks good to me! I guess we need a test since this is not called in the docstrings anymore.

**Review by ThomasBreuer — COMMENTED** [review]
No question that `length(elements(G))` should not be called.

Concerning the code for `elements` resp. `collect`, I would have thought that the only logical difference between the proposed loop over `f(x)` for `x` in `l` and the syntax `[f(x) for x in l]` is that in the former version the type of the result gets set in advance. If the difference in runtime is as large as stated then then this seems to indicate a problem with the latter syntax in general (and this is used a lot).

**Comment by SyxP** [comment]
I don't think setting the type in advance is the difference, but it seems that it is due to the fact that you are calling from `1:length(els)` rather than the generic iterator over `els`, together with the knowledge the length and index type are both known in advance.

One could show this by creating a version of `elements(G::T, ::Type{U}) where {T <: GAPGroup, U}` and passing in the type of the array explicitly. You then notice the speed isn't any faster.

**Comment by fingolfin** [comment]
Regarding broken tests: uhh, this is because GAP's `Elements` (actually an alias for `AsSet`) returns the elements of the symmetric group in one order, but GAP's iterator for symmetric groups returns a different order... So for now I'll change this back (and leave a comment, as I am pretty sure I went down this road before...)

Moreover, I've now rewritten the patch once again to be *even faster*, and actually almost identical to what @SyxP wrote -- just with a type assertion added. But I am not even sure *why* that makes it faster (and avoids all those allocations)...

Anyway, here are some timings. With `master`:

    julia> G = symmetric_group(8); @btime elements(G);
      2.195 ms (80649 allocations: 2.46 MiB)

With my previous patch:

    julia> G = symmetric_group(8); @btime elements(G);
      800.625 μs (4 allocations: 630.08 KiB)

With the new patch (note: more allocations but still faster):

    julia> G = symmetric_group(8); @btime elements(G);
      194.792 μs (9 allocations: 630.23 KiB)

For comparison, collect using the GAP iterator interface:

    julia> G = symmetric_group(8); @btime collect(G);
      28.172 ms (184051 allocations: 6.23 MiB)

**Comment by fingolfin** [comment]
Oh and note that `elements` still is 100% undocumented, because historically we decided it should go, as `collect` is the more natural interface. The question now is: must `collect(G)` return the same as `[x for x in G]`? The documentation isn't clear on this.. but it surely would be surprisng.

Anyway I am now using JET.jl to remove some issues in GAP.jl and Oscar.jl contributing to this all.

**Pull request merged**
