### PR TITLE
Start docu on G-algebras as template for moving Plural functionality …

### PR DESCRIPTION
**Pull request by wdecker**
…from Singular to OSCAR

### CODE REVIEW

**Comment by tthsqe12** [comment]
Couple of points:
- We are not so much moving the functionality as we are wrapping it in a nice oscaresque wrapper
- Could the documentation of G-algebras mention what the "G" stands for.
- The G-algebra elements themselves satisfy a similar interface to `MPolyElem`s, i.e. exponent vectors, iterations, etc.

**Comment by wdecker** [comment]
@tthsqe12 

    We are not so much moving the functionality as we are wrapping it in a nice oscaresque wrapper

Yes, sure, moving is the wrong word.

    Could the documentation of G-algebras mention what the "G" stands for.

Good point. I will improve the docu accordingly.

    The G-algebra elements themselves satisfy a similar interface to MPolyElems, i.e. exponent vectors, iterations, etc.

Yes, we will document this as soon as the functionality is there.

**Comment by tthsqe12** [comment]
so, I have the constructor looking like the following.
```
julia> r,(x,y,z) = QQ["x", "y", "z"];

julia> R,(x,y,z) = g_algebra(r, [0 x*y x*z; 0 0 y*z + 1; 0 0 0], deglex(gens(r)));

julia> R
G-algebra over Rational Field with relations y*x = x*y, z*x = x*z, z*y = y*z + 1

julia> (y*x, z*x, z*y)
(x*y, x*z, y*z + 1)
```

**Comment by wdecker** [comment]
A quick question: I wonder whether we should define the G-algebra directly, without defining a polynomial ring first? That is, shouldn't we hide in OSCAR how things are working in Singular?

**Comment by tthsqe12** [comment]
I don't know how you are going to specify the relations without an MPolyRing first.

**Comment by wdecker** [comment]
This is how it looks like in Magma:

> K := RationalField();
> A<x,y> := FPAlgebra<K, x, y | x^2*y - y*x, x*y^3 - y*x>;

If we can't do it in a similar way, we should at least follow the math and start from a free associative algebra rather than from a polynomial ring. But what precisely is the problem?

**Comment by tthsqe12** [comment]
There are problems with starting from a freeassalg. Namely, the relations are of the form `yx=xy + lower order terms` where "lower" is defined by an mpoly monomial ordering.
In julia, all arguments to functions are evaluated before the function is called. Therefore, x and y would be undefined in that magma code. Furthermore, functions generally can't introduce variables into local scope.

**Comment by wdecker** [comment]
@tthsqe12 (1) How about using the name PBW-algebra instead of G-algebra as in the revised docu?
                  (2) After thinking about it, I agree with defining PBW-algebra starting from a polynomial rings as you did in #1511.

**Comment by tthsqe12** [comment]
sure, so the constructor is `pbw_algebra`?

**Comment by wdecker** [comment]
> sure, so the constructor is `pbw_algebra`?

Yes, please!

**Comment by tthsqe12** [comment]
For ideals, do you see a need for supporting right ideals? Singular.jl does left and two-sided via
```
Ideal(...)
Ideal(...; two_sided=true)
```

**Comment by wdecker** [comment]
> For ideals, do you see a need for supporting right ideals? 

No, left and two-sided ideals are enough as we can always pass to the opposite algebra to mimic right ideals.

**Comment by tthsqe12** [comment]
Does this mean we need a function for creating the opposite algebra and a map between the two?

**Comment by wdecker** [comment]
> Does this mean we need a function for creating the opposite algebra and a map between the two?

Yes! How about `opposite_algebra`? See also here:

https://www.singular.uni-kl.de/Manual/4-3-1/sing_478.htm#SEC518

**Comment by hannes14** [comment]
Singular has
ring rOpposite(ring src)
  /* creates an opposite algebra of R */
  /* that is R^opp, where f (*^opp) g = g*f  */
and 
/// opposes a vector p from Rop to currRing (dst!)
poly pOppose(ring Rop, poly p, const ring dst)
 and
/// opposes a module I from Rop to currRing(dst)
ideal idOppose(ring Rop, ideal I, const ring dst)

**Comment by tthsqe12** [comment]
ok. Another question. I assume the three algorithms for interesecting two left ideals, two two-sided ideals, and a left ideal and a two-sided ideal are different. However, Singular's `id_Intersection` takes not data on two-sidedness (ideals are just lists of polys). How does this work?

**Comment by wdecker** [comment]
> ok. Another question. I assume the three algorithms for interesecting two left ideals, two two-sided ideals, and a left ideal and a two-sided ideal are different. However, Singular's `id_Intersection` takes not data on two-sidedness (ideals are just lists of polys). How does this work?

@hannes14 Can you please answer this

**Comment by hannes14** [comment]
id_Sect (libSingular-julia: id_Intersection) intersects 2 left ideals.
intersecting a left ideal and a two sided ideal: the two sided ideal is also a left ideal:
will be intersected as left ideals.
There is no direct intersection of 2 two sided ideals, but  id_TwoStd(id_Intersection(A,B))
should work.

**Pull request merged**
