### PR TITLE
Setup Travis and Code coverage tracking in README.md

### LINKED ISSUE #86: Setup Travis and Code coverage tracking
Also add status widgets to the README.md like for other projects

### PR DESCRIPTION
**Pull request by mohamed-barakat**
Closes #86

### CODE REVIEW

**Comment by fingolfin** [comment]
Preview: https://github.com/mohamed-barakat/Oscar.jl

**Comment by fingolfin** [comment]
Note that in the issue, I actually meant that we should setup code coverage to actually work, *and* update README.md :-). So we also need PR #87, which also adds badges, but yours are nicer / more comprehensive.

**Comment by mohamed-barakat** [comment]
> Note that in the issue, I actually meant that we should setup code coverage to actually work, _and_ update README.md :-). So we also need PR #87, which also adds badges, but yours are nicer / more comprehensive.

Indeed, I didn't notice that PR #87 adds badges :)

**Comment by fingolfin** [comment]
I've removed them there, and pushed. Once the pre-announced Travis database maintenance which is taking place right now is over (see <https://www.traviscistatus.com>) our PRs will build and then we can merge them in order.

**Comment by mohamed-barakat** [comment]
It is still confusing for me that issues and PRs on github use the same numbering scheme, although I now see the merits.

**Review by fingolfin — APPROVED** [review]

**Pull request merged**
