### PR TITLE
docu to (most of) #1511

### PR DESCRIPTION
**Pull request by wdecker**
@tthsqe12, @ThomasBreuer I temporarily included the function `strictly_upper_triangular_matrix` in `PBWAlgebra.jl`

### CODE REVIEW

**Comment by tthsqe12** [comment]
Not sure if pasting in the AA code is a good idea. When AA gets updated, we will get a method overwrite here.

**Comment by thofma** [comment]
Are you sure about the overwrite? I don't think we import all AA symbols by default.

**Comment by tthsqe12** [comment]
I think this temp renaming is the way to go

**Comment by thofma** [comment]
@wdecker I updated the AA version. There is some doctest that needs to be adjusted.

**Comment by thofma** [comment]
@wdecker I added your fix. Is this good to go then?

**Comment by wdecker** [comment]
Und the Tests pass, yes!

Von meinem iPhone gesendet

**Pull request merged**
