### PR TITLE
fixed typo Chenese to Chinese

### PR DESCRIPTION
**Pull request by CameronBraunstein**
Basic change meant to make sure I understand the merging system

### CODE REVIEW

**Review by fingolfin — APPROVED** [review]
Thanks! (Actually we should probably fold this whole file into the devdocs and then get rid of it. But that's a separate discussion)

**Comment by fingolfin** [comment]
This PR is marked as draft, so I won't schedule it for merge. If you plan to add further changes, then that's the way to go. If you are "done" with it, though, then just mark it as "ready for review"

**Comment by CameronBraunstein** [comment]
> This PR is marked as draft, so I won't schedule it for merge. If you plan to add further changes, then that's the way to go. If you are "done" with it, though, then just mark it as "ready for review"

It looks as if we are failing the macOS-latest nightly test. Did I need to do something in addition to modifying the text file to make the build succeed

**Comment by thofma** [comment]
This is #1395 and can be ignored.

**Pull request merged**
