### PR TITLE
Hypercomplexes

### PR DESCRIPTION
**Pull request by HechtiDerLachs**
@jankoboehm : As discussed today. The relevant files are exclusively in `experimental/HyperComplexes`. The rest is in #2935 and can be ignored.

### CODE REVIEW

**Comment by HechtiDerLachs** [comment]
@jankoboehm : Did you have time to have a look at this? IMHO it would make sense to subsume double complexes under `AbsHyperComplex` and make them implement the hypercomplex interface. Then we could also introduce a concrete wrapper type for double complexes in parallel to the existing `DoubleComplexOfMorphisms`, which uses a hypercomplex in the background. 

The same could then be done for ordinary `ComplexOfMorphisms` and even `FreeResolution`s. But being defined in Hecke, these can not yet be derived from `AbsHyperComplex`. So we probably do not touch upon this for the moment. What we could do nevertheless, is to rebase `FreeResolution`s on a concrete wrapper type for one-dimensional complexes which is based on the hypercomplexes here.

**Comment by HechtiDerLachs** [comment]
Freshly rebased for better readability.

**Comment by jankoboehm** [comment]
I like it. It does what we discussed. Before interlinking it with double complexes, complexes or resolutions, I think we should get it it. I would then like to test it out in some use cases, also in the one-dimensional setting. We can then discuss carefully about interlinking it with what is there, ensuring compatibility. The goal is that the user does not have to struggle with different types of complexes not interoperating, or operating inconsistently.

**Comment by HechtiDerLachs** [comment]
Rebased again after recent merge of the double complexes.

**Comment by HechtiDerLachs** [comment]
@jankoboehm : As discussed this morning. Hypercomplexes fused with the double complexes. For the fun of it, I also added a concrete type for double complexes which is wrapping a hyper complex. In the example in the test file it seems to perform slightly worse than the native double complex implementation. But since the latter is kept and used, I don't see a problem here.

**Comment by HechtiDerLachs** [comment]
Can this be merged then? Or should we talk about it again on Wednesday?

**Review by fieker — APPROVED** [review]

**Pull request merged**
