### PR TITLE
Tests and cleanup for projective and covered schemes

### PR DESCRIPTION
**Pull request by simonbrandhorst**

### CODE REVIEW

**Comment by simonbrandhorst** [comment]
There is still 

```
function covered_projection_to_base(X::ProjectiveScheme{<:MPolyQuoLocalizedRing})
  if !has_attribute(X, :covered_projection_to_base) 
    C = standard_covering(X)
  end
  return get_attribute(X, :covered_projection_to_base) # TODO: establish type assertion here!
end
```
Which does not seem to function, and is copy pasted 4 times. Yet it seems to be used in some places.

**Comment by HechtiDerLachs** [comment]
I'm trying to understand what you did here. The point was to remove duplicate code? 

The tests seem to go through. Can you be more precise with what you mean by "does not seem to function"? Did it function before your changes and now it's broken? Or was it broken to begin with?

**Comment by simonbrandhorst** [comment]
Add some tests fix bugs and remove duplicate code.  

`covered_projection_to_base` did not make sense to me so I did not touch it so far. 
No clue what it does. Neither was I able to produce a working example. (and of course it is 4x the same code)

**Comment by HechtiDerLachs** [comment]
What it does is that for `X \subset IP^n_A -> Spec(A)` it returns the morphism `X_cov -> Spec(A)` as a morphism of covered schemes, i.e. for `X_cov = as_covered_scheme(X)`. 

It might well be the case that the code is very similar, but I think there were tiny, but important, differences. I will have a look.

**Comment by HechtiDerLachs** [comment]
> Neither was I able to produce a working example.

Just define any projective scheme `X` and ask for its `covered_projection_to_base(X)`. Did anything go wrong there? This should work.

**Comment by simonbrandhorst** [comment]
Well it does not return anything.
```
julia> A = Spec(PolynomialRing(QQ,["t"])[1])
Spec of Multivariate Polynomial Ring in t over Rational Field

julia> X = projective_space(A,2)
subscheme of ℙ^2_{Multivariate Polynomial Ring in t over Rational Field} defined as the zero locus of  ideal(0)

julia> covered_projection_to_base(X)
```

**Comment by simonbrandhorst** [comment]
And apparently it does not work for any subscheme.

```
julia>  P2 = projective_space(QQ,2)
subscheme of ℙ^2_{Rational Field} defined as the zero locus of  ideal(0)

julia> covered_projection_to_base(P2)
ERROR: MethodError: no method matching covered_projection_to_base(::ProjectiveScheme{FlintRationalField, fmpq, MPolyRing_dec{fmpq, FmpqMPolyRing}, MPolyElem_dec{fmpq, fmpq_mpoly}})
```
Which is probably for technical reasons?

**Comment by HechtiDerLachs** [comment]
Yes, the functionality was broken, because we allowed so many new rings. Now it should be fixed. But I saw some other things breaking, already... 

I will look into that tomorrow. 

Edit: For projective schemes over fields, this is simply not implemented. I can not think of anyone needing that, really. For all the other cases, it should work now again.

**Comment by simonbrandhorst** [comment]
It is needed for base change. At least in theory.

**Comment by HechtiDerLachs** [comment]
> It is needed for base change. At least in theory.

Yes, indeed. But probably not as a map to a covered scheme `Spec(k)`. I suggest we look into that once we have a better understanding of how we want to model base change in general.

**Comment by simonbrandhorst** [comment]
Yes. Do you want to do some more cleanup in this ticket or are we good to go? (The doctest failure should be unrelated)

**Review by HechtiDerLachs — APPROVED** [review]
I think, we're good to go for now.

**Pull request merged**
