### PR TITLE
Add lowercase constructor for `Partition`

### LINKED ISSUE #2298: `Partition` needs a `partition` method
We are missing the lowercase version. Maybe an alias? I forgot how we do this for types.

### PR DESCRIPTION
**Pull request by lgoettgens**
Resolves https://github.com/oscar-system/Oscar.jl/issues/2298.

### CODE REVIEW

**Review by fingolfin — APPROVED** [review]
Fine by me

**Review by ulthiel — COMMENTED** [review]
Basically ok, I'm just wondering whether all types are now supposed to be lower case. Here, Partition is really changed everywhere to partition, so there's no Partition anymore!?

**Comment by lgoettgens** [comment]
> Basically ok, I'm just wondering whether all types are now supposed to be lower case. Here, Partition is really changed everywhere to partition, so there's no Partition anymore!?

As far as I understood the big renaming, there should be a distinction between types (Uppercase) and constructors (lowercase), since the latters should be handled as "normal" functions

**Review by ulthiel — APPROVED** [review]

**Comment by thofma** [comment]
Thanks Lars!

**Pull request merged**
