### PR TITLE
add env variable to check if Oscar has been imported in session

### PR DESCRIPTION
**Pull request by kalmarek**
Packages can check if the flag has been defined by defining
```julia
__weareoscar() = haskey(ENV, "WE'RE_OSCAR_NO_BANNERS_PLEASE!")
```

### CODE REVIEW

**Comment by fieker** [comment]
My emails seem to not work, thus trying this way:

what problem is this solving that the current "hack" is not solving?
is it guaranteed to work? Ie. is the setting always going to be evaluated before the dependencies are loaded?

**Comment by kalmarek** [comment]
Just to remind ;-) we're trying to come up a solution to problem we self imposed on us: of not seeing a barrage of banners while loading Oscar.

No, it is not guaranteed to work; But neither is using non-public consts in julia that were not even designed for the purpose and can change without notice. Solution with ENV variable is stable in this regard;

if this does not sway you, please feel free to close this

**Comment by kalmarek** [comment]
and btw. there is even simpler solution that doesn't require ANY modifications to the packages:
```julia
julia> original_stdout = stdout
Base.TTY(RawFD(0x0000000d) open, 0 bytes waiting)

julia> out_rd, out_wr = redirect_stdout()
(Base.PipeEndpoint(RawFD(0x00000012) open, 0 bytes waiting), Base.PipeEndpoint(RawFD(0x00000013) open, 0 bytes waiting))

julia> import Polymake
[ Info: Precompiling Polymake [d720cf60-89b5-51f5-aff5-213f193123e7]

julia> import Nemo

julia> using Oscar
[ Info: Precompiling Oscar [f1435218-dba5-11e9-1e4d-f1a5fab5fc13]
WARNING: import of Hecke.example into Oscar conflicts with an existing identifier; ignored.

julia> Libc.flush_cstdio()

julia> redirect_stdout(original_stdout)
Base.TTY(RawFD(0x0000000d) open, 0 bytes waiting)

julia> close(out_wr)

julia> str = read(out_rd, String); println(str)
polymake version 4.0
Copyright (c) 1997-2020
Ewgenij Gawrilow, Michael Joswig, and the polymake team
Technische Universität Berlin, Germany
https://polymake.org

This is free software licensed under GPL; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.


Welcome to Nemo version 0.17.1-dev

Nemo comes with absolutely no warranty whatsoever

 -----    -----    -----      -      -----   
|     |  |     |  |     |    | |    |     |  
|     |  |        |         |   |   |     |  
|     |   -----   |        |     |  |-----   
|     |        |  |        |-----|  |   |    
|     |  |     |  |     |  |     |  |    |   
 -----    -----    -----   -     -  -     -  

...combining (and extending) GAP, Hecke, Nemo, Polymake and Singular
Version not installed ... 
 ... which comes with absolutely no warranty whatsoever
Type: '?Oscar' for more information
(c) 2019-2020 by The Oscar Development Team


```
which IS guaranteed to work and solves all the problems :P

**Comment by fieker** [comment]
I'll give the env a try. The redirect: Bill and I tried that. THe problem is that we could not figure out how to set up the redirect within Oscar
It works for you as you redirect first, then do using Oscar, ...
The redirect, for us to work, needs to be done in the Oscar.jl - and that we could not get to work. All we tried failed, as teh dependencies were resolved before the 1st line we could get in.
Thats we Rafael, our local julia guru, came up with the current solution.
Yours feels cleaner - but, sorry, I have to see it working first....
Before embarking on a campaign of nested pull requests

**Comment by kalmarek** [comment]
sure, we take the solution that actually works;
did you ask on discourse why redirection fails?

**Comment by fieker** [comment]
On Wed, Apr 15, 2020 at 01:51:47AM -0700, kalmarek wrote:
> sure, we take the solution that actually works;
> did you ask on discourse why redirection fails?
Nope, we just esblished exerimentally, that (almost) nothing is executed
before the dependencies are parsed. Maybe we put it in the wrong spot,
but Bill and I spend a couple of hours before giving up and delegating.
The ENV method seems to work though which is good.

**Comment by fieker** [comment]
On Wed, Apr 15, 2020 at 01:51:47AM -0700, kalmarek wrote:
> sure, we take the solution that actually works;
> did you ask on discourse why redirection fails?

Ahh - I finally solved my confusion... and it appears that the ENV
method is not working...sadly.
OK, the problem:
  the ENV variable is set of not set depending on the whim of julia,
I've printed the keys(ENV) a couple of times.

Scenario:
  setting a key in Oscar.jl, directly after the module start

  Then, if a package needs precompiling, the key is set and I can query
  this to suppress the banner during compiling.
  However, after this, the init() is called again, ane now the ENV is
  not set.

  Then I tried your approach with const show_banner = haskey()
  This (seemed to) work(s), but now the show banner is a const that is
  set the 1st time the the package (pre)-compiler is used.

  Result
   Hecke either always shows the banner - if the pre-compile was
   triggered by a using Hecke directly (now the banner should be there)
   But as the const was set this way, the banner is also printed when
   using Oscar.

   If Hecke is pre-compiler as a result of using Oscar, then the banner
   is suppressed, however, if I try to use Hecke outside of Oscar, the
   banner is still suppressed (the const problem)

So, at this point:
  no const: banner is suppressed in pre-compile, but not in using
  const: banner is either always there - or never

I tried:
  Hecke:
  module Hecke
  ENV["NEMO_PRINT_BANNER"]="false"
  const print_banner = get(ENV, "HECKE_PRINT_BANNER", "true") == "true"

  Oscar:
  module Oscar
  ENV["NEMO_PRINT_BANNER"]="false"
  ENV["HECKE_PRINT_BANNER"]="false"
  ENV["POLYMAKE_PRINT_BANNER"]="false"


(Same is true for Polymake: an indirect compile will suppress the banner
forever..., a direct pre-compile will enable it always)

Any ideas?

**Comment by kalmarek** [comment]
oh, yes, I forgot to update the snippet here, it should be
```julia
__weareoscar() = haskey(ENV, "WE'RE_OSCAR_NO_BANNERS_PLEASE!")
```

but I also noticed some strangeness of ENV with precompilation ;/

**Comment by fieker** [comment]
On Wed, Apr 15, 2020 at 03:34:49AM -0700, kalmarek wrote:
> oh, yes, I forgot to update the snippet here, it should be
> ```julia
> __weareoscar() = haskey(ENV, "WE'RE_OSCAR_NO_BANNERS_PLEASE!")
> ```
> 
> but I also notices some strangeness of ENV with precompilation ;/

No difference, the variable is set properly on pre-compile, but not on
the actual loading...
Did you get it to work?

**Comment by kalmarek** [comment]
the answer is: "hardly ever" :D it worked once or twice, when I tested yesterday, but today I'm no longer able to reproduce it (i.e. it wasn't really working).
Te obvious thing to do is to place the env change in the `__init__()` (this is evaluated always), but imports are evaluated before it ;/

**Comment by fieker** [comment]
On Wed, Apr 15, 2020 at 04:26:43AM -0700, kalmarek wrote:
> the answer is: "hardly ever" :D it worked once or twice, when I tested yesterday, but today I'm no longer able to reproduce it (i.e. it wasn't really working).
> Te obvious thing to do is to place the env change in the `__init__()` (this is evaluated always), but imports are evaluated before it ;/
Indeed - that was our problem also with the redirection... Julia does
not give us a chance of getting in early enough.

Ah well, back to Rafael's hack with the package_locks. At least s.th.
similar needs to stay around for Julia itself...

**Pull request closed without merging**
