### PR TITLE
Simple fixes for sheaf cohomology computation

### PR DESCRIPTION
**Pull request by HechtiDerLachs**
A remake of the first steps in #3238 , only those strictly necessary for the book chapter. 

I will try to make the tests run and then this can be merged.

### CODE REVIEW

**Comment by HechtiDerLachs** [comment]
This weird and scary big GC error struck again. @benlorenz : Sorry to bother you again, but is there anything I should/could do about it? Or are we free to simply ignore this particular failure for the moment?

**Comment by benlorenz** [comment]
> This weird and scary big GC error struck again. @benlorenz : Sorry to bother you again, but is there anything I should/could do about it? Or are we free to simply ignore this particular failure for the moment?

I don't know what do to about it, for now please just ignore it.
If anyone can reproduce this outside of github actions I would be very happy to know how but so far I haven't managed to.

**Comment by HechtiDerLachs** [comment]
Ready to be merged and used for the book, @wdecker, @jankoboehm .

**Review by wdecker — APPROVED** [review]

**Comment by wdecker** [comment]
@fingolfin Can this be merged despite the failing test? If so, please do it, I need this urgently.

**Pull request merged**
