### PR TITLE
Localization docu part ii

### PR DESCRIPTION
**Pull request by HechtiDerLachs**
Promised continuation of #1898 .

### CODE REVIEW

**Comment by HechtiDerLachs** [comment]
I expect the doctests to fail at this moment. But I would like to first see the outcome of all the others and then adjust the doctests later.

**Comment by HechtiDerLachs** [comment]
@wdecker : At some point you were complaining about the printing of homomorphisms from localized rings. I improvised yet another solution. Could you have a look?

**Comment by HechtiDerLachs** [comment]
Please start reviewing already. I will fix the doctests later. If I do this now, this will mess up our "Files changed" up to the unreadable. So unless there are other failures than doctests in the tests, consider this as ripe for merge. 

@fieker , @thofma : @wdecker asked me to ask you to approve the changes made in regard of #1885.

**Comment by thofma** [comment]
I don't know whether someone advocated `/` over `//` in https://github.com/oscar-system/Oscar.jl/issues/1885. The changes here make the localization inconsistent with the ring interface, but this might be changed once we enable `/` for all the other rings.

**Review by wdecker — APPROVED** [review]
Are these done: gen(I, 1)   I[1]?

**Comment by HechtiDerLachs** [comment]
> Are these done: gen(I, 1) I[1]?

The first: Yes. The second: No.

**Comment by afkafkafk13** [comment]
Just in case you missed it:  
"ERROR: function divrem is not implemented for arguments" in the localization doctests
(This was hidden between all the irrelevant doctest errors which are due to changed showing of output.)

**Comment by benlorenz** [comment]
This seems to have [broken](https://github.com/oscar-system/Oscar.jl/actions/runs/4197425327/jobs/7279720948#step:6:770) the tests for julia 1.9 and nightly:
```
printing of ideals and homomorphisms: Error During Test at /home/runner/work/Oscar.jl/Oscar.jl/test/Rings/mpoly-localizations.jl:410
  Test threw exception
  Expression: I[1] == x
  MethodError: no method matching copy(::MPolyLocalizedRingElem{FlintIntegerRing, fmpz, FmpzMPolyRing, fmpz_mpoly, MPolyPowersOfElement{FlintIntegerRing, fmpz, FmpzMPolyRing, fmpz_mpoly}})
  
  Closest candidates are:
    copy(::T) where T<:Union{LinearAlgebra.AdjointFactorization{<:Any, <:SparseArrays.UMFPACK.UmfpackLU}, LinearAlgebra.TransposeFactorization{<:Any, <:SparseArrays.UMFPACK.UmfpackLU}}
     @ SparseArrays /opt/hostedtoolcache/julia/nightly/x64/share/julia/stdlib/v1.10/SparseArrays/src/solvers/umfpack.jl:293
    copy(::T, ::Any) where T<:Union{LinearAlgebra.AdjointFactorization{<:Any, <:SparseArrays.UMFPACK.UmfpackLU}, LinearAlgebra.TransposeFactorization{<:Any, <:SparseArrays.UMFPACK.UmfpackLU}}
     @ SparseArrays /opt/hostedtoolcache/julia/nightly/x64/share/julia/stdlib/v1.10/SparseArrays/src/solvers/umfpack.jl:293
    copy(::Union{CxxWrap.CxxWrapCore.ConstCxxRef{<:CxxWrap.StdLib.WeakPtr{CxxWrap.CxxWrapCore.CxxULongLong}}, CxxWrap.CxxWrapCore.CxxRef{<:CxxWrap.StdLib.WeakPtr{CxxWrap.CxxWrapCore.CxxULongLong}}, CxxWrap.CxxWrapCore.SmartPointer{T2} where T2<:CxxWrap.CxxWrapCore.CxxULongLong})
     @ CxxWrap ~/.julia/packages/CxxWrap/n8sun/src/CxxWrap.jl:610
    ...
  
  Stacktrace:
   [1] getindex(I::MPolyLocalizedIdeal{MPolyLocalizedRing{FlintIntegerRing, fmpz, FmpzMPolyRing, fmpz_mpoly, MPolyPowersOfElement{FlintIntegerRing, fmpz, FmpzMPolyRing, fmpz_mpoly}}, MPolyLocalizedRingElem{FlintIntegerRing, fmpz, FmpzMPolyRing, fmpz_mpoly, MPolyPowersOfElement{FlintIntegerRing, fmpz, FmpzMPolyRing, fmpz_mpoly}}}, k::Int64)
     @ Oscar ~/work/Oscar.jl/Oscar.jl/src/Rings/mpoly-localizations.jl:1481
   [2] macro expansion
     @ /opt/hostedtoolcache/julia/nightly/x64/share/julia/stdlib/v1.10/Test/src/Test.jl:477 [inlined]
   [3] macro expansion
     @ ~/work/Oscar.jl/Oscar.jl/test/Rings/mpoly-localizations.jl:410 [inlined]
   [4] macro expansion
     @ /opt/hostedtoolcache/julia/nightly/x64/share/julia/stdlib/v1.10/Test/src/Test.jl:1502 [inlined]
   [5] top-level scope
     @ ~/work/Oscar.jl/Oscar.jl/test/Rings/mpoly-localizations.jl:401
Test Summary:                        | Pass  Error  Total  Time
printing of ideals and homomorphisms |    5      1      6  3.7s
ERROR: LoadError: Some tests did not pass: 5 passed, 0 failed, 1 errored, 0 broken.
in expression starting at /home/runner/work/Oscar.jl/Oscar.jl/test/Rings/mpoly-localizations.jl:400
in expression starting at /home/runner/work/Oscar.jl/Oscar.jl/test/Rings/runtests.jl:8
in expression starting at /home/runner/work/Oscar.jl/Oscar.jl/test/runtests.jl:31
ERROR: LoadError: Package Oscar errored during testing
```

**Comment by HechtiDerLachs** [comment]
It's really weird. I can not reproduce this error locally on the current master. Hence, I also don't know how to fix it, sorry!

**Comment by benlorenz** [comment]
I do get the same error with julia 1.9.0-beta4 locally:

```
julia> include("test/Rings/mpoly-localizations.jl")
...
Test Summary: | Pass  Total  Time
printing      |    2      2  0.1s
printing of ideals and homomorphisms: Error During Test at /home/lorenz/software/polymake/julia/Oscar.jl/test/Rings/mpoly-localizations.jl:410
  Test threw exception
  Expression: I[1] == x
  MethodError: no method matching copy(::MPolyLocalizedRingElem{FlintIntegerRing, fmpz, FmpzMPolyRing, fmpz_mpoly, MPolyPowersOfElement{FlintIntegerRing, fmpz, FmpzMPolyRing, fmpz_mpoly}})
```

The log also contains:
```
┌ Oscar [f1435218-dba5-11e9-1e4d-f1a5fab5fc13]
│  WARNING: Method definition getindex(Oscar.MPolyLocalizedIdeal{LocRingType, LocRingElemType} where LocRingElemType<:(Oscar.MPolyLocalizedRingElem{BaseRingType, BaseRingElemType, RingType, RingElemType, MultSetType} where MultSetType where RingElemType where RingType where BaseRingElemType where BaseRingType) where LocRingType<:(Oscar.MPolyLocalizedRing{BaseRingType, BaseRingElemType, RingType, RingElemType, MultSetType} where MultSetType<:Oscar.AbsMPolyMultSet{BaseRingType, BaseRingElemType, RingType, RingElemType} where RingElemType where RingType where BaseRingElemType where BaseRingType), Int64) in module Oscar at /home/runner/work/Oscar.jl/Oscar.jl/src/Rings/mpoly-localizations.jl:1470 overwritten at /home/runner/work/Oscar.jl/Oscar.jl/src/Rings/mpoly-localizations.jl:1481.
│    ** incremental compilation may be fatally broken for this module **
│  
│  WARNING: Method definition getindex(Oscar.MPolyQuoLocalizedIdeal{LocRingType, LocRingElemType, MPolyLocalizedIdealType} where MPolyLocalizedIdealType<:(Oscar.MPolyLocalizedIdeal{LocRingType, LocRingElemType} where LocRingElemType<:(Oscar.MPolyLocalizedRingElem{BaseRingType, BaseRingElemType, RingType, RingElemType, MultSetType} where MultSetType where RingElemType where RingType where BaseRingElemType where BaseRingType) where LocRingType<:(Oscar.MPolyLocalizedRing{BaseRingType, BaseRingElemType, RingType, RingElemType, MultSetType} where MultSetType<:Oscar.AbsMPolyMultSet{BaseRingType, BaseRingElemType, RingType, RingElemType} where RingElemType where RingType where BaseRingElemType where BaseRingType)) where LocRingElemType<:(Oscar.MPolyQuoLocalizedRingElem{BaseRingType, BaseRingElemType, RingType, RingElemType, MultSetType} where MultSetType where RingElemType where RingType where BaseRingElemType where BaseRingType) where LocRingType<:(Oscar.MPolyQuoLocalizedRing{BaseRingType, BaseRingElemType, RingType, RingElemType, MultSetType} where MultSetType<:Oscar.AbsMultSet{RingType, RingElemType} where RingElemType where RingType where BaseRingElemType where BaseRingType), Int64) in module Oscar at /home/runner/work/Oscar.jl/Oscar.jl/src/Rings/mpolyquo-localizations.jl:1521 overwritten at /home/runner/work/Oscar.jl/Oscar.jl/src/Rings/mpolyquo-localizations.jl:1528.
│    ** incremental compilation may be fatally broken for this module **
└ 
```

And indeed this (in `src/Rings/mpoly-localizations.jl`) looks weird:
```
1470: getindex(I::MPolyLocalizedIdeal, i::Int) = I.gens[i]
...
1481: getindex(I::MPolyLocalizedIdeal, k::Int) = copy(I.gens[k])
```

Similarly in `src/Rings/mpolyquo-localizations.jl` lines 1521 and 1528.

Removing the one with `copy` in both files seem to help, if you want to keep the `copy` removing the other might help to reproduce the error?

**Comment by HechtiDerLachs** [comment]
Thanks for looking into this! Indeed that code seems pretty weird. I'm wondering whether this was caused by some faulty merge? Either way, I will take care of it and make another small pr later.

**Pull request merged**
