### PR TITLE
Revise how DEV mode is decided

### LINKED ISSUE #213: is_dev tests are not run in CI
Probably should carefully check the code which computes is_dev. While at it, I think we can simplify the part which determines the version of Oscar and make it work the same in old and new Julia versions (not sure if we can do the same for the git_revision, though, but IMHO it's sensible for us to change the version in Project.toml to 0.5.0-dev anyway).

I'll try to dig out the code for this (I used it for a time in GAP.jl for the JLL stuff, but ultimately didn't need it and so removed it again). But I am juggling too many things in my small brain right now and don't want to forget about this, hence filing this as an issue for now.

### PR DESCRIPTION
**Pull request by fingolfin**
Resolves #213

### CODE REVIEW

**Comment by fingolfin** [comment]
Tests currently fail because they use `lift_std` but that's only available in the latest `Singular.jl` master branch, which we cannot yet use here, because Polymake has not yet been updated to use the latest FLINT...

**Comment by fingolfin** [comment]
@fieker : `Examples.galois_group` hangs more or less forever

**Comment by fieker** [comment]
On Fri, Jan 08, 2021 at 01:02:15AM -0800, Max Horn wrote:
> @fieker : `Examples.galois_group` hangs more or less forever
Sorry, but no...
the ModStdQt stuff hange, the Galois groups terminate.
I'll look into this

**Comment by fingolfin** [comment]
Right, I misinterpreted the output, sorry! Still, thanks for looking

**Comment by fieker** [comment]
On Fri, Jan 08, 2021 at 01:20:47AM -0800, Max Horn wrote:
> Right, I misinterpreted the output, sorry! Still, thanks for looking
Progress?
signal (11): Segmentation fault
in expression starting at REPL[10]:1
fmpz_mod at /workspace/srcdir/flint2-2.7.0/fmpz/mod.c:21
_fmpz_vec_scalar_mod_fmpz at
/workspace/srcdir/flint2-2.7.0/fmpz_vec/scalar_mod_fmpz.c:22
fmpz_mod_poly_scalar_mul_fmpz at
/workspace/srcdir/flint2-2.7.0/fmpz_mod_poly/scalar_mul_fmpz.c:29
fmpq_poly_to_fmpz_mod_poly_raw! at
/home/fieker/.julia/dev/Hecke/src/Misc/Poly.jl:523
fmpq_poly_to_fmpz_mod_poly_raw! at
/home/fieker/.julia/dev/Hecke/src/Misc/Poly.jl:517
fmpq_poly_to_fmpz_mod_poly_raw! at
/home/fieker/.julia/dev/Hecke/src/Misc/Poly.jl:517
fmpq_poly_to_fmpz_mod_poly at
/home/fieker/.julia/dev/Hecke/src/Misc/Poly.jl:570 [inlined]
FmpzModPolyRing at
/home/fieker/.julia/dev/Hecke/src/Misc/ResidueRingPoly.jl:203 [inlined]

**Comment by fingolfin** [comment]
@fieker how did you trigger this? By just letting the computation run until it dies? Or something else?

**Comment by fieker** [comment]
On Fri, Jan 08, 2021 at 02:57:24AM -0800, Max Horn wrote:
> @fieker how did you trigger this? By just letting the computation run until it dies? Or something else?

It's now understood (this error): it was, in Hecke, a missing adjustment
to the new flint fmpz_mod_poly module

**Comment by fingolfin** [comment]
So we discovered a bug, and can fix it, great! CI tests FTW :-)

**Comment by thofma** [comment]
I pushed a new version of Hecke. Now some tests in mpoly-graded.jl fail, but I am not familiar with the singular_ring stuff.

**Comment by thofma** [comment]
I have fixed the `singular_ring` issues and bumped the Hecke version. This now includes https://github.com/thofma/Hecke.jl/pull/123, but the tests in `ModStdQt-test.jl` were still hanging. I have disabled them for now.

**Comment by thofma** [comment]
Can we merge this? Would be good to get those tests into CI.

**Pull request merged**
