### PR TITLE
Experimental

### PR DESCRIPTION
**Pull request by fieker**
start of moving files fomr examples -> experimental for a slightly more official home
why merging does not work: no idea...

### CODE REVIEW

**Comment by wbhart** [comment]
You need to do a rebase.

git checkout master
git pull
git checkout experimental
git rebase master

follow the instructions. It can also be done visually on GitHub by clicking the Resolve conflicts button. Look for the lines of arrows and replace with the version you want. Someone else apparently made changes that were incompatible with yours, so you have to work out which version is correct or write a new version that keeps both parties happy.

**Comment by fieker** [comment]
On Mon, Feb 01, 2021 at 07:44:23AM -0800, wbhart wrote:
> You need to do a rebase.
> 
> git checkout master
> git pull
> git checkout experimental
> git rebase master
> 
> follow the instructions. It can also be done visually on GitHub by clicking the Resolve conflicts button. Look for the lines of arrows and replace with the version you want. Someone else apparently made changes that were incompatible with yours, so you have to work out which version is correct or write a new version that keeps both parties happy.
> 

All done - I was certain, I did a pull -r on master before I started,
but s.o. pushed in between, or I was too slow.

"all" is "fine" now.

**Comment by fingolfin** [comment]
Unfortunately there are still unresolved conflicts

**Comment by fingolfin** [comment]
Maybe you are pulling master from the wrong remote (eg your own fork instead of the main one at oscar-system)?

**Pull request merged**
