### PR TITLE
Edit especially ugly occurences of `is*` and `n*`

### PR DESCRIPTION
**Pull request by lkastner**
This PR does some renaming for variants of
- `is*` to `is_*` in case there is an underscore in the `*` part
- for counting functions `n*` to `n_*` in the same setting.

I only edited the toric varieties and polyhedral geometry part here. Also note that this is even incomplete there, I did not change all `is*` according to the new styleguide.

### CODE REVIEW

**Review by fingolfin — COMMENTED** [review]
Fine by me, but this is of course a breaking change. So we either change the version to 0.8.0-DEV in this PR; or else we need to use `@deprecate` liberally...

**Comment by lkastner** [comment]
Are there more versions that will need bumping?

**Comment by fingolfin** [comment]
Please don't use @ nicks in commit messages -- they trigger many notifications to the user in question (here: me)

**Review by benlorenz — APPROVED** [review]
The new names are way better, thanks!

**Pull request merged**
