### PR TITLE
Form groups

### PR DESCRIPTION
**Pull request by GDeFranceschi**
Just a test.
Do not merge.

### CODE REVIEW

**Comment by thofma** [comment]
I see hermitian forms, which usually require an automorphism of the field. But I am not able to find where an automorphism is supplied.

**Comment by GDeFranceschi** [comment]
> I see hermitian forms, which usually require an automorphism of the field. But I am not able to find where an automorphism is supplied.

For finite fields of order `q^2k`, there is only one involutory field automorphism, that is `a --> a^(q^k))`.

**Comment by thofma** [comment]
If this is only for finite fields, the names of the types should reflect this.

**Comment by GDeFranceschi** [comment]
Probably I can restrict the type to `FinField`.

**Comment by thofma** [comment]
Ok.

**Comment by fingolfin** [comment]
Now that forms has been merged, this PR needs to be rebased

**Pull request closed without merging**
