### PR TITLE
move SLpoly in Oscar

### PR DESCRIPTION
**Pull request by rfourquet**
It seems like a more natural place to live in than in `StraightLinePrograms`. It was a bit of work to disentangle, but will probably make it easier to maintain the `SLPoly` type.

A couple of `SLPoly` tests had to be disabled because they were written for AA version 0.9 (it's v0.11 now). I will fix that in a follow-up PR.

### CODE REVIEW

**Comment by rfourquet** [comment]
On nightly I get this error failure:
```
InitError: could not load library "/home/runner/.julia/artifacts/860a8b2216bd059600ed7c44cdaa3bb81b23ff1c/lib/libcxxwrap_julia.so"
libjulia.so.1: cannot open shared object file: No such file or directory
```
I closed and re-opened to see whether this would be cleared up today (answer: no), and I get now errors with coveralls:
```
Error:  "2020-12-05T09:28:31.033Z"  'error from getOptions'
Error: Error: Command failed: git cat-file -p 9ac2464555756be92569fdf2c2ff2e3a6618692f
fatal: Not a valid object name 9ac2464555756be92569fdf2c2ff2e3a6618692f
```
Have someone already seen this kind of error on CI?

**Comment by thofma** [comment]
> On nightly I get this error failure:
> 
> ```
> InitError: could not load library "/home/runner/.julia/artifacts/860a8b2216bd059600ed7c44cdaa3bb81b23ff1c/lib/libcxxwrap_julia.so"
> libjulia.so.1: cannot open shared object file: No such file or directory
> ```

At the moment jlls are flaky on julia master. I think they are still ironing out some problems.

> I closed and re-opened to see whether this would be cleared up today (answer: no), and I get now errors with coveralls:
> 
> ```
> Error:  "2020-12-05T09:28:31.033Z"  'error from getOptions'
> Error: Error: Command failed: git cat-file -p 9ac2464555756be92569fdf2c2ff2e3a6618692f
> fatal: Not a valid object name 9ac2464555756be92569fdf2c2ff2e3a6618692f
> ```
> 
> Have someone already seen this kind of error on CI?

No, but I have a lot of experience with coveralls.

**Comment by fieker** [comment]
What is the status? Can this be merged? Can I create PolynomialRing(SLPolynomialRing()) now? Print (however badly - that can be imporved in a second step) but error free?

**Comment by rfourquet** [comment]
> What is the status? Can this be merged? 

I think this can be merged, but CI failing is annoying. I will try once more closing-opening to see if this fails again.

> Can I create PolynomialRing(SLPolynomialRing()) now? Print (however badly - that can be imporved in a second step) but error free?

Here I only changed the home for `SLPoly` and `SLPolyRing`, other fixes will come once this gets merged.

**Comment by fieker** [comment]
On Tue, Dec 08, 2020 at 03:22:47AM -0800, Rafael Fourquet wrote:

S = slpoly_ring(QQ, :x=>1:3)
St, t = PolynomialRing(S);

This might help:

Oscar.elem_type(::Type{SLPolyRing{S, T}}) where {S, T} = SLPoly{S, SLPolyRing{S, T}}
Oscar.parent_type(::Type{SLPoly{S, T}}) where {S, T} = T
Oscar.normalise(a::SLPoly, ::Int) = a
Oscar.iszero(a::SLPoly) = false
Oscar.isone(a::SLPoly) = false
Oscar.mul!(a::SLPoly, b::SLPoly, c::SLPoly) = b*c

helps, but
the show is still missing
and
julia> prod(t-y for y = gens(S))
ERROR: ArgumentError: unable to coerce polynomial
Stacktrace:
 [1] SLPolyRing at
 /home/fieker/.julia/dev/Oscar/src/Rings/slpolys.jl:125 [inlined]
 [2] PolyRing at
 /home/fieker/.julia/dev/AbstractAlgebra/src/generic/Poly.jl:2965 [in

**Pull request merged**
