### PR TITLE
Fix (work around...) #784

### PR DESCRIPTION
**Pull request by joschmitt**
Here is a trivial fix for #784 .
I don't know whether this is the best thing to do, but I would like to stop hacking around the issue.

### CODE REVIEW

**Comment by thofma** [comment]
Looks ok. Would it also work to make the method with the ring the default one?

**Comment by joschmitt** [comment]
Sure, as far as I can say. I'm actually surprised that there is a method `ideal(...)` where you don't have to specify the ring.

**Comment by joschmitt** [comment]
Sorry, should I change this or do we wait for somebody else's opinion?

**Comment by thofma** [comment]
I guess it is a bit more work. Maybe just add a TODO.

**Review by thofma — APPROVED** [review]

**Pull request merged**
