### PR TITLE
Return isomorphism in isomorphic_matrix_group_over_finite_field

### PR DESCRIPTION
**Pull request by thofma**

### CODE REVIEW

**Review by joschmitt — APPROVED** [review]
Looks good to me!

**Comment by joschmitt** [comment]
But all this should be done in the background when the user wants to work with a char 0 matrix group, right? How do we want to do this or where do we cache the char p group?

**Comment by fingolfin** [comment]
The way I'd do it is to use GAP's `NiceMonomorphism` system to inform GAP about the reduction, in the GAP group generated by the Oscar matrices in char 0. See my comment in https://github.com/oscar-system/Oscar.jl/pull/538#discussion_r673856914 and before/after that. I'll write more later.

**Comment by thofma** [comment]
Nothing in this regard has happened since we merged the first PR, but we need it now to move forward with the invariant theory and/or with the subgroups for matrix groups in characteristic 0.

I believe what you suggest can be added later?

**Comment by thofma** [comment]
> But all this should be done in the background when the user wants to work with a char 0 matrix group, right? How do we want to do this or where do we cache the char p group?

Yes, this is just for internal use and yes, we should cache this on the char. 0 matrix group.

**Pull request merged**
