### PR TITLE
Wolfram

### PR DESCRIPTION
**Pull request by wdecker**

### CODE REVIEW

**Comment by wdecker** [comment]
I guess I need help here

**Comment by thofma** [comment]
Sind deine Änderungen nur die hier: https://github.com/oscar-system/Oscar.jl/pull/509/commits/9e260b8b658ebfb408c2da23e6de46c23cc56d76?

**Comment by wdecker** [comment]
ja

**Comment by thofma** [comment]
OK. That should do it. I will merge once all the lights are green.

**Comment by wdecker** [comment]
Can someone please help with the Ferret problem showing in the docu build check

**Comment by thofma** [comment]
This is not related.

The problem is the warning about the duplicated docstring (it is include twice).

**Pull request merged**
