### PR TITLE
IntersectionTheory

### PR DESCRIPTION
**Pull request by jieaosong**
Here is a first draft for moving IntersectionTheory to Oscar. Things that already work can be found in the test file (no blowup yet).

I used Oscar's `MPolyRing_dec` and `MPolyQuo` for the Chow rings, but it becomes a bit hard to keep track of the differences between the two (like `R.R` vs `R.R.R` or `x.f` vs `x.f.f`...). So I'm a bit keen to create a custom ring structure, with an optional field `R.I` for the ideal.

### CODE REVIEW

**Comment by thofma** [comment]
Could you expand on your last comment about `R.R` and `R.R.R` etc? If there is a common concept to both types, there should be a function doing what you want (if not, it should be added).

**Comment by wdecker** [comment]
The types of graded resp. quotient rings are still in flux and under discussion. Suggestions based on applications such as computing in Chow rings are most welcome.

**Comment by jieaosong** [comment]
> Could you expand on your last comment about `R.R` and `R.R.R` etc? If there is a common concept to both types, there should be a function doing what you want (if not, it should be added).

Yes I guess some functionalities are still missing. Here are some of the issues I found:

* `homogeneous_components` when used on a quotient element returns elements in the ambient ring
```julia
julia> R, (x, y) = grade(PolynomialRing(QQ, ["x", "y"])[1]);

julia> Q = quo(R, ideal([x^2, y]))[1];

julia> homogeneous_components(Q[1])
Dict{GrpAbFinGenElem, MPolyElem_dec{fmpq, fmpq_mpoly}} with 1 entry:
  [1] => x
```
* No function to retrieve the degrees of the generators of R or Q, so one must use `R.d` or `Q.R.d`.
* The gradings are not very easy to use. In particular since the abelian group used in the gradings is not cached, one must retrieve it using `R.D` or `Q.R.D`.
```julia
julia> Z = abelian_group([0])
GrpAb: Z

julia> R.D
GrpAb: Z

julia> R.D == Z
false

julia> homogeneous_component(x, Z([1]))
ERROR: Elements must belong to the same group
```
* If one works with the underlying non-graded ring, elements cannot be coerced into Q directly (easy to fix).
```julia
julia> R.R[1]
x

julia> R(R.R[1])
x

julia> Q(R.R[1])
ERROR: AssertionError: parent(a) == Q.R
```

**Comment by jieaosong** [comment]
@thofma Hi! I mentioned that I'm probably going to keep my ring type for the Oscar migration. But just for comparison I rebased my branch on Oscar master (this branch currently has a partial implementation using Oscar's graded / quotient rings). So here are some issues with the latest graded / quotient ring in Oscar.

1. Some promotions are broken. Notably between `fmpz` and `MPolyElem_dec{fmpq, fmpq_mpoly})`. I manually fixed it with 
```julia
function AbstractAlgebra.promote_rule(::Type{MPolyElem_dec{T, S}}, ::Type{U}) where {T <: RingElement, S <: RingElement, U <: RingElement}
  AbstractAlgebra.promote_rule(S, U) === S ? MPolyElem_dec{T, S} : Union{}
end
```
(Also I learned that AA's `promote_rule` is not the same as `Base.promote_rule`...)

2. A more serious issue is that the code runs significantly slower now. I have the following piece of code that constructs a Chow ring and does some arithmetic in it.
```julia
using Oscar
using Oscar.IntersectionTheory
@time G = flag(1,6,10,bott=false); A,B,C = G.bundles; @time integral(chern(dual(A*exterior_power(2,B)+A*B*C)))
```
Before rebase
```julia
  0.722267 seconds (433.69 k allocations: 8.915 MiB)
  2.913104 seconds (25.74 M allocations: 459.096 MiB, 7.92% gc time)
990
```
After
```julia
128.310077 seconds (1.40 G allocations: 26.138 GiB, 14.37% gc time)
 53.300904 seconds (575.27 M allocations: 10.723 GiB, 14.08% gc time, 0.03% compilation time)
990
```
I'm not sure what's the problem yet.

**Comment by thofma** [comment]
Do you by any chance have the branch before rebasing?

**Comment by jieaosong** [comment]
Actually I did the rebase locally so this is still the branch before rebasing.

For the rebase I dropped the first commit which is already fixed in Oscar. Essentially all the diff of the second commit are new files in the IntersectionTheory folder and they are not changed at all. So you could also just use an earlier version of Oscar and copy the files to there.

**Comment by thofma** [comment]
I am having a look.

**Comment by thofma** [comment]
Should be fixed by #698.

**Comment by thofma** [comment]
How far are we from getting this merged @8d1h? :)

**Comment by thofma** [comment]
@8d1h We are still excited to have this functionality in Oscar and thus are planning to revamp this PR here. There is no need for any work on your part, but let us know if you foresee problems or have any objections.

**Pull request closed without merging**
