### PR TITLE
bump dep versions

### PR DESCRIPTION
**Pull request by tthsqe12**

### CODE REVIEW

**Comment by tthsqe12** [comment]
@thofma there are still some unfortunates in hecke, but I assume this is not a big deal.
```
julia> using Nemo
Welcome to Nemo version 0.27.0-dev
julia> typeof(factor(2^2^5+1))
Fac{Int64}
```
```
julia> using Oscar
julia> typeof(factor(2^2^5+1))
Fac{fmpz}
```

**Comment by thofma** [comment]
Did this change?

**Comment by tthsqe12** [comment]
I don't think it changed. Here is oscar 0.6.0 *not* deved:
```
julia> typeof(factor(2^2^5+1))
Fac{fmpz}
julia> typeof(Oscar.Nemo.factor(2^2^5+1))
Fac{Int64}
```
I would be inclined to say the return should be of type Fac{Int} for Int input.

**Comment by thofma** [comment]
Bump the AA version to 0.22.1

**Comment by tthsqe12** [comment]
Do we want this bump as is? I didn't mean for the unfortunate `factor(Int) -> Fac{fmpz}` that I pointed out to hold up anything as this is a feature of oscar that is neither caused nor fixed by this bump.

**Pull request merged**
