### PR TITLE
Adv/upgrade regression fix

### PR DESCRIPTION
**Pull request by antonydellavecchia**
Fixes a regression in the upgrade script, and fixes test for upgrades that allowed said regression.

Also adds comment in error message when trying to serialize an unsupported type.

### CODE REVIEW

**Comment by thofma** [comment]
Who should review this?

**Comment by thofma** [comment]
Who should review this?

**Comment by antonydellavecchia** [comment]
> Who should review this?

@benlorenz looked at it this week, and we decided we wanted to pretty print
the files in the data folder. I am currently working on change the format for some of them so I can deal with pretty printing the files the another pull request, and then we can just merge

**Review by benlorenz — APPROVED** [review]

**Comment by thofma** [comment]
OK, then just merge at your own discretion.

**Comment by lgoettgens** [comment]
backport?

**Pull request merged**
