### PR TITLE
More test coverage and fixes

### PR DESCRIPTION
**Pull request by simonbrandhorst**

### CODE REVIEW

**Comment by simonbrandhorst** [comment]
@afkafkafk13 please merge

**Review by afkafkafk13 — APPROVED** [review]

**Comment by afkafkafk13** [comment]
> @afkafkafk13 please merge

@simonbrandhorst : Booktests fail. Please have a look at it: something is creating huge amounts of output there.

**Comment by benlorenz** [comment]
> > @afkafkafk13 please merge
> 
> @simonbrandhorst : Booktests fail. Please have a look at it: something is creating huge amounts of output there.

The booktest failure looks like https://github.com/oscar-system/Oscar.jl/issues/3633, which might get fixed with some upcoming new GAP builds. I have restarted the job.

**Comment by afkafkafk13** [comment]
> > > @afkafkafk13 please merge
> > 
> > 
> > @simonbrandhorst : Booktests fail. Please have a look at it: something is creating huge amounts of output there.
> 
> The booktest failure looks like #3633, which might get fixed with some upcoming new GAP builds. I have restarted the job.

Thank you for the hint. Then this has to wait until the bug is fixed as the failing test is blocking.

**Pull request merged**
