### PR TITLE
Introduce bibtool CI test

### PR DESCRIPTION
**Pull request by HereAround**
A first proposal following the discussion in https://github.com/oscar-system/Oscar.jl/issues/1773.

cc @fingolfin @thofma

### CODE REVIEW

**Comment by thofma** [comment]
Could you add a commit here which triggers a failure? Just for testing purposes.

**Comment by HereAround** [comment]
https://github.com/oscar-system/Oscar.jl/pull/1807/commits/8acb99eb6c6b6cb2596f1a582577b4a6939b07f1 ~~will cause~~ causes a failure.

**Review by fingolfin — APPROVED** [review]
Looks good to me, though of course we should wait to see if it detects the failure (and then remove the cause for the failure etc., whatever ;-)

**Comment by HereAround** [comment]
> Looks good to me, though of course we should wait to see if it detects the failure (and then remove the cause for the failure etc., whatever ;-)

Thank you @fingolfin . Yes, I will of course remove this dummy commit. I assume @thofma just wanted to check that this test detects a failure.

**Comment by HereAround** [comment]
Btw. the bibtool test has already detected the failure as introduced in https://github.com/oscar-system/Oscar.jl/commit/8acb99eb6c6b6cb2596f1a582577b4a6939b07f1 for test purposes. This test completes - as we should expect - very quickly (at most a few minutes). It could be even faster if we did not have to install `bibtool` on the server.

**Comment by thofma** [comment]
Yes, looks good. Could you separate the installation step from the actual test? Then there is less output if it fails.

**Comment by HereAround** [comment]
> Yes, looks good. Could you separate the installation step from the actual test? Then there is less output if it fails.

Done. Also removed the dummy commit (I assume we have all seen that this leads to a failure.)

**Review by thofma — APPROVED** [review]

**Pull request merged**
