### PR TITLE
Fix for module ordering conversion

### LINKED ISSUE #4303: Gröbner basis for modules
**Describe the bug**
While computing some Gröbner bases for modules I encountered some differences between documentation and behaviour in Oscar. It seems like the Gröbner basis is not computed with respect to the requested module ordering. In the example below it looks like during the computation of  `groebner_basis` and `leading_module` the ordering `invlex(M)*deglex(R)` is replaced by `lex(M)*deglex(R)` and therefore does not return a correct result.

**To Reproduce**
```
julia> R,_ = polynomial_ring(QQ, 1, :t);

julia> M = free_module(R, 3);

julia> ord = invlex(M)*deglex(R);

julia> g1 = 2M[1] + M[3];

julia> leading_term(g1, ordering=ord)
e[3]

julia> g2 = M[1] + M[2] + M[3];

julia> leading_term(g2, ordering=ord)
e[3]

julia> U,_ = sub(M, [g1, g2])
(Submodule with 2 generators
  1: 2*e[1] + e[3]
  2: e[1] + e[2] + e[3]
represented as subquotient with no relations, Hom: U -> M)

julia> G = groebner_basis(U, ordering=ord)
Gröbner basis with elements
e[3] + 2*e[2]
e[3] + e[2] + e[1]
 with respect to the ordering
invlex([gen(1), gen(2), gen(3)])*deglex([t1])

julia> LG,_ = sub(M, [leading_term(G[i], ordering=ord) for i=1:length(G)])
(Submodule with 2 generators
  1: e[3]
  2: e[3]
represented as subquotient with no relations, Hom: LG -> M)

julia> LU = leading_module(U, ord)
Submodule with 2 generators
  1: 2*e[2]
  2: e[1]
represented as subquotient with no relations

julia> LG == LU
false
```

**Expected behavior**
The expected result can currently be computed by the following, mathmatically wrong code by replacing `invlex(M)*deglex(R)` with `lex(M)*deglex(R)`.
```
julia> G1 = groebner_basis(U, ordering=lex(M)*deglex(R))
Gröbner basis with elements
-e[1] + e[2]
e[1] + e[2] + e[3]
 with respect to the ordering
lex([gen(1), gen(2), gen(3)])*deglex([t1])

julia> LG1,_ = sub(M, [leading_term(G1[i], ordering=ord) for i=1:length(G)])
(Submodule with 2 generators
  1: e[2]
  2: e[3]
represented as subquotient with no relations, Hom: LG1 -> M)

julia> LU1 = leading_module(U, lex(M)*deglex(R))
Submodule with 2 generators
  1: e[2]
  2: e[3]
represented as subquotient with no relations

julia> LG1==LU1
true
```
**Version Information**
```
julia> Oscar.versioninfo(full=true)
OSCAR version 1.3.0-DEV - #master, b3ab222d48 -- 2024-11-12 10:38:02 +0100
  combining:
    AbstractAlgebra.jl   v0.43.10
    GAP.jl               v0.12.0
    Hecke.jl             v0.34.6
    Nemo.jl              v0.47.3
    Polymake.jl          v0.11.22
    Singular.jl          v0.23.10
  building on:
    FLINT_jll               v300.100.300+0
    GAP_jll                 v400.1300.102+2
    Singular_jll            v404.0.606+0
    libpolymake_julia_jll   v0.13.0+0
    libsingular_julia_jll   v0.46.0+0
    polymake_jll            v400.1300.2+0
See `]st -m` for a full list of dependencies.

Julia Version 1.7.3
Commit 742b9abb4d (2022-05-06 12:58 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-12.0.1 (ORCJIT, skylake)
Official https://julialang.org/ release
```

**Additional context**
The same problem also occurs with the orderings `deglex(R)*lex(M)` and `deglex(R)*invlex(M)`.

### PR DESCRIPTION
**Pull request by Syz-MS**
Fixes #4303. 
According to the [Oscar documentation](https://docs.oscar-system.org/dev/CommutativeAlgebra/GroebnerBases/orderings/#Module-Orderings) and [Singular manual](https://www.singular.uni-kl.de/Manual/4-3-2/sing_980.htm) the module orderings should be converted as followed:
 `:lex`        ->   `Singular.ordering_c`
 `:invlex`   ->   `Singular.ordering_C`
This was swapped in the code.

### CODE REVIEW

**Comment by Syz-MS** [comment]
Marked as draft for breaking every test and doctest that relies on module orderings for objects being ordered and displayed in a certain way.

**Comment by afkafkafk13** [comment]
I fear that the problem is significantly larger than just exchanging the positions of `c` and `C` in the translation.

Several people obviously stumbled into this in the past when debugging their own code, but were unaware of the underlying translation problem leading them to the conclusion that they had chosen the wrong Oscar-ordering for their purpose and then using the other one.

**Comment by Syz-MS** [comment]
@afkafkafk13 are we allowed to change the default ordering for modules on the Oscar side to match the default ordering on the Singular side? 
This would fix the conversion problem for module related objects when the ordering is ignored. With some small code changes the tests (except book test) and doctests are now working.

**Comment by afkafkafk13** [comment]
> @afkafkafk13 are we allowed to change the default ordering for modules on the Oscar side to match the default ordering on the Singular side? This would fix the conversion problem for module related objects when the ordering is ignored. With some small code changes the tests (except book test) and doctests are now working.

Changing the default ordering (as ordering, not as symbol) would be a major change and cannot be done without thorough discussion with @ederc and @jankoboehm and others. On the other hand, you are NOT changing the default ordering, but correcting it back to the ordering (not the symbol) that is currently being used, whereas the correct default ordering was changed by correcting the translation table for the symbols to match the definition, right?

**Comment by Syz-MS** [comment]
> On the other hand, you are NOT changing the default ordering, but correcting it back to the ordering (not the symbol) that is currently being used, whereas the correct default ordering was changed by correcting the translation table for the symbols to match the definition, right?

You are partially correct. For every computation that happens on the Singular side I am just correcting it to the ordering currently being used. Some examples for this would be using `groebner_basis` and `leading_module` without a specified ordering.

Wheras if the computation happens purely in Oscar I have changed the ordering from current default ordering e.g. when using `leading_term`, `terms` without a specified ordering.  This is actually the reason for the failing book test.

**Comment by afkafkafk13** [comment]
No. We are not free to change the default ordering in Oscar. There were reasons for this choice and it is used in the Oscar-book.

Instead, we need to look at the lowlevel methods for preparing data for Singular and add the means to pass an ordering to the corresponding Singular objects. (Just (C,...), (c,...),(...,C) and (...,c) -- nothing fancy, which cannot be represented on the Singular side anyway. The fancy staff, which also includes ways to translate more elaborate module orderings in suitable ways, is not as urgent, but the core functionality on module orderings in Singular should be accessible from Oscar in a clean way. Can we talk about this on Wednesday morning?

**Comment by Syz-MS** [comment]
Wednesday morning is fine by me.

**Comment by joschmitt** [comment]
With #4379 merged, is this obsolete now?

**Comment by afkafkafk13** [comment]
obsoleted by #4379

**Comment by joschmitt** [comment]
Thank you very much @Syz-MS for reporting this and working on it!

**Pull request closed without merging**
