### PR TITLE
alg options for integral_basis

### PR DESCRIPTION
**Pull request by tthsqe12**

### CODE REVIEW

**Comment by thofma** [comment]
Maybe test all of the options as well as passing a wrong one.

**Review by wdecker — CHANGES_REQUESTED** [review]
With the algorithm choice `alg = :normal_local`, the function relies on the
local-to-global approach to normalization presented in [BDLPS19](@cite).

@tthsqe12 Thx for doing this.  Please repace in the above [BDLPS19](@cite) by [BDLPSS13](@cite) (sorry, my mistake).

Otherwise, fine with me.

**Comment by tthsqe12** [comment]
@wdecker so you would like `alg=:hensel` to be the default even though it doesn't work over GF(2)?

**Comment by wdecker** [comment]
@tthsqe12   Sorry, no, I overlooked `alg=:hensel`as default. The default should be `alg = :normalLocal`

**Comment by wdecker** [comment]
Looks good to me and can be merged!

**Pull request merged**
