### PR TITLE
fix some nesting bugs

### PR DESCRIPTION
**Pull request by tthsqe12**
There is now a bug somewhere in Nemo or Hecke that prevents the doc example from even working, so I haven't changed the doc test.

```julia
julia> using Oscar

julia> Qa, a = PolynomialRing(QQ, :a=>1:2)

julia> R, X = PolynomialRing(FractionField(Qa), :X=>1:2)

julia> f = (X[1]^2+a[1]*X[2]^2)*(X[1]+X[2]+a[1]+a[2])

julia> z = factor_absolute(f)
ERROR: Incompatible polynomial rings in polynomial operation
Stacktrace:
  [1] error(s::String)
    @ Base ./error.jl:33
  [2] check_parent
    @ ~/.julia/packages/AbstractAlgebra/2tNNk/src/generic/Poly.jl:76 [inlined]
  [3] check_parent
    @ ~/.julia/packages/AbstractAlgebra/2tNNk/src/generic/Poly.jl:75 [inlined]
  [4] gcd(x::fmpq_poly, y::fmpq_poly)
    @ Nemo ~/.julia/packages/Nemo/ZPSws/src/flint/fmpq_poly.jl:517
  [5] rational_reconstruction_mod(g::fmpq_poly, f::fmpq_poly, bnd::Int64; ErrorTolerant::Bool)
    @ Hecke ~/.julia/packages/Hecke/dyUKa/src/Misc/RatRecon.jl:259
  [6] #rational_reconstruction#903
    @ ~/.julia/packages/Hecke/dyUKa/src/Misc/RatRecon.jl:52 [inlined]
  [7] #rational_reconstruction#4
    @ ~/.julia/dev/Oscar/experimental/ModStd/ModStdQt.jl:82 [inlined]
  [8] interpolate(Val::Oscar.ModStdQt.Vals{fmpq}, M::Oscar.ModStdQt.MPolyInterpolateCtx{fmpq})
    @ Oscar.ModStdQt ~/.julia/dev/Oscar/experimental/ModStd/ModStdQt.jl:190
  [9] macro expansion
    @ ~/.julia/dev/Oscar/experimental/ModStd/ModStdQt.jl:712 [inlined]
 [10] macro expansion
    @ ~/.julia/packages/Hecke/dyUKa/src/Hecke.jl:594 [inlined]
 [11] afact(g::fmpq_mpoly, a::Vector{Int64}; int::Bool)
    @ Oscar.ModStdQt ~/.julia/dev/Oscar/experimental/ModStd/ModStdQt.jl:709
 [12] afact
    @ ~/.julia/dev/Oscar/experimental/ModStd/ModStdQt.jl:619 [inlined]
 [13] factor_absolute(f::AbstractAlgebra.Generic.MPoly{AbstractAlgebra.Generic.Frac{fmpq_mpoly}})
    @ Oscar.ModStdQt ~/.julia/dev/Oscar/experimental/ModStd/ModStdQt.jl:567
 [14] top-level scope
    @ REPL[5]:1

julia> 
```

### CODE REVIEW

**Comment by thofma** [comment]
So we could enable the doctest again?

**Comment by tthsqe12** [comment]
no, we can't because the code doesn't work. I don't know how to fix the bug that occurs in Nemo/Hecke.

**Comment by thofma** [comment]
So what does this PR here fix? I don't see a test, so I am not sure.

**Comment by tthsqe12** [comment]
It fixes
https://github.com/oscar-system/Oscar.jl/blob/d1c1cb5b47eaf70b92eafbadbe530c97e6d7b321/experimental/ModStd/ModStdQt.jl#L574

I will investigate the parent bug and try to add it to this pr.

**Comment by thofma** [comment]
Sorry, I overlooked that, thanks.

**Comment by tthsqe12** [comment]
@thofma, @fieker The bug is here in oscar probably.
```julia
mutable struct InterpolateCtx{T}
  C::Hecke.crt_env{T}
  function InterpolateCtx(a::Vector{S}, parent = PolynomialRing(parent(a[1]), cached = false)[1]) where {S}
    bt = parent
    t = gen(bt)
    r = new{elem_type(bt)}()
    r.C = Hecke.crt_env([t - i for i = a])
    return r
  end
end
```

Since it is with `cached = false` when it gets in Hecke as
```julia
function crt(b::Array{T, 1}, a::crt_env{T}) where T
  res = zero(b[1])
  return crt!(res, b, a)
end
```

the `zero` function is going to call AA's zero which gets to Nemo's similar
```julia
function similar(f::PolyElem, R::FlintRationalField, var::Symbol=var(parent(f)); cached::Bool=true)
   z = fmpq_poly()
   z.parent = FmpqPolyRing(R, var, cached)
   return z
end
```

The point is, here `z.parent != f.parent` since `f.parent` was created uncached.

How many of our functions assume that the polynomial rings were created cached? :(

**Comment by tthsqe12** [comment]
This can be fixed by putting cached = true, but:
Maybe this is a bug in AA/Nemo, since how could it ever be reasonable to have `parent(zero(e)) != parent(e)` for an element `e` (regardless of how its parent was constructed)?

**Comment by thofma** [comment]
This is not a problem with caching or not. This is a bug in `zero`.

https://github.com/Nemocas/AbstractAlgebra.jl/issues/897

(A quick workaround would be `zero(parent())` instead of `zero()`)

**Comment by thofma** [comment]
I bumped the Hecke version. Can you try again and enable the docstring?

**Comment by fieker** [comment]
The caching needs to be false. We're going to have fun with the new?,
correct? Zero...

**Comment by tthsqe12** [comment]
I will try again.

**Pull request merged**
