### PR TITLE
Taking up intersection theory again

### PR DESCRIPTION
**Pull request by wdecker**
With @thofma, we will extend the functionality with regard to abstract intersection theory in Oscar, produce examples, document this part of Oscar, and, finally, move it out of experimental. This is the first PR in this direction. Along our way, discussions on naming identifiers, on how the math is reflected in the code, and on explaining the math in the docu is most welcome.

### CODE REVIEW

**Comment by thofma** [comment]
@wdecker ping me once you are happy with the status and I will adjust some internal things.

**Comment by wdecker** [comment]
@ederc  Can you please have a look at this test: Run tests / doctest (1.10, macOS, RPTU). Is the a randomness problem? Or?

**Comment by ederc** [comment]
I have no idea why this happening. I cannot reproduce the problem, neither on Apple Silicon nor on x64 Linux.

**Comment by wdecker** [comment]
@thofma From my point of view, this is fine now for you to adjust things. However, I do not understand the mistakes appearing in the tests (seemingly unrelated to what we do).

**Comment by thofma** [comment]
yeah, I think we can ignore those things

**Comment by thofma** [comment]
@wdecker I checked and the failure is not our fault. Since this only touches upon stuff in experimental, I will merge soon if there are no complaints.

**Review by ederc — APPROVED** [review]

**Pull request merged**
