### PR TITLE
small adjustment docu `isnormal`

### PR DESCRIPTION
**Pull request by wdecker**

### CODE REVIEW

**Comment by wdecker** [comment]
I do not understand the errors appearing here: Run tests / test (1.6, x64, ubuntu-latest) (pull_request) 
They have nothing to do with my changes and should, thus, have already appeared earlier. 
Also, why do they not appear in this test as well: Documentation / deploy_docs (pull_request) 
Is there some new element of randomness somewhere?

**Comment by benlorenz** [comment]
The `isnormal` function changes some global options in Singular which affect the output of other doctests:
```julia
julia> R, (x, y) = PolynomialRing(QQ, ["x", "y"]);

julia> RR, (xx, yy, zz) = PolynomialRing(QQ, ["x", "y", "z"]);

julia> A, _ = quo(RR, ideal(RR, [zz^2-xx*yy]));

julia> Singular.libSingular.call_interpreter("option();")[2]
"//options: redTail redThrough intStrategy usage prompt\n"

julia> isnormal(A)
true

julia> Singular.libSingular.call_interpreter("option();")[2]
"//options: redSB returnSB redTail redThrough intStrategy usage prompt\n"

julia> syzygy_generators([x^3+y+2,x*y^2-13*x^2,y-14])
4-element Vector{FreeModElem{fmpq_mpoly}}:
 (-y + 14)*e[2] + (-13*x^2 + x*y^2)*e[3]
 (13*x*y - 182*x - y^3 + 14*y^2)*e[1] + (x^2*y - 14*x^2)*e[2] + (-13*x*y - 26*x + y^3 + 2*y^2)*e[3]
 (13*x^2 - x*y^2)*e[1] + (x^3 + y + 2)*e[2]
 (-y + 14)*e[1] + (x^3 + y + 2)*e[3]

julia> Singular.libSingular.set_option("OPT_REDSB", false);

julia> Singular.libSingular.set_option("OPT_RETURN_SB", false);

julia> Singular.libSingular.call_interpreter("option();")[2]
"//options: redTail redThrough intStrategy usage prompt\n"

julia> syzygy_generators([x^3+y+2,x*y^2-13*x^2,y-14])
3-element Vector{FreeModElem{fmpq_mpoly}}:
 (-y + 14)*e[2] + (-13*x^2 + x*y^2)*e[3]
 (-169*y + 2366)*e[1] + (-13*x*y + 182*x - 196*y + 2744)*e[2] + (13*x^2*y^2 - 2548*x^2 + 196*x*y^2 + 169*y + 338)*e[3]
 (-13*x^2 + 196*x)*e[1] + (-x^3 - 16)*e[2] + (x^4*y + 14*x^4 + 13*x^2 + 16*x*y + 28*x)*e[3]
```

Before this change the code in the ` ```repl ` block was not executed. (I am not sure why the deploy_docs didn't fail as well.)

**Comment by tthsqe12** [comment]
This is a bug if the isnormal function is indeed changing the global options.

**Comment by wdecker** [comment]
@benlorenz Thx for pointing this out!

**Comment by hannes14** [comment]
should be fixed with https://github.com/Singular/Singular/commit/74622283ad46295f0602f84dc752ccf62f699461

**Comment by fingolfin** [comment]
So we need a new Singular_jll and then also a nw libsingular_julia_jll for other reasons

**Comment by tthsqe12** [comment]
If we want something that works here right away, the two offending options can be queried and restored in the oscar code (for the time being).

EDIT: maybe this not the best idea because there are at least 5 options (redSB returnSB redTail redThrough intStrategy) that need restoring after isnormal is called.

**Comment by tthsqe12** [comment]
So this is turning out to be a bit more complicated than I expected:

If you run the oscar test code, you will see that the options start out as
`//options: usage prompt`
then end up at least as
`//options: redTailSyz redTail redThrough intStrategy usage prompt`
Calls to, for example, `kernel` and `preimage` in the `Polynomial homs` section of `mpoly-test.jl` are (at least) responsible for these changes.

After reading the documentation https://www.singular.uni-kl.de/Manual/4-3-0/sing_318.htm#SEC358 it seems that a simple change of base ring can set options?
If options can be set behind the scenes(!), how can we know with what options a particular computation is being done?

It seems like the whole setting of the base ring in some parts of Singular.jl need to be accompanied by some switches in options as well...

**Comment by benlorenz** [comment]
I think it should be ok to just reset `redSB` and `returnSB` after the isnormal call to their previous values (and to ignore the "ring dependent" options for now). For the example that is failing here `returnSB` is the important one.

**Comment by wdecker** [comment]
> I think it should be ok to just reset `redSB` and `returnSB` after the isnormal call to their previous values (and to ignore the "ring dependent" options for now). For the example that is failing here `returnSB` is the important one.

Can someone please do this, I am away from my desk right now.

**Comment by tthsqe12** [comment]
I will try it here

**Comment by wdecker** [comment]
From my point of view, this can be merged now.

**Pull request merged**
