### PR TITLE
Extending docu on PBW-algebras as template for @tthsqe12

### PR DESCRIPTION
**Pull request by wdecker**
Introductory remarks on opposite PBW algebras

### CODE REVIEW

**Comment by tthsqe12** [comment]
Do you agree with the following? I guess the relations of B are in the revlex (rp) order.
```
julia> R, (x,y,z) = QQ["x", "y", "z"];

julia> L = [2*x*y + 3*z*y, 4*x*z + 5*z*y, 4*y*z + z^3+z+1];

julia> A, (x,y,z) = pbw_algebra(R, strictly_upper_triangular_matrix(L), lex(gens(R)))
(PBW-algebra over Rational Field in x, y, z with relations y*x = 2*x*y + 3*y*z, z*x = 4*x*z + 5*y*z, z*y = 4*y*z + z^3 + z + 1, PBWAlgElem{fmpq, Singular.n_Q}[x, y, z])

julia> B = opposite(A)
PBW-algebra over Rational Field in z, y, x with relations y*z = z^3 + 4*z*y + z + 1, x*z = 5*z*y + 4*z*x, x*y = 3*z*y + 2*y*x

julia> B.sring
Singular G-Algebra (QQ),(Z,Y,X),(rp(3),C)
```

**Comment by wdecker** [comment]
@tthsqe12 
- Where is this example from?
- After entering `B = opposite(A)`, and then, say, `f = 3*x^2+z*y`, is `f` an element of `B` or `A`. Put differently, should we allow that the user to pick names for the variables of the opposite algebra? Or should we stick to the Singular convention?

**Comment by thofma** [comment]
Just adding my two cents here: There is already a function `opposite_algebra`, which works for finite-dimensional algebras and returns the opposite algebra as well as the corresponding anti-isomorphism. What do you think about changing the name to `opposite_algebra`?

Regarding returning the anti-isomorphism. I found it handy to do `B, f = opposite_algebra(A)` followed by a `f(I)`, where `I` is a (left/right/two-sided) ideal of `A`. But I have no strong opinion. If we don't want `opposite_algebra` to return the map, I would just add `opposite_algebra_with_map` in addition.

**Comment by wdecker** [comment]
> Just adding my two cents here: There is already a function `opposite_algebra`, which works for finite-dimensional algebras and returns the opposite algebra as well as the corresponding anti-isomorphism. What do you think about changing the name to `opposite_algebra`?
> 
> Regarding returning the anti-isomorphism. I found it handy to do `B, f = opposite_algebra(A)` followed by a `f(I)`, where `I` is a (left/right/two-sided) ideal of `A`. But I have no strong opinion. If we don't want `opposite_algebra` to return the map, I would just add `opposite_algebra_with_map` in addition.

@thofma I agree with both suggestions. In fact, I would have suggested using `opposite_algebra` myself. Adding the anti-isomorphism and using it as suggested solves another problem I was thinking about. Can you provide an explicit example of how this works for finite-dimensional algebras? In particular, how is this implementation related to the questions on variables which I asked above?

**Comment by wdecker** [comment]
@thofma By the way: How about documenting what is there on finite dimensional algebras and add this to what we do here.

**Comment by thofma** [comment]
> By the way: How about documenting what is there on finite dimensional algebras and add this to what we do here.

Yes, we should add it to the documentation.

Follow-up question: Do you want `opposite_algebra` to always return the map or do you prefer `opposite_algebra` to only return the algebra and `opposite_algebra_with_map` to return the algebra and the map? I am leaning towards the second option but have no strong opinion.

Regarding the example. I did not implement `f(I)` for an ideal of the algebra (because I never had a use for it so far), but it works for other "sub-structures":

```julia
julia> A = matrix_algebra(QQ, 2);

julia> B, f = opposite_algebra(A);

julia> R = Order(A, basis(A)); # this is the subring M_2(Z) of A

julia> f(R); # transport R to B
```

Here is another example with a group algebra `QQ[G]` for some finite group `G`. Here we return `QQ[G]` itself (the identical object) as the opposite algebra and the anti-isomorphism is induced by `g -> g^-1`:
```julia
julia> G = abelian_group([2, 2]);

julia> A = QQ[G]
Group algebra of group
GrpAb: (Z/2)^2
over
Rational Field

julia> B, f = opposite_algebra(A);

julia> B === A
true
```

There is not much with variables/generators/names for these algebras going on.

In your above example, after doing `B = opposite(A)`, the element `f =  3*x^2+z*y` is an element of `A`. The only way to reassign `x, y, z` is by having them explicitly on the LHS of an `=` sign. We cannot reassign them automatically. So I guess we either return them directly or the user has to do `x, y, z = gens(B)` afterwards.

Maybe one more remark. Going by textbook, the opposite algebra has the same underlying set as the algebra one starts with. But this a bit awkward in a computer algebra system using the element/parent system, since an element cannot be an element of the algebra and its opposite unless both are the same objects in the system. So I take the viewpoint that an opposite algebra is an algebra which is anti-isomorphic to the input algebra (as illustrated by the example). The important information is then the anti-isomorphism. I have the impression that you are doing something similar, maybe with the additional requirement that for PBW-algebras, the opposite algebra is again a PBW-algebra and *the* generators are mapped to *the* generators under the anti-isomorphism.

**Pull request merged**
