### PR TITLE
Replace convert function

### PR DESCRIPTION
**Pull request by raulepure**
I removed the conversion via convert(R, x) and replaced it by the conversion via R(x).
This PR relies on oscar-system/Singular.jl#356

### CODE REVIEW

**Comment by wbhart** [comment]
I merged the Singular.jl PR this relies on, but the tests here still fail. I guess a new version of AA is also needed.

**Comment by raulepure** [comment]
I'm not sure. I ran the tests on my computer and here the tests pass.
The error from the checks is the same I obtained when the fix was not in Singular.jl. Does the check use the dev Version of Singular.jl or another one?

**Comment by wbhart** [comment]
It'll use whatever version is in the Project.toml file.

**Comment by raulepure** [comment]
I did a clean install of Oscar and I figured out, that this PR needs a dev version of Singular.jl. Can this be fixed somehow, or do I just have to wait until the next Singular.jl release?

**Comment by wbhart** [comment]
If it requires things not in the latest version of Singular.jl there is no point merging them, or Oscar.jl will break. So you have to wait for (or help with) the next Singular release. In the mean time, simply use the dev version on your machine so you can continue working.

**Comment by fingolfin** [comment]
We now have the latest Singular. However, there is also a merge conflict now, probably because @fingolfin just merged PR #242. So this will have to be rebased

**Review by fingolfin — APPROVED** [review]
Looks good to me, except of course it needs to be rebased

**Comment by raulepure** [comment]
I will have a look at it this afternoon after my exercise class and do the rebase. It seems that I just have to adapt the new mpoly-quo.jl and delete the quotient data in mpoly.jl.

**Comment by fingolfin** [comment]
I took the liberty of splitting your changes into two different commits: one containing the `convert` related changes; and a second with the two new coercions you added. Finally I added a commit of my own which tweaks the codecov settings, to see if I can get better reporting here.

**Pull request merged**
