### PR TITLE
Msolve fixes

### LINKED ISSUE #1431: latest version of msolve (msolve_jll v0.2.5+0) seems to be buggy
@ederc 
the tests are all failing now c.f. 
https://github.com/oscar-system/Oscar.jl/pull/1429
https://github.com/oscar-system/Oscar.jl/pull/1427

If not buggy, then at least the tests are invalid. However, it is also easy to crash it
```
julia> using Oscar
julia> R, (x1,x2,x3) = PolynomialRing(QQ, ["x1", "x2", "x3"])

julia> I = ideal(R, [x1+2*x2+2*x3-1, x1^2+2*x2^2+2*x3^2-x1, 2*x1*x2+2*x2*x3-x2]); msolve(I);
Fixes info level to no output.

signal (11): Segmentation fault
in expression starting at REPL[3]:1
cfree at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
msolve_julia at /workspace/srcdir/msolve/src/msolve/msolve.c:5648
#msolve#739 at ~/.julia/dev/Oscar/src/Rings/msolve/msolve.jl:114
msolve at ~/.julia/dev/Oscar/src/Rings/msolve/msolve.jl:80
_jl_invoke at /buildworker/worker/package_linux64/build/src/gf.c:2247 [inlined]

```

### PR DESCRIPTION
**Pull request by ederc**
Updates msolve to version 0.3.0, should fix #1431.

### CODE REVIEW

**Comment by thofma** [comment]
Thanks for the quick fix! Unfortunately this does not help with the problem that anyone using Oscar version 0.8.2--0.10.0 might/will now have a broken Oscar. Broken in the sense that the tests don't pass and anything relying on msolve will fail.

@fingolfin Should we try to unbreak the previous versions or just merge this here and tag a 0.10.1?

**Comment by fingolfin** [comment]
I would suggest to also unbreak existing releases by submitting a PR to the General registry which removes the offending version(s) of msolve_jll. I would also be happy to release Oscar 0.10.1 ASAP. In the future, if we always hardcode specific msolve_jll versions, we should be good; drawback: any bug fixes in msolve_jll then also will require a new Oscar release... so even better would be to keep using dependencies like "msolve 0.3.x", and get msolve to follow semver... but I am not sure whether @ederc and collaborators are open to that? As a minor incentive, I know that many other consumers will love you for following semver.

**Comment by fingolfin** [comment]
See https://github.com/JuliaRegistries/General/pull/63483

**Comment by ederc** [comment]
In general we follow semver, but one of my collaborators broke the interface without knowing and I just assumed that the msolve_jll.jl version was hardcoded in Oscar. Our bad, but in general things should work also from our side.

**Comment by fingolfin** [comment]
@ederc excellent, that's great to know. And yeah, accidents happen of course, no bad feelings from my side. Thank you for taking care of it so quickly!

**Pull request merged**
