### PR TITLE
let `iso_gap_oscar` choose `Nemo._GF`

### PR DESCRIPTION
**Pull request by ThomasBreuer**
see #1987 for the background

### CODE REVIEW

**Comment by ThomasBreuer** [comment]
That's funny: The test failure means that the finite field that is now chosen by `iso_gap_oscar` behaves better than the previously chosen one; thus I have to change a test in order to really get an error.

**Comment by fingolfin** [comment]
A few doctests need to be adjusted

**Comment by thofma** [comment]
There is no need for the "dance" with `p < 2^64` and `degree == 1` or not. `_GF` and `_FiniteField` do this automatically.

One other thing. The new finite fields come also in a relative version, so that the use of `degree(F)` etc in the `_iso_oscar_gap_field_finite_functions` a bit problematic is:
```julia
julia> F = Hecke.Nemo._GF(2, 2);

julia> Fx, x = F["x"]
(Univariate Polynomial Ring in x over Finite field of degree 2 over F_2, x)

julia> f = x^3 + x + 1
x^3 + x + 1

julia> FF, = Hecke.Nemo._FiniteField(f)
(Finite field of degree 6 over F_2 (over Finite field of degree 2 over F_2), o)

julia> degree(FF)
3

julia> absolute_degree(FF)
6
```
I just noticed that `modulus` is doing the wrong thing:
```julia
julia> modulus(FF)
T^6 + T^4 + T^3 + T + 1

julia> defining_polynomial(FF)
x^3 + x + 1
``` 
(I will fix this in Nemo)

**Comment by fingolfin** [comment]
Woa, `modulus` for finite fields is really weird. As @ThomasBreuer just pointed out to me: it is not really clearly defined what it is (as such: I am happy that @thofma says with confidence it "is doing the wrong thing" as I am not sure what it is supposed to do). But there are more issues. Let's look at one of them, from Nemo:
```
@doc Markdown.doc"""
    modulus(k::fqPolyRepField, var::String="T")

Return the modulus defining the finite field $k$.
"""
function modulus(k::fqPolyRepField, var::String="T")
    p::Int = characteristic(k)
    Q = polynomial(GF(p), [], var)
    P = ccall((:fq_nmod_ctx_modulus, libflint), Ref{fpPolyRingElem},
                 (Ref{fqPolyRepField},), k)
    ccall((:nmod_poly_set, libflint), Nothing,
          (Ref{fpPolyRingElem}, Ref{fpPolyRingElem}),
          Q, P)

    return Q
end
```
So "the modulus defining the finite field $k$ is unclear. I guess a hint that this is a polynomial $f$ such that $parent(f)/(f)$ is isomorphic to $k$  would be helpful (assuming that what it is). In so far it seems consistent:
```
julia> f1 = modulus(FF)
T^6 + T^4 + T^3 + T + 1

julia> parent(f1)
Univariate Polynomial Ring in T over Galois field with characteristic 2

julia> base_ring(parent(f1))
Galois field with characteristic 2

julia> order(coefficient_ring(parent(f1)))
2
```
and
```
julia> f2 = defining_polynomial(FF)
x^3 + x + 1

julia> parent(f2)
Univariate Polynomial Ring in x over Finite field of degree 2 over F_2

julia> order(coefficient_ring(parent(f2)))
4
```
at least seem consistent to me?


But then also `var::String="T"`  raises eyebrows: Why aren't symbols also allowed? And  shouldn't it allow passing in an existing polynomial ring (instead or in addition of the name of a variable)?

**Comment by ThomasBreuer** [comment]
@thofma Thanks for your comments.

Concerning `_iso_oscar_gap_field_finite_functions`, I have now added a check that the Oscar field is an extension of a prime field. (The analogous check for the GAP field had been already there.)

**Review by thofma — APPROVED** [review]

**Comment by thofma** [comment]
Thanks @ThomasBreuer

**Pull request merged**
