### PR TITLE
Removes singular_assure() calls from mpoly-local implementation

### PR DESCRIPTION
**Pull request by ederc**
See #1920.

### CODE REVIEW

**Review by joschmitt — DISMISSED** [review]
Looks good to me.
Stupid question though: is anyone using this code? From what I can see, in the algebraic geometry code people seem to use the stuff from `mpoly-localizations.jl`.

**Comment by ederc** [comment]
> Looks good to me. Stupid question though: is anyone using this code? From what I can see, in the algebraic geometry code people seem to use the stuff from `mpoly-localizations.jl`.

I have no idea. We discussed the `singular_assure()` issue on Wednesday, no one from the Geometry crew wanted the code to be removed. In the end I do not care.

**Comment by joschmitt** [comment]
I'm just wondering how much more time and energy we (or more precisely you) should put into this, if this code could just go.

@wdecker @HechtiDerLachs @afkafkafk13 @simonbrandhorst @jankoboehm does anybody know about the status of this file? Why do we have `MPolyLocRing` and `MPolyRingLoc`?

**Comment by HechtiDerLachs** [comment]
I will make a PR to remove `src/Rings/mpoly-local.jl` if that's OK with everybody. 

If you disagree: Please speak up!

**Comment by afkafkafk13** [comment]
> I will make a PR to remove `src/Rings/mpoly-local.jl` if that's OK with everybody.
> 
> If you disagree: Please speak up!

I am not against it, but I would like to ask you to pay special attention not to break the following functionalities:
- duValSing.jl
- SpaceGerms.jl (in particular rational_point_coordinates)
- Tjurina.jl

from experimental/src/Schemes. I hope that everything is consistent, but these are the parts where the local ordering are used. If something breaks, then it will most probably be visible there.

**Comment by afkafkafk13** [comment]
This will most probably be obsoleted by #3790

**Pull request closed without merging**
