### PR TITLE
Start using AbstractAlgebra.@attr

### PR DESCRIPTION
**Pull request by fingolfin**

### CODE REVIEW

**Comment by fingolfin** [comment]
Unfortunately I've uncovered a bunch of issues with `@attr`, and we'll probably have to revise it :-/. Anyway, I am collecting more data for now.

**Comment by thofma** [comment]
I thought about it during the week and wondered how it could work at all (I was thinking about what is when parsed/compiled/run). Do you already know what the problem is?

**Comment by fingolfin** [comment]
See https://github.com/Nemocas/AbstractAlgebra.jl/pull/1114 (work in progress)

**Comment by fingolfin** [comment]
This is ready now @HereAround @lkastner 

i did not convert all places yet because they might conflict with your big renaming PR

**Comment by fingolfin** [comment]
This is ready now @HereAround @lkastner 

i did not convert all places yet because they might conflict with your big renaming PR

**Review by lkastner — APPROVED** [review]
This is very cool, thank you.

If that is ok, we can change the remaining occurences later in @HereAround s PR.

**Comment by fingolfin** [comment]
@HereAround told me on Slack that I should just merge and do all the changes as he'll have to update this PR anyway

**Comment by HereAround** [comment]
Thank you @fingolfin!

**Pull request merged**
