### PR TITLE
LieAlgebras: Constructions for module homs

### PR DESCRIPTION
**Pull request by lgoettgens**
~~This builds upon https://github.com/oscar-system/Oscar.jl/pull/2644 and thus includes that PR. Once https://github.com/oscar-system/Oscar.jl/pull/2644 gets merged, I will rebase this PR.~~

Introduces new constructions for Lie algebra module homs:

- [x] injections/projections for direct sums
- [x] `hom_tensor`
- [x] `hom_direct_sum`
- [x] lift hom $V \to W$ to $T^k V \to T^k W$
- [x] lift hom $V \to W$ to $\bigwedge^k V \to \bigwedge^k W$
- [x] lift hom $V \to W$ to $S^k V \to S^k W$

While doing that, refactor the constructions of the modules and put more helpful stuff in attribute storage:

- [x] direct sum
- [x] tensor product
- [x] tensor power
- [x] exterior power
- [x] symmetric power

More changes:
- [x] add `is_welldefined` to be able to check that even if using `check=false` in the `hom` constructor
- [x] add `zero_map`
- [x] change the internals of modules to use right multiplication with a matrix as the action

Missing: 
- [ ] Handle 0-th powers

### CODE REVIEW

**Comment by fieker** [comment]
is there any reason to not bind hom_tensor and hom_direct_sum to hom as well? As in
hom(M, N, V) for M and N being tensor products: call hom_tensor, for both being ...?

**Comment by lgoettgens** [comment]
> is there any reason to not bind hom_tensor and hom_direct_sum to hom as well? As in hom(M, N, V) for M and N being tensor products: call hom_tensor, for both being ...?

I am not sure if I understand you correctly. Are you proposing to add `hom_tensor` (and `hom_direct_sum`) instead as methods to `hom`?
As similar functions (`hom_tensor` and `hom_product`) already exist for `ModuleFP`, I would keep it here for the time being as is, and then discuss your proposal in a new issue for both `ModuleFP` and `LieAlgebraModule`.

**Comment by lgoettgens** [comment]
There is a little bit of cleanup possible once https://github.com/thofma/Hecke.jl/pull/1196 is available.

**Review by fingolfin — APPROVED** [review]
Looks good to me, thanks

**Pull request merged**
