### PR TITLE
devdocs: add a preamble to the code formatting section

### PR DESCRIPTION
**Pull request by fingolfin**
These are unwritten rules I try to adhere to myself. But I know not everyone agrees.

So, I think we should have written rules -- I am offering these as a starting point for a discussion, and then the project leads can hopefully agree on some revised version.

CC @fieker @micjoswig @simonbrandhorst @thofma @wdecker

### CODE REVIEW

**Comment by simonbrandhorst** [comment]
I agree with the change. Thank you for taking care of this. 
What is less clear to me is who is the "stakeholder" of a particular piece of code and what are the rights and obligations of a stakeholder.  We could try to formulate a code of conduct? For instance I would say that if one does a non-trivial change in the "stakeholders" code, they should be contacted and given a minimum of 1 week time to react (depending on how far reaching the change is). Finally the "rights" of any stakeholder are limited. Once the code is contributed to Oscar I dare say that one gives up most rights (for instance the copy right). 
Edit: The discussion can probably wait until we have some more time. I can keep it in mind and bring it up on some occasion.

**Review by micjoswig — APPROVED** [review]
The word I like most in this paragraph is "lax".

Please keep in mind: once rules become too strict, over time, they usually become a layer of bureaucracy; with all its drawbacks.

The thing is: not every aspect of software development is well reflected on github, despite all its issues, pull requests, reviews etc.  I'd say the best thing that we have to sort out stuff is our regular zoom meeting.  If people intend to make changes which affect several areas of our beloved system, then it is best to make announcements there.  This way we can coordinate.

Keep up the good work!

**Comment by fingolfin** [comment]
@simonbrandhorst I deliberately used "stakeholder" and not "author" or something like that. And I also don't want to overly formalize this (I think a code of conduct is actually counter productive in this regard, it tends to ossify things in my impression). I mean it quite literally, looking at the definition given at https://www.merriam-webster.com/dictionary/stakeholder :
1. a person entrusted with the [stakes](https://www.merriam-webster.com/dictionary/stakes) of bettors
2. one that has a [stake](https://www.merriam-webster.com/dictionary/stake) in an enterprise
3. one who is involved in or affected by a course of action

Since there are no bettors or enterprises involved here, it is the third meaning I have in mind: that may include the original authors of a piece of code (but only if they are still around and active), but really what I have in mind is "anybody working on that code or using it extensively". Now for code reformatting, if you are purely a user of some code, you likely won't mind (or even notice) if it is reformatted. So really it is about people working on that code "recently", who may have open PRs touching the code (which can be broken by reformatting) or who might be currently working on a PR, having a local branch that just hasn't been submitted. For these people it can be super frustrating if suddenly a code reformatting change gets in the way.

To find out who might be a stakeholder, this is what I would do:
1. use my memory as to what I recall about who worked on some code (e.g. for group theory, I assume everyone who has been around a bit will eventually figure out that Thomas and me work a lot on that),
2. check the relevant section in the manual for who is listed as contact for some code (to stick with my example: `docs/src/Groups/intro.md` lists Thomas and me)
3. ask around on Slack or our meetings,
4. look through open PRs as to whether any touch those files,
5. check `git` to figure out who "recently" worked on a given file or directory. E.g. for the groups theory code:
```
$ git shortlog -sn --since=2024-01-01 src/Groups/
    34  Thomas Breuer
    20  Max Horn
    14  Lars Göttgens
     6  Johannes Schmitt
     4  Tommy Hofmann
     2  Morgan Rodgers
     1  Erik Paemurru
     1  Stevell Muller
```

**Review by fieker — APPROVED** [review]
Please keep in mind that our core buisness is mathematics, not software... and in particular: research mathematics

**Review by simonbrandhorst — APPROVED** [review]

**Comment by simonbrandhorst** [comment]
I am fine with keeping things informal.

**Comment by fingolfin** [comment]
@thofma do you have any thoughts on this?

**Review by thofma — APPROVED** [review]

**Pull request merged**
