### PR TITLE
Normalization output is now a triple

### PR DESCRIPTION
**Pull request by paemurru**
Everything done.

### CODE REVIEW

**Comment by thofma** [comment]
Is `normalization` an exported function that exists in version 1.0?

**Comment by simonbrandhorst** [comment]
It is an exported function and existed in 1.0 but with a different signature (e.g. only for affine algebras).
This one taking schemes as input was added about 2 weeks ago in #3494
If there was no Oscar release in between, a deprecation should not be necessary?

**Comment by thofma** [comment]
Yes, in this case everything is fine. Just wanted to double check.

**Comment by simonbrandhorst** [comment]
> Yes, in this case everything is fine. Just wanted to double check.

Thanks for double checking :-)

**Comment by afkafkafk13** [comment]
@paemurru : from my perspective this looks good!
What do you plan to add further to this PR? As soon as the docstrings are available and tests for the new functionality are running, this seems ready for approval/merging.

**Comment by paemurru** [comment]
I have now added everything that I planned.

I would have preferred if in my `disjoint_union` example one of the schemes is an affine scheme, but apparently the function `covered_scheme` cannot be applied to affine schemes.

**Review by simonbrandhorst — APPROVED** [review]

**Pull request merged**
