### PR TITLE
Align `all_*_groups` methods some more

### PR DESCRIPTION
**Pull request by fingolfin**
For `all_small_groups` we allow specifying the order as a single
integer or abstract vector, followed by any number of additional
filters. For transitive and primitive groups, we also allowed
specifying the degree as a single integer or abstract vector, but
this then could not be followed by filters. With this patch the
additional filters work in all cases.

Depends on PR #3404 (which has already been merged), so this PR here can only be backported after PR #3404.

### CODE REVIEW

**Comment by lgoettgens** [comment]
primitive and transitive groups were both changed similarly in https://github.com/oscar-system/Oscar.jl/pull/3404, so it would make sense to add a similar change to primitive groups here as well.

Regarding the backport: https://github.com/oscar-system/Oscar.jl/pull/3404 is not yet backported. So backporting this here will create ugly conflicts.

**Review by lgoettgens — APPROVED** [review]

**Comment by fingolfin** [comment]
@lgoettgens thank you! I stumbled over this for transitive groups today while working on the book, and instead of checking, blindly assumed that primitive groups followed the small groups... Argh.

Anyway, fixed now, also adjusted the commit message / PR description.


As for the backporting: yes, this should only be backported if and after PR #3404 is backported.

**Comment by lgoettgens** [comment]
When I worked on https://github.com/oscar-system/Oscar.jl/pull/3404, I should have looked at all the `all_*_groups` implementations (including the small groups) to make it completely consistent. I cannot remember how I overlooked them.

**Comment by fingolfin** [comment]
@lgoettgens well, when I reviewed PR #3404 I should have thought "wait a moment, ....", looked at those other methods, and told you about them. :-) but I didn't, I thought "this is fine". If there is any "blame" (if one wants to use that word, I don't really) it is on me, not you :-)

**Pull request merged**
