### PR TITLE
A few toric fixes and additions

### PR DESCRIPTION
**Pull request by HereAround**
* Support functionality for trivial line bundle on toric variety.
* Fix a typo in the documentation.
* Remove some (presumably?) outdated comments in the documentation.

### CODE REVIEW

**Review by lkastner — APPROVED** [review]

**Comment by HereAround** [comment]
Those failures in the intersection theory/abstract varieties are surprising. @thofma any ideas?

**Comment by thofma** [comment]
The PR here adds `trivial_line_bundle`, which breaks `IntersectionTheory` (since `FTheoryTools` is loaded first). It now needs to be imported in `IntersectionTheory`. Adding a line at https://github.com/oscar-system/Oscar.jl/blob/master/experimental/IntersectionTheory/src/IntersectionTheory.jl#L9 should fix it.

**Comment by HereAround** [comment]
To clarify, there are no changes to FTheoryTools in this PR, but rather in the Oscar source on toric geometry. Still, seems that this needs importing in the file you mentioned. I will try to fix that.

**Comment by thofma** [comment]
I see. The cure is the same.

**Comment by HereAround** [comment]
> I see. The cure is the same.

Thank you. Just fixed it (or so I believe).

**Pull request merged**
