### PR TITLE
[WIP] try imap for MPolyElem

### PR DESCRIPTION
**Pull request by tthsqe12**
@wdecker
I will try to separate two distinct issues with what I see as a convenience function mirroring singular's imap:
1. What it does for the user: the interface is as in the test code: `embed_names` or whatever name is most appropriate is called on two rings to create the mapping, which can be applied to polys from the domain.
2. What is does under the hood: The current implementation uses a new type and is lightweight. Do we really want to eventually create a `AlgHom{T}` and all of its baggage?

### CODE REVIEW

**Comment by thofma** [comment]
I don't like the ad hoc overloading for ideals. We should coordinate this with the other map types. Also @fieker and I discussed the possibility of using `m.(I)` for the case where `parent(I) != domain(m)` but there is a canonical induced map.

**Comment by thofma** [comment]
How does this differ from the functionality implemented already here: https://github.com/oscar-system/Oscar.jl/blob/master/src/Rings/mpoly.jl#L863-L927?

**Comment by tthsqe12** [comment]
Ok, that basically does the same thing: It throws instead of mapping missing variables to zero.
I will be deleting some code soon.

**Comment by thofma** [comment]
Wasn't yours more efficient?

**Comment by tthsqe12** [comment]
No. It just had the possibility of mapping the bad guys to zero. But, I think that is a bad idea.
The allocations in MPolyHom_vars can be reduced (ie moved out of the loop), but this is not a big deal.

**Comment by HechtiDerLachs** [comment]
Not sure whether this belongs here, but today I have encountered the following related issue:

phi = AlgebraHomomorphism( R, S, list_of_images_of_generators )
I = ideal( R, some_elements )
phi(I)

the last line seems not to be implemented, yet. Is that correct? 

If yes, that would definitely be a functionality that will be useful in the future.

**Comment by fieker** [comment]
On Thu, Jul 15, 2021 at 02:27:43AM -0700, HechtiDerLachs wrote:
> Not sure whether this belongs here, but today I have encountered the following related issue:
> 
> phi = AlgebraHomomorphism( R, S, list_of_images_of_generators )
> I = ideal( R, some_elements )
> phi(I)
> 
> the last line seems not to be implemented, yet. Is that correct? 
> 
Its also a mixture...we need a common mechanism to extend maps. This
accors e.g. R -> R[x], R -> matrices, R -> ideals
For proper homomorphisms, this is "easy", however for partial maps like
reduce mod p this is not clear...

We need it...

**Comment by tthsqe12** [comment]
Closing this because I don't see any way to make progress here and because this should be solved by a much more general map interface.

**Pull request closed without merging**
