### PR TITLE
Deprecate coeffs

### PR DESCRIPTION
**Pull request by wbhart**
This is the Oscar.jl equivalent of https://github.com/Nemocas/AbstractAlgebra.jl/pull/805

Obviously this won't pass until that PR is merged, and possibly others in the series.

### CODE REVIEW

**Comment by thofma** [comment]
Rebased and fixed some problems. This is waiting for https://github.com/oscar-system/Singular.jl/pull/396.

**Comment by thofma** [comment]
This is good to go. Should not be delayed too much, otherwise someone has to rebase it again.

**Comment by fieker** [comment]
On Mon, Mar 22, 2021 at 05:42:27AM -0700, thofma wrote:
> This is good to go. Should not be delayed too much, otherwise someone has to rebase it again.
> 
Do you want me to merge?

**Comment by thofma** [comment]
Sure

**Pull request merged**
