### PR TITLE
Add more monomial and module orderings

### PR DESCRIPTION
**Pull request by wbhart**
* Module orderings (incl. TOP and POT defined via * operator)
* Weighted orderings defined by weight vector
* Numerous missing orderings
* Factored out orderings into orderings.jl

### CODE REVIEW

**Comment by wdecker** [comment]
I have two questions here:

1) wnegdeglex,  wnegdegrevlex: shouldn't we rather write negwdeglex,  negwdegrevlex,
keeping the wdeg together?

2) How should, for example,  deglex(::AbstractVector{<:MPolyElem}) show up when calling the groebner_basis function?

Currently, this reads

groebner_basis(I::MPolyIdeal; ordering::Symbol = :degrevlex, complete_reduction::Bool = false)

Should we write 

groebner_basis(I::MPolyIdeal; ordering=:degrevlex, complete_reduction::Bool = false)

and something like

groebner_basis(I::MPolyIdeal; ordering=:wdegrevlex(W::Vector{Int}), complete_reduction::Bool = false)

in the weighted case?

Opinions?

**Comment by wbhart** [comment]
We currently haven't dealt with the std function, and will need to change the signature to support orderings that are not given by symbols.

I have no opinion on renaming the orderings. I thought that we followed the decision that was made at the meeting, but on second thought perhaps we didn't discuss this part in sufficient detail.

**Comment by HechtiDerLachs** [comment]
Has any further progress been made so that the groebner_basis function can digest the new orderings which are not merely given by symbols?

Edit: I found that the `singular_ring` routine can be used with the new orderings. But when p is of type `MonomialOrdering`, then one has to call `singular_ring(R, p.o)` rather than `singular_ring(R, p)`, i.e. one has to refer to an inner field of the actual ordering as an argument. This is not how it's supposed to be, right? 

Did I miss out on the intended way to use this, or is this going to be addressed in the future?

**Comment by tthsqe12** [comment]
Access to the private fields shouldn't be the part of any publich interface (unless it is explicitly documented).

**Comment by wbhart** [comment]
We haven't done that yet. We are waiting on some things downstream, but they are well in hand.

**Comment by fingolfin** [comment]
What's the status of this? Briefly, please: you said you are waiting for some things downstream. Which downstream is meant? AA? or Singular? It would be good to track this here so we know who is waiting for whom right now

**Comment by wbhart** [comment]
At present that has been worked around. We were waiting for block_diagonal matrices in AbstractAlgebra, but it turns out Hecke had them under a different name.

The main thing preventing merge here is documentation, which is today's task.

**Comment by wbhart** [comment]
Actually, I take it back. It seems that all the orderings need to be implemented on the Oscar side so that we can test them. The only reasonable test would be to check that a list of terms with respect to all these orderings end up in the right order.

As we don't maintain the Singular polynomials as well (or even have a conversion function as far as I can see), this means the orderings need to be implemented on the Oscar side, and this appears to be somewhat nontrivial (some of the basic ones are already there). Also, presumably some of the existing code actually depends on this working...

On the other hand, writing code to test on the Oscar side hardly tests that we hooked it all up to Singular correctly. So we also need tests of some Singular functionality that tests the orderings such as GB and GB_with_transform.

@hannes14 said he will also provide some test cases for the GB and leading_ideal stuff we added, tomorrow.

So, it's going to be next week before all this is done.

**Comment by wbhart** [comment]
Current status: we fixed the problems we were aware of.

I also want to add the ability to do monomial comparison using the new orderings (on the Oscar side) and tests for this. This will be a priority next week.

**Comment by wbhart** [comment]
I am also unsure if leading_term/monomial/coefficient are working with the new orderings. I need to check this and possibly add more tests, etc.

**Comment by tthsqe12** [comment]
So, what is the status here? I see a test is failing with `:negwdegrevlex` with weight vector `[1,2,1]` on variables `[x,y,z]`
From what I can see in the code, this constructs the weight matrix `[-1 -2 -1; -1 0 0; 0 -1 0]`. With the monomials `x^0*y^0*z^3` and `x^1*y^1*z^0`, I get a tie in the first row but the second row says the first monomial `x^0*y^0*z^3` is bigger. So, the just the test needs to be fixed?

**Comment by hannes14** [comment]
No, x*y should be larger than z3, the weight matrix should be [-1 -2 -1;0 0 -1; 0 -1 0].
I am working on it.

**Comment by fingolfin** [comment]
What's the status of this?

**Comment by wbhart** [comment]
The monomial orderings simply need to be corrected by @hannes14 . The branch belongs to him currently.

However, I believe he's been busy working on the Singular release, so we have to wait until he gets back to it.

**Comment by thofma** [comment]
Someone recently asked me about this. Is there an update on this? @hannes14?

**Comment by fingolfin** [comment]
Apparently there is a conflict here and @hannes14 and @fieker are supposed to look into resolving this

**Comment by fingolfin** [comment]
I've merged master into this now.

I hope this can now proceed?

**Comment by wbhart** [comment]
There were two completely mathematically different, incompatible patches to the code which I did not author or understand.

I am a number theorist, not an algebraic geometer. I could not simply "merge" the code. I had to understand how to apply both fixes mathematically, which I did not.

**Comment by fingolfin** [comment]
OK, I wasn't aware of "completely mathematically different, incompatible patches" that only an algebraic geometer could resolve. All I saw when merging where a few conflicts caused by trivial changes on `master` to code that was (re)moved in this PR, and then I had to fix some trivial test regressions. None of this required knowledge beyond undergrad year 1? Of course it's possible there are deeper problems now which I missed, but then it would still seem to me that the person most qualified to deal with them is the one who wrote most of the code in this PR?

Anyway, tests seem to pass now and the PR is mergeable again, at least on a technical level.

**Comment by wbhart** [comment]
The conflict was in the ModStdQ code, which I certainly do not understand. From memory (and I am certainly going from memory here; I don't have the time or interest to reconstruct everything) the conflict was caused because someone was adding a use_hilbert option, which I don't understand, and some issue with a keep_ordering flag which I don't understand. Any potential interaction of this with the use_hilbert option is completely unknown to me.

You seriously expect me to have just fixed the trivial merge conflict and not understand whether further changes were needed here to make this mathematically consistent/correct?

Your characterisation of the level of knowledge required to do this correctly is honestly pretty insulting and from my perspective incorrect.

Hannes had to fix the ordering stuff anyway (I had previously tried to do so multiple times according to his instructions, but the tests which are known to be correct kept failing, and the definitions seem to be Singular specific and are not something I can just look up in a textbook as far as I know even if that would be a good use of my time). Is it really so much to expect that Hannes also spend a couple of seconds with his specialist knowledge checking that the trivial merge is mathematically consistent? Or that the original authors of the code being merged do it?

After all the effort I put into this PR you question my intelligence for taking the high road and waiting for an expert to do what I believed only an expert should do!?

And you claim that the best person to fix the issue was the person who wrote the PR (me and Hannes jointly as it happens), even though I did not write any of the original code or the code to do with the conflict!?

I used my best judgement in dealing with this issue.

**Comment by tthsqe12** [comment]
So, I am looking into the merge conflicts right now. They do not look too bad, but I hope I haven't spoken too soon.

**Comment by tthsqe12** [comment]
this should be good to go now

**Comment by tthsqe12** [comment]
I can only guess the following was happening with the orderings:
the name "degrevlex" suggests it is "deg" + "revlex" but in fact it is "deg" plus "negrevlex". This combined with all of the possible permutations understandably had us confused.

**Comment by thofma** [comment]
Docstrings need adjustment.

**Comment by tthsqe12** [comment]
merge me please

**Pull request merged**
