### PR TITLE
Change order for groups to return fmpz by default

### PR DESCRIPTION
**Pull request by fingolfin**

### CODE REVIEW

**Comment by rfourquet** [comment]
I probably missed the background from somewhere else, but what is the motivation for this change?

**Comment by thofma** [comment]
The default cannot be an `Int`.

**Comment by rfourquet** [comment]
> The default cannot be an Int.

Oh OK, (I assume because it "too often" can't represent large enough values).

**Comment by fingolfin** [comment]
Type stability is the motivation: the old code returned either an Int or a BigInt, depending on what fits.

Moreover, we (well, at least @fieker and me) agreed last year that the default integer type for Oscar should be `fmpz`, so that's that (of course changing the default would be trivial now, too). But back then the conversion code for that was missing, so it was punted.

Also, issue #260 by @fieker is motivation.

One open problem is dealing with infinite orders. For now I wrote it so that one is supposed to check `isfinite`, but contemplating this again now, this only makes sense for groups, not for group elements (at least we don't define `isfinite` for those). I see that e.g. `order(P::EllCrvPt{fmpq})` "solves" this by using 0 to represent `infinity`, but I am strictly against that: it is confusing and far too easy to royally mess up handling it (e.g. checks like `order(g) < 10` or `order(g) % 5 == 0` silently break with this).

For the kind of code I write, it'd be probably most convenient if `order` returned say `Inf` in this case (and similar, `deg` for a zero polynomial could return `-Inf`). But of course "type stability"... Hmm, Or perhaps `fmpz` could be extended to have two further special "immediate" values, corresponding to + and - infinity (not sure anybody would be happy about that, though ;-))

**Pull request merged**
