### PR TITLE
Support computation of basis of H^(2,2) and H^4

### PR DESCRIPTION
**Pull request by HereAround**
cc @lkastner 

Motivated from F-theory applications.

(You might find this entertaining @apturner @emikelsons .)

### CODE REVIEW

**Comment by apturner** [comment]
At a glance, it looks like this is only computing the vertical part of the middle cohomology, is that right? Of course the others will be trickier, but I’m wondering based on the name of you are planning to compute the horizontal part as well.

**Comment by HereAround** [comment]
> At a glance, it looks like this is only computing the vertical part of the middle cohomology, is that right? Of course the others will be trickier, but I’m wondering based on the name of you are planning to compute the horizontal part as well.

I only want to get the vertical part.

**Review by apturner — APPROVED** [review]
Glad to see this is working now. Thanks @HereAround, looks good!

**Comment by HereAround** [comment]
@lkastner and @apturner I will merge this PR now, as I need this so that I can proceed with the draft of a paper on the `FTheoryTools`. If you have feedback, please let me know, and I will be happy to update/improve the methods.

Please note that I placed the method `basis_of_h22` in experimental (`FTheoryTools`), as it is relevant for and inspired by the related physics discussions. Still, from a math/algorithm perspective, it achieves the exact same (for simplicial, complete toric varieties) as `basis_of_h4`. As such, it would also seem reasonable to have both methods be called `basis_of_h4`, both be placed in the toric part of OSCAR, and call them with an optional "algorithm = ..." argument. The default algorithm could be the current method `basis_of_h4`, which relies on `monomial_basis`. Let me know your thoughts.

In case you wonder @lkastner , the algorithm with `monomial_basis` is painfully slow for big toric varieties, as it triggers a Groebner basis computation. One F-theory application that we are currently working on involves a simplicial, complete toric variety, whose cohomology ring is the quotient of a multivariate polynomial ring with 310 indeterminates and the ideal divided out is generated by about 47k generators. In this case, a GB computation is hopeless, which triggered the other algorithm `basis_of_h22`. For this involved variety, `basis_of_h22` completes in about 10 seconds on my computer.

(@wdecker Based on our conversation, you might find this entertaining. In particular, you were right - this problem could be cast into a linear equation system.)

**Pull request merged**
