### PR TITLE
proposal for the function coerce_down

### PR DESCRIPTION
**Pull request by ThomasBreuer**

### CODE REVIEW

**Review by fieker — COMMENTED** [review]
see in Hecke/src/NfAbs/NfAbs.jl the function force_coerce_cyclo

We should possibly see which versino is more efficient... but the coercion for cyclos in all directions was added in March for Ulli - not that he used it as far as I know...
It should be the "same" as in Magma

**Comment by ThomasBreuer** [comment]
@fieker Can it be the same as in Magma? As far as I know, Magma uses a different basis (described in the paper by Bosma) for representing elements in cyclotomic fields, which makes it obvious how to represent a given element of some cyclotomic field w.r.t. any smaller cyclotomic field that contains the element.
(GAP uses another basis to represent elements of cyclotomic fields, which can be interpreted as a compromise between cheap conversions between different cyclotomic fields and cheap applications of Galois automorphisms.)

**Comment by fieker** [comment]
On Thu, Sep 03, 2020 at 12:44:02AM -0700, ThomasBreuer wrote:
> @fieker Can it be the same as in Magma? As far as I know, Magma uses a different basis (described in the paper by Bosma) for representing elements in cyclotomic fields, which makes it obvious how to represent a given element of some cyclotomic field w.r.t. any smaller cyclotomic field that contains the element.
> (GAP uses another basis to represent elements of cyclotomic fields, which can be interpreted as a compromise between cheap conversions between different cyclotomic fields and cheap applications of Galois automorphisms.)
> 
The Bosma stuff is mostly no longer used. Cyclos share the same code as
all number fields (I just checked: Bosma is no more there)

I know about the Gap appraoch as well - it's your approach isn't it? My
personal experience was that mostly doing the "obvious" minimization
gives some performance boost, but mostly working in too large fields is
cheaper than using other presentations...

**Comment by fieker** [comment]
You you want to jitsi/ chat?

**Comment by fingolfin** [comment]
@fieker @ThomasBreuer are there any plans to continue this experiment at some point, or what's the plan?

**Comment by fieker** [comment]
On Fri, Mar 12, 2021 at 04:47:22AM -0800, Max Horn wrote:
> @fieker @ThomasBreuer are there any plans to continue this experiment at some point, or what's the plan?

The functionality is there, in Hecke....

**Comment by ThomasBreuer** [comment]
My plan was to continue with the character stuff as soon as I get more input from @ulthiel.

**Pull request closed without merging**
