### PR TITLE
Adapt to `isFOO` -> `is_FOO` changes

### PR DESCRIPTION
**Pull request by fingolfin**
This contains PR #1331 and the applies the renaming scripts from AA/Nemo/Hecke. I do not have such a script for Singular (maybe @tthsqe12 has one?), and I did not yet attempt similar renaming for Oscar specific functions.

This PR will likely require some extra tweaking. Moreover, there is a chance that this will conflicts with a bunch of PRs... I am happy to help with updating PRs, but OTOH it's trivial for me to update this PR to changes to `master` as it mostly is generated by scripts

### CODE REVIEW

**Comment by fingolfin** [comment]
Anyone know what this new failure is about?
```
Torsion points on elliptic curves: Error During Test at Oscar.jl/test/Experimental/PlaneCurve-test.jl:398
  Test threw exception
  Expression: Oscar.torsion_points_lutz_nagell(E) == [Q1]
  not the same curve
```
Perhaps the work on the EC code in Hecke is partially responsible, @thofma  @JHanselman ?

Or something else entirely?

**Comment by JHanselman** [comment]
> Anyone know what this new failure is about?
> 
> ```
> Torsion points on elliptic curves: Error During Test at Oscar.jl/test/Experimental/PlaneCurve-test.jl:398
>   Test threw exception
>   Expression: Oscar.torsion_points_lutz_nagell(E) == [Q1]
>   not the same curve
> ```
> 
> Perhaps the work on the EC code in Hecke is partially responsible, @thofma @JHanselman ?
> 
> Or something else entirely?

I took a quick look at what the reason for this failure is. It seems like it is the reliance of the PlaneCurve code on the field coeffs attached to an elliptic curve, which is basically redundant and only in there for compatibility with PlaneCurves. Removing it broke the Plane Curves functionality before and @thofma put in a quick fix for that to still keep the field, but it seems it wasn't enough.

What happens right now is that PlaneCurve creates an elliptic curve with coeffs [1,4] (and a_invars [0, 0, 0, 1, 4]). The torsion_points function then transforms the elliptic curve somehow and saves a curve with coeffs = [0, 0, 0, 1, 4] and (a_invars = [0, 0, 0, 1, 4]). The coeffs fields then get compared and you get an error. 

Letting PlaneCurve use the a_invars field (or even better, the function a_invars, which returns the a_invars field) every time it tries to access the coeffs field of a Hecke Elliptic Curve in Oscar should fix it, I think. I can't really test it myself right now.

(Or the coeffs field that's only in Hecke for compatibility with Oscar in the constructor should be changed to always be equal to a_invars).

**Comment by thofma** [comment]
I pushed a fix over at #1331.

**Comment by tthsqe12** [comment]
Here was the singular-specific rename.sh:
```
#!/bin/sh
for sym in bad_name constant default_twosided_ideal gen monomial ordering_symbolic ordering_symbolic_with_symbol quotient_ring term unit var_generated zerodim
do
    echo "Rename is$sym to is_$sym"
    git ls-files | xargs perl -pi -e "s;\bis$sym\b;is_$sym;g"
done
```

**Comment by fingolfin** [comment]
Ready from my point of view (could and probably should be squashed, not merged or rebased)

**Comment by thofma** [comment]
Since no one spoke up regarding merging other PRs first, lets get this in.

**Pull request merged**
