### PR TITLE
Rename `is_*_form` to `is_*`

### PR DESCRIPTION
**Pull request by lgoettgens**
This changes the code to just add dispatches to already defined functions, instead of declaring new functions.

### CODE REVIEW

**Review by thofma — APPROVED** [review]
Makes sense

**Comment by benlorenz** [comment]
Once all jobs are done (either failed or successful) you can just restart the failed jobs instead of running everything again by reopening the PR.
Also nightly is broken again due to some changes in the julia SparseArrays interface.

**Comment by lgoettgens** [comment]
> Once all jobs are done (either failed or successful) you can just restart the failed jobs instead of running everything again by reopening the PR.

I cannot find that button in the Oscar repos (where it is in my private ones). Maybe I do not have the rights to do that?

> Also nightly is broken again due to some changes in the julia SparseArrays interface.

Thanks for letting me know.

**Review by fingolfin — APPROVED** [review]

**Comment by lgoettgens** [comment]
The errors on nightly and 1.10-alpha1 are not due to changes here.

**Comment by thofma** [comment]
Needs a rebase

**Comment by lgoettgens** [comment]
> Needs a rebase

Done

**Pull request merged**
