### PR TITLE
Add `@attr` types in simple cases

### PR DESCRIPTION
**Pull request by lgoettgens**
If one only adds `@attr` to a function without giving a type, one shadows all inference of this function for callers of this function as the `@attr` code changes the inference result to `Any`. This PR thus adds types there, where it was obvious to me what the return type is, or where the compiler was able to prove a concrete return type (if one removes the `@attr` to allow for real inference).

The commits are partitioned by the area they touch. Let me ping some people in the different areas here to make them aware / get a review.
- Lie algebras -> myself, no review needed
- lattices -> @StevellM or maybe @ThomasBreuer ?
- schemes -> @afkafkafk13 @HechtiDerLachs 
- rings -> @jankoboehm @HechtiDerLachs 
- groups -> @ThomasBreuer

### CODE REVIEW

**Review by afkafkafk13 — COMMENTED** [review]
Those in my courtyard are fine. ( src/AlgebraicGeometry/Schemes/CoveredSchemes/Objects/Properties.jl )
ToricVarieties is in @HereAround 's courtyard.

**Review by afkafkafk13 — COMMENTED** [review]
I'm not @jankoboehm , but from my point of view the changes around rings are spot-on.

**Comment by StevellM** [comment]
For `lattices_with_isometry.jl` and `spinor_norms.jl`, if the tests pass, then I am good.

**Comment by ThomasBreuer** [comment]
Yes, this is o.k.

**Review by afkafkafk13 — APPROVED** [review]
As everyone answered in the meantime, I now put this on approve.

**Pull request merged**
