### PR TITLE
fix typo/ julia change: ' -> transpose

### PR DESCRIPTION
**Pull request by fieker**

### CODE REVIEW

**Comment by thofma** [comment]
The test you added seems to fail.

**Comment by benlorenz** [comment]
After the merge of this PR to master, the error from the new test with julia 1.6 now appeared on another PR as well: https://github.com/oscar-system/Oscar.jl/actions/runs/4135274562/jobs/7147510937#step:6:962
It doesn't happen reliably though, the tests on master directly after the merge were fine.

**Comment by thofma** [comment]
Yes, it was failing as I noticed.

**Comment by thofma** [comment]
@fieker

**Pull request merged**
